Repository files-community/Files, pull requests merged in 2019-12, with the labels that each got.

#266 Add ability to jump to directory item by typing
  Files UWP/GenericFileBrowser.xaml
  Files UWP/GenericFileBrowser.xaml.cs
  Files UWP/PhotoAlbum.xaml.cs
  Files/BaseLayout.cs
  Files/Filesystem/ItemViewModel.cs
  Files/GenericFileBrowser.xaml
  Files/GenericFileBrowser.xaml.cs
  Files/Interacts/Interaction.cs
  Files/PhotoAlbum.xaml.cs
Labels: enhancement, review needed

#288 Add folder properties to ribbon, right-click menu
  Files/Controls/RibbonArea.xaml
  Files/Filesystem/ItemViewModel.cs
  Files/GenericFileBrowser.xaml
  Files/Interacts/Interaction.cs
  Files/PhotoAlbum.xaml
  Files/Properties.xaml.cs
Labels: review needed

#321 Feat: Optional acrylic sidebar
  Files/ProHome.xaml
  Files/ProHome.xaml.cs
  Files/SettingsPages/Personalization.xaml
  Files/SettingsPages/Personalization.xaml.cs
Labels: review needed

#353 QuickLook Integration
  Files.Launcher/Files.Launcher.csproj
  Files.Launcher/Program.cs
  Files.Launcher/QuickLook.cs
  Files/App.xaml.cs
  Files/GenericFileBrowser.xaml
  Files/GenericFileBrowser.xaml.cs
  Files/Interacts/Interaction.cs
Labels: enhancement, feature

#361 Choose Terminal Applications
  Files/App.xaml.cs
  Files/Assets/terminal/terminal.json
  Files/DataModels/TerminalFileModel.cs
  Files/DataModels/TerminalModel.cs
  Files/Files.csproj
  Files/Interacts/Interaction.cs
  Files/SettingsPages/Preferences.xaml
  Files/SettingsPages/Preferences.xaml.cs
Labels: review needed
