Repository files-community/Files, pull requests merged in 2019-11, with the labels that each got.

#257 Add enter keybinding to open file/folder
  Files UWP/GenericFileBrowser.xaml
  Files UWP/GenericFileBrowser.xaml.cs
  Files UWP/Interacts/Interaction.cs
  Files UWP/PhotoAlbum.xaml
  Files UWP/PhotoAlbum.xaml.cs
Labels: enhancement, feature

#249 Allow inline, direct renaming in file list
  Files UWP/GenericFileBrowser.xaml
  Files UWP/GenericFileBrowser.xaml.cs
  Files UWP/Interacts/Interaction.cs
  Files UWP/PhotoAlbum.xaml
  Files UWP/PhotoAlbum.xaml.cs
Labels: enhancement

#262 Dynamic Drives List
  Files UWP/App.xaml.cs
  Files UWP/Dialogs/ExtractFilesDialog.xaml
  Files UWP/Dialogs/ExtractFilesDialog.xaml.cs
  Files UWP/FilesUWP.csproj
  Files UWP/Filesystem/DriveItem.cs
  Files UWP/GenericFileBrowser.xaml
  Files UWP/GenericFileBrowser.xaml.cs
  Files UWP/Interacts/Interaction.cs
  Files UWP/PhotoAlbum.xaml
  Files UWP/PhotoAlbum.xaml.cs
  Files UWP/ProHome.xaml
  Files UWP/ProHome.xaml.cs
  ProcessLauncher/Program.cs
Labels: enhancement

#277 Show "Open File Location" on recent files only
  Files UWP/YourHome.xaml
  Files UWP/YourHome.xaml.cs
Labels: review needed
