Repository files-community/Files, pull requests merged in 2020-06, with the labels that each got.

#888 Translation update + Strings added
  Files/Filesystem/ListedItem.cs
  Files/MultilingualResources/Files.de-DE.xlf
  Files/MultilingualResources/Files.es-ES.xlf
  Files/MultilingualResources/Files.fr-FR.xlf
  Files/MultilingualResources/Files.it-IT.xlf
  Files/MultilingualResources/Files.nl-NL.xlf
  Files/MultilingualResources/Files.pl-PL.xlf
  Files/MultilingualResources/Files.ru-RU.xlf
  Files/MultilingualResources/Files.ta.xlf
  Files/MultilingualResources/Files.tr-TR.xlf
  Files/MultilingualResources/Files.uk-UA.xlf
  Files/MultilingualResources/Files.zh-Hans.xlf
  Files/Strings/en-US/Resources.resw
  Files/Strings/es-ES/Resources.resw
Labels: approved

#908 Resource update [ta]
  Files/Strings/ta/Resources.resw
Labels: approved

#914 Remove terminal from json if terminal app has been removed
  Files/DataModels/TerminalFileModel.cs
  Files/Files.csproj
  Files/Helpers/PackageHelper.cs
  Files/View Models/SettingsViewModel.cs
Labels: approved

#920 Translation update [Spanish]
  Files/MultilingualResources/Files.es-ES.xlf
  Files/Strings/es-ES/Resources.resw
Labels: needs-review

#919 Improved settings code
  Files/DataModels/TerminalModel.cs
  Files/Filesystem/ListedItem.cs
  Files/Helpers/PackageHelper.cs
  Files/UserControls/LayoutModes/GenericFileBrowser.xaml
  Files/UserControls/LayoutModes/GridViewBrowser.xaml
  Files/View Models/InteractionViewModel.cs
  Files/Views/InstanceTabsView.xaml
  Files/Views/SettingsPages/Appearance.xaml
  Files/Views/SettingsPages/Appearance.xaml.cs
  Files/Views/SettingsPages/Experimental.xaml
  Files/Views/SettingsPages/Experimental.xaml.cs
  Files/Views/SettingsPages/FilesAndFolders.xaml
  Files/Views/SettingsPages/FilesAndFolders.xaml.cs
  Files/Views/SettingsPages/OnStartup.xaml
  Files/Views/SettingsPages/OnStartup.xaml.cs
  Files/Views/SettingsPages/Preferences.xaml
  Files/Views/SettingsPages/Preferences.xaml.cs
Labels: approved

#898 Fix renaming files with long names in GridViewBrowser
  Files/UserControls/LayoutModes/GridViewBrowser.xaml
  Files/UserControls/LayoutModes/GridViewBrowser.xaml.cs
Labels: needs-review

#923 Update version number to v0.9.2
  Files.Package/Package.appxmanifest
Labels: approved

#928 feat: Open item with
  Files/BaseLayout.cs
  Files/Interacts/Interaction.cs
  Files/MultilingualResources/Files.de-DE.xlf
  Files/MultilingualResources/Files.es-ES.xlf
  Files/MultilingualResources/Files.fr-FR.xlf
  Files/MultilingualResources/Files.it-IT.xlf
  Files/MultilingualResources/Files.nl-NL.xlf
  Files/MultilingualResources/Files.pl-PL.xlf
  Files/MultilingualResources/Files.ru-RU.xlf
  Files/MultilingualResources/Files.ta.xlf
  Files/MultilingualResources/Files.tr-TR.xlf
  Files/MultilingualResources/Files.uk-UA.xlf
  Files/MultilingualResources/Files.zh-Hans.xlf
  Files/Strings/en-US/Resources.resw
  Files/Strings/es-ES/Resources.resw
  Files/UserControls/LayoutModes/GenericFileBrowser.xaml
  Files/UserControls/LayoutModes/GridViewBrowser.xaml
Labels: approved

#932 Fix settings
  Files/View Models/SettingsViewModel.cs
  Files/Views/SettingsPages/Experimental.xaml
  Files/Views/SettingsPages/FilesAndFolders.xaml
  Files/Views/SettingsPages/FilesAndFolders.xaml.cs
  Files/Views/SettingsPages/OnStartup.xaml
  Files/Views/SettingsPages/Preferences.xaml
  Files/Views/SettingsPages/Preferences.xaml.cs
Labels: approved

#933 Fix creating a folder or file with restricted names or characters
  Files/Dialogs/RenameDialog.xaml
  Files/Dialogs/RenameDialog.xaml.cs
  Files/Interacts/Interaction.cs
  Files/MultilingualResources/Files.de-DE.xlf
  Files/MultilingualResources/Files.es-ES.xlf
  Files/MultilingualResources/Files.fr-FR.xlf
  Files/MultilingualResources/Files.it-IT.xlf
  Files/MultilingualResources/Files.nl-NL.xlf
  Files/MultilingualResources/Files.pl-PL.xlf
  Files/MultilingualResources/Files.ru-RU.xlf
  Files/MultilingualResources/Files.ta.xlf
  Files/MultilingualResources/Files.tr-TR.xlf
  Files/MultilingualResources/Files.uk-UA.xlf
  Files/MultilingualResources/Files.zh-Hans.xlf
  Files/Strings/en-US/Resources.resw
  Files/Strings/ru-RU/Resources.resw
  Files/Strings/uk-UA/Resources.resw
  Files/UserControls/LayoutModes/GenericFileBrowser.xaml
  Files/UserControls/LayoutModes/GenericFileBrowser.xaml.cs
  Files/UserControls/LayoutModes/GridViewBrowser.xaml
  Files/UserControls/LayoutModes/GridViewBrowser.xaml.cs
Labels: approved

#938 fixed auto selection when renaming if extensions are hidden
  Files/UserControls/LayoutModes/GenericFileBrowser.xaml.cs
  Files/UserControls/LayoutModes/GridViewBrowser.xaml.cs
Labels: approved

#941 Add ability to open sidebar drive in new window or tab
  Files/UserControls/ModernSidebar.xaml
  Files/UserControls/ModernSidebar.xaml.cs
Labels: needs-review

#942 Dialogs: Hide rename dialog if user pressed Esc button
  Files/Dialogs/AddItemDialog.xaml.cs
  Files/Dialogs/RenameDialog.xaml
  Files/Dialogs/RenameDialog.xaml.cs
Labels: needs-review

#943 Added button to open debug.txt location in explorer
  Files/MultilingualResources/Files.de-DE.xlf
  Files/MultilingualResources/Files.es-ES.xlf
  Files/MultilingualResources/Files.fr-FR.xlf
  Files/MultilingualResources/Files.it-IT.xlf
  Files/MultilingualResources/Files.nl-NL.xlf
  Files/MultilingualResources/Files.pl-PL.xlf
  Files/MultilingualResources/Files.ru-RU.xlf
  Files/MultilingualResources/Files.ta.xlf
  Files/MultilingualResources/Files.tr-TR.xlf
  Files/MultilingualResources/Files.uk-UA.xlf
  Files/MultilingualResources/Files.zh-Hans.xlf
  Files/Strings/en-US/Resources.resw
  Files/Strings/ru-RU/Resources.resw
  Files/Strings/uk-UA/Resources.resw
  Files/Views/SettingsPages/About.xaml
  Files/Views/SettingsPages/About.xaml.cs
Labels: approved

#940 Fixed md5 visibility and check boxes spacing
  Files/Views/Pages/Properties.xaml
  Files/Views/Pages/Properties.xaml.cs
Labels: approved

#937 Change how to get Dispatcher
  Files/Filesystem/Drives.cs
  Files/Helpers/ThemeHelper.cs
  Files/Interacts/Interaction.cs
  Files/Views/SettingsPages/Preferences.xaml.cs
Labels: needs-review

#939 Translation Update [ES]
  Files/MultilingualResources/Files.es-ES.xlf
  Files/Strings/es-ES/Resources.resw
Labels: approved

#951 Added option to unpin libraries from the sidebar
  Files.Package/Package.appxmanifest
  Files/View Models/SettingsViewModel.cs
Labels: needs-review

#960 Add margin to gridview item
  Files/UserControls/LayoutModes/GridViewBrowser.xaml
Labels: approved

#964 Added keyboard shortcuts to the tooltip of buttons in the navigation bar
  Files/MultilingualResources/Files.de-DE.xlf
  Files/MultilingualResources/Files.es-ES.xlf
  Files/MultilingualResources/Files.fr-FR.xlf
  Files/MultilingualResources/Files.it-IT.xlf
  Files/MultilingualResources/Files.nl-NL.xlf
  Files/MultilingualResources/Files.pl-PL.xlf
  Files/MultilingualResources/Files.ru-RU.xlf
  Files/MultilingualResources/Files.ta.xlf
  Files/MultilingualResources/Files.tr-TR.xlf
  Files/MultilingualResources/Files.uk-UA.xlf
  Files/MultilingualResources/Files.zh-Hans.xlf
  Files/Strings/en-US/Resources.resw
  Files/Strings/es-ES/Resources.resw
  Files/UserControls/NavigationToolbar/ModernNavigationToolbar.xaml
  Files/Views/InstanceTabsView.xaml
Labels: approved

#954 Update re-pinned library icons without restarting the app
  Files/Interacts/Interaction.cs
Labels: needs-review

#989 Terminal: Use path as terminal identifier
  Files/Assets/terminal/terminal.json
  Files/DataModels/TerminalFileModel.cs
  Files/DataModels/TerminalModel.cs
  Files/View Models/SettingsViewModel.cs
  Files/Views/SettingsPages/Preferences.xaml.cs
Labels: needs-review

#998 Updated Chinese Simplified translation 简体中文
  Files/MultilingualResources/Files.zh-Hans.xlf
Labels: approved

#1012 Properties: Fix Properties window crash on older systems
  Files/Dialogs/PropertiesDialog.xaml
  Files/Interacts/Interaction.cs
  Files/Views/Pages/Properties.xaml.cs
Labels: approved

#1013 Update resources [zh-Hans]
  Files/Strings/zh-Hans/Resources.resw
Labels: approved

#1018 Proposal: Custom icons for Tiles view and List view in layout mode menu
  Files/App.xaml
  Files/Assets/Custom Glyphs/layout-mode-custom-icon.ttf
  Files/Files.csproj
  Files/UserControls/StatusBarControl.xaml
Labels: approved

#1011 Fixed a crash when using the high contrast theme
  Files/App.xaml
  Files/Views/Pages/Properties.xaml.cs
Labels: approved

#1026 Updated status bar
  Files/App.xaml.cs
  Files/BaseLayout.cs
  Files/Files.csproj
  Files/MultilingualResources/Files.de-DE.xlf
  Files/MultilingualResources/Files.es-ES.xlf
  Files/MultilingualResources/Files.fr-FR.xlf
  Files/MultilingualResources/Files.it-IT.xlf
  Files/MultilingualResources/Files.ja-JP.xlf
  Files/MultilingualResources/Files.nl-NL.xlf
  Files/MultilingualResources/Files.pl-PL.xlf
  Files/MultilingualResources/Files.ru-RU.xlf
  Files/MultilingualResources/Files.ta.xlf
  Files/MultilingualResources/Files.tr-TR.xlf
  Files/MultilingualResources/Files.uk-UA.xlf
  Files/MultilingualResources/Files.zh-Hans.xlf
  Files/Strings/en-US/Resources.resw
  Files/UserControls/StatusBarControl.xaml
  Files/UserControls/StatusBarControl.xaml.cs
  Files/View Models/SelectedItemsPropertiesViewModel.cs
Labels: needs-review

#1039 Translation update [ES]
  Files/MultilingualResources/Files.es-ES.xlf
  Files/Strings/es-ES/Resources.resw
Labels: approved

#1038 Updated italian translations
  Files/MultilingualResources/Files.it-IT.xlf
Labels: approved

#1044 [Fixed] #1034 Multi-Windows Cut Copy crash
  Files/Interacts/Interaction.cs
Labels: approved

#1048 Cancel previous watcher
  Files/Helpers/NativeDirectoryChangesHelper.cs
  Files/View Models/ItemViewModel.cs
Labels: needs-review

#1041 Update resources [it-IT]
  Files/MultilingualResources/Files.it-IT.xlf
  Files/Strings/it-IT/Resources.resw
Labels: approved

#1001 Prevent the file watching loop from still being alive after we kill it
  Files/Helpers/NativeDirectoryChangesHelper.cs
  Files/View Models/ItemViewModel.cs
Labels: approved

#1046 New language Files.zh-Hant.xlf
  Files/Files.csproj
  Files/MultilingualResources/Files.zh-Hant.xlf
Labels: approved

#1053 Updated version to 0.10.2
  Files.Package/Package.appxmanifest
Labels: needs-review

#1061 Fix quicklook detection
  Files.Launcher/Program.cs
  Files/App.xaml.cs
  Files/View Models/SettingsViewModel.cs
Labels: approved

#1063 Improve performance on selection operations
  Files/Files.csproj
  Files/Helpers/BulkObservableCollection.cs
  Files/UserControls/LayoutModes/GenericFileBrowser.xaml.cs
  Files/View Models/ItemViewModel.cs
Labels: approved

#1062 Improved support for opening multiple files at a time
  Files.Launcher/Program.cs
  Files.Launcher/Win32API.cs
  Files/Interacts/Interaction.cs
Labels: approved

#1065 Added item count to the status bar
  Files/App.xaml.cs
  Files/BaseLayout.cs
  Files/Files.csproj
  Files/MultilingualResources/Files.de-DE.xlf
  Files/MultilingualResources/Files.es-ES.xlf
  Files/MultilingualResources/Files.fr-FR.xlf
  Files/MultilingualResources/Files.it-IT.xlf
  Files/MultilingualResources/Files.ja-JP.xlf
  Files/MultilingualResources/Files.nl-NL.xlf
  Files/MultilingualResources/Files.pl-PL.xlf
  Files/MultilingualResources/Files.ru-RU.xlf
  Files/MultilingualResources/Files.ta.xlf
  Files/MultilingualResources/Files.tr-TR.xlf
  Files/MultilingualResources/Files.uk-UA.xlf
  Files/MultilingualResources/Files.zh-Hans.xlf
  Files/Strings/en-US/Resources.resw
  Files/UserControls/StatusBarControl.xaml
  Files/UserControls/StatusBarControl.xaml.cs
  Files/View Models/DirectoryPropertiesViewModel.cs
  Files/View Models/ItemViewModel.cs
  Files/View Models/SelectedItemsPropertiesViewModel.cs
Labels: approved

#1067 Translation update [ES]
  Files/MultilingualResources/Files.es-ES.xlf
  Files/Strings/es-ES/Resources.resw
Labels: needs-review

#768 Improved "last tab closing" behavior
  Files/Interacts/Interaction.cs
  Files/Views/InstanceTabsView.xaml.cs
Labels: approved

#1078 Upgrade SDK Version to v2004
  Files.Package/Files.Package.wapproj
  Files/Files.csproj
  MessageRelay/Files.MessageRelay.csproj
Labels: approved

#1064 ModernSidebar: Rework pinned to SideBar items model
  Files/App.xaml.cs
  Files/DataModels/SidebarPinnedModel.cs
  Files/Files.csproj
  Files/Interacts/Interaction.cs
  Files/UserControls/ModernSidebar.xaml
  Files/UserControls/ModernSidebar.xaml.cs
  Files/View Models/SettingsViewModel.cs
Labels: approved

#1079 Fixed converting "PinnedItems.txt" when it already conatins duplicate…
  Files/View Models/SettingsViewModel.cs
Labels: approved

#1072 Added ability to cancel hash computation
  Files/Interacts/Interaction.cs
  Files/Views/Pages/Properties.xaml.cs
Labels: approved

#1082 Properties: Show progress when calculating MD5 hash
  Files/Interacts/Interaction.cs
  Files/Views/Pages/Properties.xaml
  Files/Views/Pages/Properties.xaml.cs
Labels: approved

#1081 Launch file (with other files containing in folder as param) to support apps like Photos and Movies & TV + Include Files.Extensions (unused at the moment)
  Files.Extensions/Files.Extensions.vcxproj
  Files.Extensions/Files_Extensions.def
  Files.Extensions/PropertySheet.props
  Files.Extensions/SysProc.cpp
  Files.Extensions/SysProc.h
  Files.Extensions/TEBProc.h
  Files.Extensions/UserInteractionMode.cpp
  Files.Extensions/UserInteractionMode.h
  Files.Extensions/UserInteractionMode.idl
  Files.Extensions/Wnf.cpp
  Files.Extensions/Wnf.h
  Files.Extensions/packages.config
  Files.Extensions/pch.cpp
  Files.Extensions/pch.h
  Files.Extensions/readme.txt
  Files.sln
  Files/Files.csproj
  Files/Interacts/Interaction.cs
Labels: approved

#1084 Added pin path to sidebar to right click context menu
  Files/DataModels/SidebarPinnedModel.cs
  Files/Interacts/Interaction.cs
  Files/MultilingualResources/Files.de-DE.xlf
  Files/MultilingualResources/Files.es-ES.xlf
  Files/MultilingualResources/Files.fr-FR.xlf
  Files/MultilingualResources/Files.it-IT.xlf
  Files/MultilingualResources/Files.ja-JP.xlf
  Files/MultilingualResources/Files.nl-NL.xlf
  Files/MultilingualResources/Files.pl-PL.xlf
  Files/MultilingualResources/Files.ru-RU.xlf
  Files/MultilingualResources/Files.ta.xlf
  Files/MultilingualResources/Files.tr-TR.xlf
  Files/MultilingualResources/Files.uk-UA.xlf
  Files/MultilingualResources/Files.zh-Hans.xlf
  Files/Strings/en-US/Resources.resw
  Files/UserControls/LayoutModes/GenericFileBrowser.xaml
  Files/UserControls/LayoutModes/GridViewBrowser.xaml
Labels: approved

#1095 Fixed issue where the folder name wouldn't display on tabs
  Files/Views/InstanceTabsView.xaml.cs
Labels: approved

#1090 Automatically refresh the itemCount of the status bar
  Files/View Models/ItemViewModel.cs
Labels: approved

#1096 Add ability to empty recycle bin from sidebar context menu
  Files/UserControls/ModernSidebar.xaml
  Files/UserControls/ModernSidebar.xaml.cs
  Files/Views/InstanceTabsView.xaml
Labels: approved

#1102 Improved code layout
  Files/Files.csproj
  Files/INavigationToolbar.cs
  Files/UserControls/ModernNavigationToolbar.xaml
  Files/UserControls/ModernNavigationToolbar.xaml.cs
  Files/Views/LayoutModes/GenericFileBrowser.xaml
  Files/Views/LayoutModes/GenericFileBrowser.xaml.cs
  Files/Views/LayoutModes/GridViewBrowser.xaml
  Files/Views/LayoutModes/GridViewBrowser.xaml.cs
  Files/Views/ModernShellPage.xaml
  Files/Views/ModernShellPage.xaml.cs
  Files/Views/Settings.xaml
  Files/Views/Settings.xaml.cs
Labels: approved

#1099 Use FindFirstFile to calculate Directory Size Recursively
  Files/Interacts/Interaction.cs
  Files/View Models/ItemViewModel.cs
  Files/Views/Pages/Properties.xaml
  Files/Views/Pages/Properties.xaml.cs
Labels: approved

#1055 Added Support for Date Accessed and File Owner Properties
  Files/App.xaml.cs
  Files/BaseLayout.cs
  Files/Interacts/Interaction.cs
  Files/Strings/en-US/Resources.resw
  Files/UserControls/StatusBarControl.xaml
  Files/View Models/SelectedItemsPropertiesViewModel.cs
  Files/View Models/SettingsViewModel.cs
  Files/Views/Pages/Properties.xaml
  Files/Views/Pages/Properties.xaml.cs
  Files/Views/SettingsPages/Experimental.xaml
Labels: approved

#1133 Update Multilingual Resources + translation [ES]
  Files/MultilingualResources/Files.de-DE.xlf
  Files/MultilingualResources/Files.es-ES.xlf
  Files/MultilingualResources/Files.fr-FR.xlf
  Files/MultilingualResources/Files.it-IT.xlf
  Files/MultilingualResources/Files.ja-JP.xlf
  Files/MultilingualResources/Files.nl-NL.xlf
  Files/MultilingualResources/Files.pl-PL.xlf
  Files/MultilingualResources/Files.ru-RU.xlf
  Files/MultilingualResources/Files.ta.xlf
  Files/MultilingualResources/Files.tr-TR.xlf
  Files/MultilingualResources/Files.uk-UA.xlf
  Files/MultilingualResources/Files.zh-Hans.xlf
  Files/Strings/es-ES/Resources.resw
Labels: needs-review

#1108 Add margin to folder size progress ring
  Files/Views/Pages/Properties.xaml
Labels: approved

#1135 Properties: Fix progressRing displayed for files properties
  Files/Interacts/Interaction.cs
  Files/View Models/ItemViewModel.cs
  Files/View Models/SelectedItemsPropertiesViewModel.cs
  Files/Views/Pages/Properties.xaml.cs
Labels: approved

#1139 Properties: Prevent crash when access denied
  Files/View Models/SelectedItemsPropertiesViewModel.cs
  Files/Views/Pages/Properties.xaml
Labels: approved

#1138 Fix incorrect item size value
  Files/Filesystem/DriveItem.cs
  Files/MultilingualResources/Files.de-DE.xlf
  Files/MultilingualResources/Files.es-ES.xlf
  Files/MultilingualResources/Files.fr-FR.xlf
  Files/MultilingualResources/Files.it-IT.xlf
  Files/MultilingualResources/Files.ja-JP.xlf
  Files/MultilingualResources/Files.nl-NL.xlf
  Files/MultilingualResources/Files.pl-PL.xlf
  Files/MultilingualResources/Files.ru-RU.xlf
  Files/MultilingualResources/Files.ta.xlf
  Files/MultilingualResources/Files.tr-TR.xlf
  Files/MultilingualResources/Files.uk-UA.xlf
  Files/MultilingualResources/Files.zh-Hans.xlf
  Files/Strings/en-US/Resources.resw
  Files/View Models/ItemViewModel.cs
  Files/View Models/SelectedItemsPropertiesViewModel.cs
Labels: approved

#1136 Set WorkingDirectory for terminal
  Files.Launcher/Program.cs
  Files/Assets/terminal/terminal.json
  Files/Interacts/Interaction.cs
  Files/View Models/SettingsViewModel.cs
  Files/Views/SettingsPages/Appearance.xaml.cs
Labels: approved

#1141 Fix issue where terminal.json has been overwritten on every app launch
  Files/DataModels/TerminalFileModel.cs
Labels: approved

#1091 Bug fixes for handling network path
  Files/View Models/ItemViewModel.cs
  Files/Views/InstanceTabsView.xaml.cs
Labels: approved

#1145 Properties: Fix some properties loading on older systems
  Files/View Models/SelectedItemsPropertiesViewModel.cs
  Files/Views/Pages/Properties.xaml
  Files/Views/Pages/Properties.xaml.cs
Labels: approved

#1151 Add ability to convert size abbreviations and translate them
  Common/ShellFileItem.cs
  Files.Launcher/Program.cs
  Files/Filesystem/DriveItem.cs
  Files/Filesystem/ListedItem.cs
  Files/Helpers/StringExtensions.cs
  Files/MultilingualResources/Files.de-DE.xlf
  Files/MultilingualResources/Files.es-ES.xlf
  Files/MultilingualResources/Files.fr-FR.xlf
  Files/MultilingualResources/Files.it-IT.xlf
  Files/MultilingualResources/Files.ja-JP.xlf
  Files/MultilingualResources/Files.nl-NL.xlf
  Files/MultilingualResources/Files.pl-PL.xlf
  Files/MultilingualResources/Files.ru-RU.xlf
  Files/MultilingualResources/Files.ta.xlf
  Files/MultilingualResources/Files.tr-TR.xlf
  Files/MultilingualResources/Files.uk-UA.xlf
  Files/MultilingualResources/Files.zh-Hans.xlf
  Files/Strings/en-US/Resources.resw
  Files/Strings/ru-RU/Resources.resw
  Files/Strings/uk-UA/Resources.resw
  Files/View Models/ItemViewModel.cs
  Files/View Models/SelectedItemsPropertiesViewModel.cs
Labels: approved

#699 Bringing custom shellcontextmenu
  Files.Launcher/Files.Launcher.csproj
  Files.Launcher/Program.cs
  Files.Launcher/Win32API.cs
  Files.Launcher/packages.config
  Files/BaseLayout.cs
  Files/Files.csproj
  Files/Helpers/RegistryReader.cs
  Files/Helpers/ShellCommandParser.cs
  Files/Interacts/Interaction.cs
  Files/Views/LayoutModes/GenericFileBrowser.xaml
  Files/Views/LayoutModes/GenericFileBrowser.xaml.cs
  Files/Views/LayoutModes/GridViewBrowser.xaml
  Files/Views/LayoutModes/GridViewBrowser.xaml.cs
Labels: needs-review

#1167 Fix open in new window
  Files/App.xaml.cs
  Files/Views/InstanceTabsView.xaml.cs
Labels: approved

#1153 Properties: Show item location instead of full path
  Files/Helpers/StringExtensions.cs
  Files/View Models/SelectedItemsPropertiesViewModel.cs
Labels: approved

#1171 Cleaned up code base
  Files.Extensions/SysProc.cpp
  Files.Extensions/SysProc.h
  Files.Extensions/TEBProc.h
  Files.Extensions/UserInteractionMode.cpp
  Files.Extensions/UserInteractionMode.h
  Files.Extensions/UserInteractionMode.idl
  Files.Extensions/Wnf.cpp
  Files.Extensions/pch.cpp
  Files.Launcher/Program.cs
  Files.Launcher/QuickLook.cs
  Files.Launcher/Win32API.cs
  Files/App.xaml.cs
  Files/BaseLayout.cs
  Files/DataModels/SidebarPinnedModel.cs
  Files/Dialogs/AddItemDialog.xaml.cs
  Files/Dialogs/RenameDialog.xaml
  Files/Files.csproj
  Files/Filesystem/DriveItem.cs
  Files/Filesystem/Drives.cs
  Files/Helpers/BulkObservableCollection.cs
  Files/Helpers/NativeDirectoryChangesHelper.cs
  Files/Helpers/NativeFindStorageItemHelper.cs
  Files/Helpers/RegistryReader.cs
  Files/Helpers/ShellCommandParser.cs
  Files/Interacts/Interaction.cs
  Files/UserControls/ModernNavigationToolbar.xaml.cs
  Files/UserControls/SidebarControl.cs
  Files/UserControls/SidebarControl.xaml
  Files/UserControls/StatusBarControl.xaml
  Files/UserControls/StatusBarControl.xaml.cs
  Files/UserControls/YourHome.xaml.cs
  Files/View Models/CurrentInstanceViewModel.cs
  Files/View Models/DirectoryPropertiesViewModel.cs
  Files/View Models/InteractionViewModel.cs
  Files/View Models/ItemViewModel.cs
  Files/View Models/SelectedItemsPropertiesViewModel.cs
  Files/Views/InstanceTabsView.xaml
  Files/Views/InstanceTabsView.xaml.cs
  Files/Views/LayoutModes/GenericFileBrowser.xaml.cs
  Files/Views/ModernShellPage.xaml
  Files/Views/ModernShellPage.xaml.cs
  Files/Views/Pages/Properties.xaml
  Files/Views/Pages/Properties.xaml.cs
  Files/Views/Settings.xaml.cs
  Files/Views/SettingsPages/Appearance.xaml.cs
  Files/Views/SettingsPages/FilesAndFolders.xaml.cs
  Files/Views/SettingsPages/OnStartup.xaml.cs
  Files/Views/SettingsPages/Preferences.xaml.cs
Labels: approved

#1168 Drives: Fixed drives loading when no letter assigned to partition
  Files/Filesystem/Drives.cs
Labels: approved

#1184 Added icons in context menu of the sidebar and "More options" + Custom icon for "New tab" and "Open in new tab"
  Files/App.xaml
  Files/Assets/Custom Glyphs/newtab-icon.ttf
  Files/Files.csproj
  Files/UserControls/ModernNavigationToolbar.xaml
  Files/UserControls/SidebarControl.xaml
  Files/Views/LayoutModes/GenericFileBrowser.xaml
  Files/Views/LayoutModes/GridViewBrowser.xaml
Labels: approved

#1186 1185: "Open", "Open with", "open in new tab / window" and "pin to sidebar" no longer appear in the item context menu
  Files/BaseLayout.cs
  Files/Views/LayoutModes/GenericFileBrowser.xaml
  Files/Views/LayoutModes/GridViewBrowser.xaml
Labels: approved

#1187 Cleaned up settings
  Files/MultilingualResources/Files.de-DE.xlf
  Files/MultilingualResources/Files.es-ES.xlf
  Files/MultilingualResources/Files.fr-FR.xlf
  Files/MultilingualResources/Files.it-IT.xlf
  Files/MultilingualResources/Files.ja-JP.xlf
  Files/MultilingualResources/Files.nl-NL.xlf
  Files/MultilingualResources/Files.pl-PL.xlf
  Files/MultilingualResources/Files.ru-RU.xlf
  Files/MultilingualResources/Files.ta.xlf
  Files/MultilingualResources/Files.tr-TR.xlf
  Files/MultilingualResources/Files.uk-UA.xlf
  Files/MultilingualResources/Files.zh-Hans.xlf
  Files/Strings/en-US/Resources.resw
  Files/Views/SettingsPages/About.xaml
  Files/Views/SettingsPages/Appearance.xaml
  Files/Views/SettingsPages/Preferences.xaml
Labels: needs-review

#1188 Status bar: Show total size of selected files
  Files/BaseLayout.cs
Labels: approved

#1189 Updated docs
  Contributing.md
  README.md
  contributing.md
Labels: approved

#1190 Fixed app launch
  Files/DataModels/SidebarPinnedModel.cs
  Files/Views/InstanceTabsView.xaml.cs
Labels: approved

#1192 Translation update [ES]
  Files/MultilingualResources/Files.es-ES.xlf
  Files/Strings/es-ES/Resources.resw
Labels: approved

#1169 Properties: Display how many folders and files a folder contains
  Files/MultilingualResources/Files.de-DE.xlf
  Files/MultilingualResources/Files.es-ES.xlf
  Files/MultilingualResources/Files.fr-FR.xlf
  Files/MultilingualResources/Files.it-IT.xlf
  Files/MultilingualResources/Files.ja-JP.xlf
  Files/MultilingualResources/Files.nl-NL.xlf
  Files/MultilingualResources/Files.pl-PL.xlf
  Files/MultilingualResources/Files.ru-RU.xlf
  Files/MultilingualResources/Files.ta.xlf
  Files/MultilingualResources/Files.tr-TR.xlf
  Files/MultilingualResources/Files.uk-UA.xlf
  Files/MultilingualResources/Files.zh-Hans.xlf
  Files/Strings/en-US/Resources.resw
  Files/Strings/ru-RU/Resources.resw
  Files/Strings/uk-UA/Resources.resw
  Files/View Models/DirectoryPropertiesViewModel.cs
  Files/View Models/SelectedItemsPropertiesViewModel.cs
  Files/Views/Pages/Properties.xaml
  Files/Views/Pages/Properties.xaml.cs
Labels: approved

#1207 Update Files.de-DE.xlf
  Files/MultilingualResources/Files.de-DE.xlf
Labels: triage approved

#1211 Properties: Add support for combined and drive properties
  Files/BaseLayout.cs
  Files/Enums/PropertiesType.cs
  Files/Files.csproj
  Files/Interacts/Interaction.cs
  Files/MultilingualResources/Files.de-DE.xlf
  Files/MultilingualResources/Files.es-ES.xlf
  Files/MultilingualResources/Files.fr-FR.xlf
  Files/MultilingualResources/Files.it-IT.xlf
  Files/MultilingualResources/Files.ja-JP.xlf
  Files/MultilingualResources/Files.nl-NL.xlf
  Files/MultilingualResources/Files.pl-PL.xlf
  Files/MultilingualResources/Files.ru-RU.xlf
  Files/MultilingualResources/Files.ta.xlf
  Files/MultilingualResources/Files.tr-TR.xlf
  Files/MultilingualResources/Files.uk-UA.xlf
  Files/MultilingualResources/Files.zh-Hans.xlf
  Files/Strings/de-DE/Resources.resw
  Files/Strings/en-US/Resources.resw
  Files/Strings/es-ES/Resources.resw
  Files/Strings/ru-RU/Resources.resw
  Files/Strings/uk-UA/Resources.resw
  Files/UserControls/StatusBarControl.xaml
  Files/View Models/SelectedItemsPropertiesViewModel.cs
  Files/View Models/SettingsViewModel.cs
  Files/Views/Pages/Properties.xaml
  Files/Views/Pages/Properties.xaml.cs
  Files/Views/SettingsPages/Experimental.xaml
Labels: approved, needs-review

#1200 Fix NullReferenceException for some scenarios
  Files/View Models/SettingsViewModel.cs
  Files/Views/InstanceTabsView.xaml.cs
Labels: approved

#1214 Properties: Replace "combined files" icon
  Files/App.xaml
  Files/Assets/Custom Glyphs/Custom-Glyphs.ttf
  Files/Assets/Custom Glyphs/layout-mode-custom-icon.ttf
  Files/Assets/Custom Glyphs/newtab-icon.ttf
  Files/Files.csproj
  Files/UserControls/ModernNavigationToolbar.xaml
  Files/UserControls/SidebarControl.xaml
  Files/Views/LayoutModes/GenericFileBrowser.xaml
  Files/Views/LayoutModes/GridViewBrowser.xaml
  Files/Views/Pages/Properties.xaml
Labels: approved

#1223 Fix: Status bar is not visible
  Files/UserControls/StatusBarControl.xaml
Labels: approved

#1224 Fix JSON loading when it's empty
  Files/View Models/SettingsViewModel.cs
Labels: approved

#1159 Add support for Bitlocker
  Files.Launcher/Program.cs
  Files.Launcher/Win32API.cs
  Files/Dialogs/BitlockerDialog.xaml
  Files/Dialogs/BitlockerDialog.xaml.cs
  Files/Files.csproj
  Files/MultilingualResources/Files.de-DE.xlf
  Files/MultilingualResources/Files.es-ES.xlf
  Files/MultilingualResources/Files.fr-FR.xlf
  Files/MultilingualResources/Files.it-IT.xlf
  Files/MultilingualResources/Files.ja-JP.xlf
  Files/MultilingualResources/Files.nl-NL.xlf
  Files/MultilingualResources/Files.pl-PL.xlf
  Files/MultilingualResources/Files.ru-RU.xlf
  Files/MultilingualResources/Files.ta.xlf
  Files/MultilingualResources/Files.tr-TR.xlf
  Files/MultilingualResources/Files.uk-UA.xlf
  Files/MultilingualResources/Files.zh-Hans.xlf
  Files/Strings/en-US/Resources.resw
  Files/View Models/ItemViewModel.cs
  Files/Views/LayoutModes/GenericFileBrowser.xaml.cs
  Files/Views/LayoutModes/GridViewBrowser.xaml.cs
Labels: needs-review

#1215 Removed AppCenter from debug mode
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/critical-high-priority-bug-report.md
  Files.Package/Package.appxmanifest
  Files/App.xaml.cs
  Files/Assets/FilesHome.png
  README.md
Labels: approved

#1233 Retrieve Better Thumbnails for files in Properties Dialog
  Files/Dialogs/PropertiesDialog.xaml
  Files/Dialogs/PropertiesDialog.xaml.cs
  Files/Views/Pages/Properties.xaml.cs
Labels: approved

#1234 Use Fluent Folder Glyph for Properties Dialog
  Files/Views/Pages/Properties.xaml
Labels: approved

#1235 Added a privacy policy file
  Privacy
Labels: approved

#1155 Modify context menu options for executable and installer files
  Files.Launcher/Program.cs
  Files.sln
  Files/BaseLayout.cs
  Files/Files.csproj
  Files/Interacts/Interaction.cs
  Files/MultilingualResources/Files.de-DE.xlf
  Files/MultilingualResources/Files.es-ES.xlf
  Files/MultilingualResources/Files.fr-FR.xlf
  Files/MultilingualResources/Files.it-IT.xlf
  Files/MultilingualResources/Files.ja-JP.xlf
  Files/MultilingualResources/Files.nl-NL.xlf
  Files/MultilingualResources/Files.pl-PL.xlf
  Files/MultilingualResources/Files.ru-RU.xlf
  Files/MultilingualResources/Files.ta.xlf
  Files/MultilingualResources/Files.tr-TR.xlf
  Files/MultilingualResources/Files.uk-UA.xlf
  Files/MultilingualResources/Files.zh-Hans.xlf
  Files/Strings/en-US/Resources.resw
  Files/Views/LayoutModes/GenericFileBrowser.xaml
  Files/Views/LayoutModes/GridViewBrowser.xaml
Labels: approved

#1231 Tweaked App Center
  Files/App.xaml.cs
Labels: approved

#1137 Recyclebin improvements
  Common/ShellFileItem.cs
  Files.Launcher/Program.cs
  Files.Launcher/Win32API.cs
  Files/BaseLayout.cs
  Files/DataModels/SidebarPinnedModel.cs
  Files/Interacts/Interaction.cs
  Files/MultilingualResources/Files.de-DE.xlf
  Files/MultilingualResources/Files.es-ES.xlf
  Files/MultilingualResources/Files.fr-FR.xlf
  Files/MultilingualResources/Files.it-IT.xlf
  Files/MultilingualResources/Files.ja-JP.xlf
  Files/MultilingualResources/Files.nl-NL.xlf
  Files/MultilingualResources/Files.pl-PL.xlf
  Files/MultilingualResources/Files.ru-RU.xlf
  Files/MultilingualResources/Files.ta.xlf
  Files/MultilingualResources/Files.tr-TR.xlf
  Files/MultilingualResources/Files.uk-UA.xlf
  Files/MultilingualResources/Files.zh-Hans.xlf
  Files/Strings/en-US/Resources.resw
  Files/UserControls/YourHome.xaml.cs
  Files/View Models/ItemViewModel.cs
  Files/View Models/SelectedItemsPropertiesViewModel.cs
  Files/Views/LayoutModes/GenericFileBrowser.xaml
  Files/Views/LayoutModes/GridViewBrowser.xaml
  Files/Views/Pages/Properties.xaml.cs
Labels: approved

#1237 Translation update [ES]
  Files/MultilingualResources/Files.es-ES.xlf
  Files/MultilingualResources/Files.ja-JP.xlf
  Files/Strings/es-ES/Resources.resw
Labels: approved

#1239 Added string for "New tab" that appears in path
  Files/Interacts/Interaction.cs
  Files/Navigation/NavigationActions.cs
  Files/UserControls/ModernNavigationToolbar.xaml.cs
  Files/UserControls/SidebarControl.cs
  Files/Views/InstanceTabsView.xaml.cs
  Files/Views/ModernShellPage.xaml.cs
Labels: approved

#1240 Added support for unpinning recycle bin from the sidebar
  Files/App.xaml.cs
  Files/UserControls/SidebarControl.cs
Labels: approved

#1250 Settings: Remove transition animations
  Files/Views/SettingsPages/About.xaml
  Files/Views/SettingsPages/Appearance.xaml
  Files/Views/SettingsPages/Experimental.xaml
  Files/Views/SettingsPages/FilesAndFolders.xaml
  Files/Views/SettingsPages/OnStartup.xaml
  Files/Views/SettingsPages/Preferences.xaml
Labels: approved

#1174 WIP: Op progress
  Files/BaseLayout.cs
  Files/Files.csproj
  Files/Interacts/Interaction.cs
  Files/MultilingualResources/Files.de-DE.xlf
  Files/MultilingualResources/Files.es-ES.xlf
  Files/MultilingualResources/Files.fr-FR.xlf
  Files/MultilingualResources/Files.it-IT.xlf
  Files/MultilingualResources/Files.ja-JP.xlf
  Files/MultilingualResources/Files.nl-NL.xlf
  Files/MultilingualResources/Files.pl-PL.xlf
  Files/MultilingualResources/Files.ru-RU.xlf
  Files/MultilingualResources/Files.ta.xlf
  Files/MultilingualResources/Files.tr-TR.xlf
  Files/MultilingualResources/Files.uk-UA.xlf
  Files/MultilingualResources/Files.zh-Hans.xlf
  Files/Strings/en-US/Resources.resw
  Files/UserControls/StatusBarControl.xaml
  Files/UserControls/StatusCenter.xaml
  Files/UserControls/StatusCenter.xaml.cs
  Files/View Models/ItemViewModel.cs
  Files/Views/LayoutModes/GenericFileBrowser.xaml.cs
  Files/Views/ModernShellPage.xaml
  Files/Views/ModernShellPage.xaml.cs
Labels: approved, ready-to-merge

#1264 RecycleBin: Remove Properties menu item for the folder itself
  Files/Views/LayoutModes/GenericFileBrowser.xaml
  Files/Views/LayoutModes/GridViewBrowser.xaml
Labels: approved

#1254 Apply Tweaks to DataGrid FontSize, ColumnHeaders
  Files/Views/LayoutModes/GenericFileBrowser.xaml
Labels: approved

#1287 Removed docs in favor of the Wiki
  Contributing.md
  Translator.md
Labels: approved, needs-review

#1286 Fixed right click context menu on sidebar
  Files/UserControls/SidebarControl.cs
Labels: approved

#1301 Use direct URLs to community project
  Files/Views/SettingsPages/About.xaml.cs
  Files/Views/SettingsPages/Preferences.xaml
Labels: approved

#1298 Translation update [es-ES]
  Files/MultilingualResources/Files.es-ES.xlf
  Files/Strings/es-ES/Resources.resw
Labels: approved

#1295 Cleaned up code
  Common/ShellFileItem.cs
  Files.Launcher/Program.cs
  Files.Launcher/Win32API.cs
  Files/App.xaml.cs
  Files/BaseLayout.cs
  Files/DataModels/SidebarPinnedModel.cs
  Files/Dialogs/AddItemDialog.xaml
  Files/Dialogs/BitlockerDialog.xaml
  Files/Dialogs/ConsentDialog.xaml
  Files/Dialogs/ExceptionDialog.xaml
  Files/Dialogs/ExtractFilesDialog.xaml
  Files/Dialogs/LayoutDialog.xaml
  Files/Dialogs/PropertiesDialog.xaml
  Files/Dialogs/PropertiesDialog.xaml.cs
  Files/Dialogs/RenameDialog.xaml
  Files/Interacts/Interaction.cs
  Files/UserControls/ModernNavigationToolbar.xaml
  Files/UserControls/SidebarControl.cs
  Files/UserControls/SidebarControl.xaml
  Files/UserControls/StatusBarControl.xaml
  Files/UserControls/StatusCenter.xaml
  Files/UserControls/StatusCenter.xaml.cs
  Files/UserControls/YourHome.xaml.cs
  Files/View Models/ItemViewModel.cs
  Files/View Models/SettingsViewModel.cs
  Files/Views/InstanceTabsView.xaml.cs
  Files/Views/LayoutModes/GenericFileBrowser.xaml
  Files/Views/LayoutModes/GenericFileBrowser.xaml.cs
  Files/Views/LayoutModes/GridViewBrowser.xaml
  Files/Views/ModernShellPage.xaml
  Files/Views/ModernShellPage.xaml.cs
  Files/Views/Pages/Properties.xaml
  Files/Views/Pages/Properties.xaml.cs
  Files/Views/Settings.xaml.cs
  Files/Views/SettingsPages/About.xaml
Labels: approved

#1303 Translation: Update UA, RU translation
  Files/MultilingualResources/Files.ru-RU.xlf
  Files/MultilingualResources/Files.uk-UA.xlf
  Files/Strings/ru-RU/Resources.resw
  Files/Strings/uk-UA/Resources.resw
Labels: approved

#926 [PROPOSAL] - Access android (MTP) devices
  Common/Extensions.cs
  Files.Launcher/Program.cs
  Files/BaseLayout.cs
  Files/DataModels/SidebarPinnedModel.cs
  Files/Dialogs/AddItemDialog.xaml.cs
  Files/Files.csproj
  Files/Filesystem/DriveItem.cs
  Files/Filesystem/Drives.cs
  Files/Filesystem/StorageFileHelpers/IStorageItemWithPath.cs
  Files/Filesystem/StorageFileHelpers/StorageFileExtensions.cs
  Files/Filesystem/StorageFileHelpers/StorageFileWithPath.cs
  Files/Filesystem/StorageFileHelpers/StorageFolderWithPath.cs
  Files/Interacts/Interaction.cs
  Files/Navigation/NavigationActions.cs
  Files/UserControls/ModernNavigationToolbar.xaml
  Files/UserControls/ModernNavigationToolbar.xaml.cs
  Files/UserControls/YourHome.xaml.cs
  Files/View Models/CurrentInstanceViewModel.cs
  Files/View Models/ItemViewModel.cs
  Files/Views/InstanceTabsView.xaml.cs
  Files/Views/LayoutModes/GenericFileBrowser.xaml
  Files/Views/LayoutModes/GenericFileBrowser.xaml.cs
  Files/Views/LayoutModes/GridViewBrowser.xaml
  Files/Views/ModernShellPage.xaml.cs
  Files/Views/Pages/Properties.xaml.cs
Labels: approved
