Repository files-community/Files, pull requests merged in 2020-11, with the labels that each got.

#2200 Update Files.hu-HU.xlf
  Files/MultilingualResources/Files.hu-HU.xlf
Labels: approved

#2177 Fixed an issue where screen readers will wrongly read files and folders as Files.Filesystem.ListedItem
  Files/Filesystem/ListedItem.cs
  Files/MultilingualResources/Files.de-DE.xlf
  Files/MultilingualResources/Files.es-ES.xlf
  Files/MultilingualResources/Files.fr-FR.xlf
  Files/MultilingualResources/Files.he-IL.xlf
  Files/MultilingualResources/Files.hi-IN.xlf
  Files/MultilingualResources/Files.hu-HU.xlf
  Files/MultilingualResources/Files.it-IT.xlf
  Files/MultilingualResources/Files.ja-JP.xlf
  Files/MultilingualResources/Files.nl-NL.xlf
  Files/MultilingualResources/Files.or-IN.xlf
  Files/MultilingualResources/Files.pl-PL.xlf
  Files/MultilingualResources/Files.pt-BR.xlf
  Files/MultilingualResources/Files.ru-RU.xlf
  Files/MultilingualResources/Files.ta.xlf
  Files/MultilingualResources/Files.tr-TR.xlf
  Files/MultilingualResources/Files.uk-UA.xlf
  Files/MultilingualResources/Files.zh-Hans.xlf
  Files/Strings/en-US/Resources.resw
Labels: approved

#2215 Overhaul Codebase to Avoid Static App.CurrentInstance
  Files.Launcher/Program.cs
  Files.Package/Package.appxmanifest
  Files/App.xaml.cs
  Files/BaseLayout.cs
  Files/Commands/Delete.cs
  Files/Commands/ItemOperations.cs
  Files/Commands/Paste.cs
  Files/Dialogs/AddItemDialog.xaml.cs
  Files/Dialogs/ConfirmDeleteDialog.xaml.cs
  Files/Dialogs/ExceptionDialog.xaml.cs
  Files/Dialogs/RenameDialog.xaml.cs
  Files/Files.csproj
  Files/Filesystem/Drives.cs
  Files/INavigationToolbar.cs
  Files/IShellPage.cs
  Files/Interacts/Interaction.cs
  Files/MultilingualResources/Files.es-ES.xlf
  Files/Navigation/NavigationActions.cs
  Files/Properties/Default.rd.xml
  Files/UserControls/ModernNavigationToolbar.xaml
  Files/UserControls/ModernNavigationToolbar.xaml.cs
  Files/UserControls/MultitaskingControl/HorizontalMultitaskingControl.xaml.cs
  Files/UserControls/MultitaskingControl/IMultitaskingControl.cs
  Files/UserControls/MultitaskingControl/VerticalTabViewControl.xaml.cs
  Files/UserControls/SidebarControl.xaml
  Files/UserControls/SidebarControl.xaml.cs
  Files/UserControls/StatusBarControl.xaml
  Files/UserControls/StatusBarControl.xaml.cs
  Files/UserControls/Widgets/DrivesWidget.xaml.cs
  Files/UserControls/Widgets/LibraryCards.xaml.cs
  Files/UserControls/Widgets/RecentFiles.xaml.cs
  Files/UserControls/YourHome.xaml
  Files/UserControls/YourHome.xaml.cs
  Files/View Models/InteractionViewModel.cs
  Files/View Models/ItemViewModel.cs
  Files/View Models/Properties/BaseProperties.cs
  Files/View Models/Properties/CombinedProperties.cs
  Files/View Models/Properties/DriveProperties.cs
  Files/View Models/Properties/FileProperties.cs
  Files/View Models/Properties/FolderProperties.cs
  Files/View Models/Properties/PropertiesTab.cs
  Files/View Models/SelectedItemsPropertiesViewModel.cs
  Files/View Models/SettingsViewModel.cs
  Files/Views/LayoutModes/GenericFileBrowser.xaml
  Files/Views/LayoutModes/GenericFileBrowser.xaml.cs
  Files/Views/LayoutModes/GridViewBrowser.xaml
  Files/Views/LayoutModes/GridViewBrowser.xaml.cs
  Files/Views/MainPage.xaml.cs
  Files/Views/ModernShellPage.xaml
  Files/Views/ModernShellPage.xaml.cs
  Files/Views/Pages/Properties.xaml.cs
  Files/Views/Pages/PropertiesGeneral.xaml.cs
Labels: codebase quality, needs-review

#2163 Display available keyboard shortcuts in context menus
  Files/Interacts/Interaction.cs
  Files/UserControls/ModernNavigationToolbar.xaml
  Files/UserControls/StatusBarControl.xaml
  Files/Views/LayoutModes/GenericFileBrowser.xaml
  Files/Views/LayoutModes/GridViewBrowser.xaml
  Files/Views/LayoutModes/GridViewBrowser.xaml.cs
Labels: approved

#2374 Update lang fr-FR
  Files/MultilingualResources/Files.fr-FR.xlf
Labels: approved

#2390 Fix delayed item display bug
  Files/Helpers/BulkObservableCollection.cs
  Files/View Models/ItemViewModel.cs
  Files/Views/LayoutModes/GenericFileBrowser.xaml.cs
  Files/Views/LayoutModes/GridViewBrowser.xaml.cs
Labels: needs-review

#2430 [Hidden files] - Fix opening hidden folder in new tab
  Files/Interacts/Interaction.cs
  Files/View Models/ItemViewModel.cs
  Files/Views/ModernShellPage.xaml.cs
Labels: needs-review

#2432 CodeMaid
  Common/DeviceEvent.cs
  Files.Launcher/DeviceWatcher.cs
  Files/Enums/CloudProviders.cs
  Files/Filesystem/Cloud/CloudProvider.cs
  Files/Filesystem/Cloud/CloudProviderController.cs
  Files/Filesystem/Cloud/ICloudProviderDetector.cs
  Files/Filesystem/Cloud/Providers/AppleCloudProvider.cs
  Files/Filesystem/Cloud/Providers/BoxCloudProvider.cs
  Files/Filesystem/Cloud/Providers/DropBoxCloudProvider.cs
  Files/Filesystem/Cloud/Providers/GoogleDriveCloudProvider.cs
  Files/Filesystem/Cloud/Providers/MegaCloudProvider.cs
  Files/Filesystem/Cloud/Providers/OneDriveCloudProvider.cs
  Files/Filesystem/Cloud/Providers/OneDriveCommercialCloudProvider.cs
  Files/Filesystem/Drives.cs
  Files/Helpers/BulkObservableCollection.cs
  Files/Helpers/NativeDirectoryChangesHelper.cs
  Files/Helpers/NativeFileOperationsHelper.cs
  Files/Helpers/NativeIoDeviceControlHelper.cs
  Files/Helpers/NativeWinApiHelper.cs
  Files/Interacts/Interaction.cs
  Files/Interacts/RemovableDevice.cs
  Files/UserControls/SidebarControl.xaml.cs
  Files/UserControls/Widgets/DrivesWidget.xaml.cs
  Files/UserControls/Widgets/RecentFiles.xaml.cs
  Files/View Models/Properties/CombinedProperties.cs
  Files/View Models/Properties/FileProperties.cs
  Files/View Models/Properties/FolderProperties.cs
  Files/View Models/SelectedItemsPropertiesViewModel.cs
  Files/View Models/SettingsViewModel.cs
  Files/Views/LayoutModes/GenericFileBrowser.xaml.cs
  Files/Views/SettingsPages/Preferences.xaml.cs
Labels: approved

#2439 Removed the image property from the library widget
  Files/UserControls/Widgets/LibraryCards.xaml.cs
Labels: approved

#2440 Fix CloseHandle definition
  Files/Helpers/NativeIoDeviceControlHelper.cs
Labels: approved

#2441 Allow navigating to hidden folders from path bar
  Files/Views/ModernShellPage.xaml.cs
Labels: approved

#2444 Added NLog to rd.xml
  Files/Properties/Default.rd.xml
Labels: needs-review

#2443 Fix file watcher and order files on new item
  Files/View Models/ItemViewModel.cs
Labels: approved

#2445 Update Files.de-DE.xlf
  Files/MultilingualResources/Files.de-DE.xlf
Labels: approved

#2453 📓 Updated HUN
  Files/MultilingualResources/Files.hu-HU.xlf
Labels: approved

#2461 Update fr-FR
  Files/MultilingualResources/Files.fr-FR.xlf
Labels: needs-review

#2465 Fixed an issue where you cannot display more than 4 drives in a row on the home page
  Files/UserControls/Widgets/DrivesWidget.xaml
Labels: approved

#2459 Fixed an issue where clicking the back button on the settings page in tablet mode wouldn't work
  Files/Views/Settings.xaml.cs
Labels: approved

#2481 Fix files not showing when show hidden items is not enabled
  Files/View Models/ItemViewModel.cs
Labels: needs-review

#2474 Added the option to restore recently closed tabs
  Files/Dialogs/ExceptionDialog.xaml.cs
  Files/Files.csproj
  Files/Interacts/Interaction.cs
  Files/Strings/fr-FR/Resources.resw
  Files/Strings/hu-HU/Resources.resw
  Files/UserControls/MultitaskingControl/BaseMultitaskingControl.cs
  Files/UserControls/MultitaskingControl/IMultitaskingControl.cs
  Files/UserControls/MultitaskingControl/TabItem/ITabItem.cs
  Files/UserControls/MultitaskingControl/TabItem/ITabItemControl.cs
  Files/UserControls/MultitaskingControl/TabItem/TabItem.cs
  Files/Views/MainPage.xaml.cs
  Files/Views/ModernShellPage.xaml
  Files/Views/ModernShellPage.xaml.cs
Labels: approved

#2493 📓 Updated HUN
  Files/MultilingualResources/Files.hu-HU.xlf
Labels: needs-review

#2487 Fixed an issue where opening files wouldn't work when the directory was sorted by size or by file type
  Files/Interacts/Interaction.cs
Labels: needs-review

#2484 Fixed an issue where the text in the properties dialog would get cut off in some languages
  Files/MultilingualResources/Files.de-DE.xlf
  Files/MultilingualResources/Files.es-ES.xlf
  Files/MultilingualResources/Files.fr-FR.xlf
  Files/MultilingualResources/Files.he-IL.xlf
  Files/MultilingualResources/Files.hi-IN.xlf
  Files/MultilingualResources/Files.hu-HU.xlf
  Files/MultilingualResources/Files.it-IT.xlf
  Files/MultilingualResources/Files.ja-JP.xlf
  Files/MultilingualResources/Files.nl-NL.xlf
  Files/MultilingualResources/Files.or-IN.xlf
  Files/MultilingualResources/Files.pl-PL.xlf
  Files/MultilingualResources/Files.pt-BR.xlf
  Files/MultilingualResources/Files.ru-RU.xlf
  Files/MultilingualResources/Files.ta.xlf
  Files/MultilingualResources/Files.tr-TR.xlf
  Files/MultilingualResources/Files.uk-UA.xlf
  Files/MultilingualResources/Files.zh-Hans.xlf
  Files/MultilingualResources/Files.zh-Hant.xlf
  Files/Strings/de-DE/Resources.resw
  Files/Strings/en-US/Resources.resw
  Files/Strings/es-ES/Resources.resw
  Files/Strings/fr-FR/Resources.resw
  Files/Strings/he-IL/Resources.resw
  Files/Strings/hi-IN/Resources.resw
  Files/Strings/hu-HU/Resources.resw
  Files/Strings/it-IT/Resources.resw
  Files/Strings/ja-JP/Resources.resw
  Files/Strings/nl-NL/Resources.resw
  Files/Strings/or-IN/Resources.resw
  Files/Strings/pl-PL/Resources.resw
  Files/Strings/pt-BR/Resources.resw
  Files/Strings/ru-RU/Resources.resw
  Files/Strings/ta/Resources.resw
  Files/Strings/tr-TR/Resources.resw
  Files/Strings/uk-UA/Resources.resw
  Files/Strings/zh-Hans/Resources.resw
  Files/Strings/zh-Hant/Resources.resw
  Files/Views/Pages/PropertiesGeneral.xaml
Labels: approved

#2497 Reduce unnecessary work during extended property initialization and use new item icon in GridView
  Files/Views/LayoutModes/GenericFileBrowser.xaml
  Files/Views/LayoutModes/GenericFileBrowser.xaml.cs
  Files/Views/LayoutModes/GridViewBrowser.xaml
  Files/Views/LayoutModes/GridViewBrowser.xaml.cs
Labels: approved
