Repository files-community/Files, pull requests merged in 2020-04, with the labels that each got.

#607 Fix new folder/file creation looses focus with each letter
  Files/BaseLayout.cs
  Files/UserControls/LayoutModes/GenericFileBrowser.xaml.cs
  Files/UserControls/LayoutModes/PhotoAlbum.xaml.cs
Labels: needs-review

#610 Fix Download folder location
  Files/View Models/SettingsViewModel.cs
Labels: needs-review

#608 Don't create folder or file if dialog was canceled
  Files/Dialogs/AddItemDialog.xaml.cs
  Files/Dialogs/RenameDialog.xaml
  Files/Dialogs/RenameDialog.xaml.cs
Labels: needs-review

#604 Add Invert Selection, icons to status bar, fix folder navigation and remove space before .dll
  Files/BaseLayout.cs
  Files/Helpers/NaturalStringComparer.cs
  Files/Interacts/Interaction.cs
  Files/MultilingualResources/Files.de-DE.xlf
  Files/MultilingualResources/Files.es-ES.xlf
  Files/MultilingualResources/Files.fr-FR.xlf
  Files/MultilingualResources/Files.nl-NL.xlf
  Files/MultilingualResources/Files.pl-PL.xlf
  Files/MultilingualResources/Files.ru-RU.xlf
  Files/MultilingualResources/Files.tr-TR.xlf
  Files/MultilingualResources/Files.uk-UA.xlf
  Files/MultilingualResources/Files.zh-Hans.xlf
  Files/Strings/en-US/Resources.resw
  Files/UserControls/LayoutModes/GenericFileBrowser.xaml.cs
  Files/UserControls/LayoutModes/PhotoAlbum.xaml.cs
  Files/UserControls/StatusBarControl.xaml
Labels: needs-review

#612 v0.7.6 with fixes
  Files/BaseLayout.cs
  Files/Dialogs/AddItemDialog.xaml.cs
  Files/Dialogs/RenameDialog.xaml
  Files/Dialogs/RenameDialog.xaml.cs
  Files/Helpers/NaturalStringComparer.cs
  Files/Interacts/Interaction.cs
  Files/MultilingualResources/Files.de-DE.xlf
  Files/MultilingualResources/Files.es-ES.xlf
  Files/MultilingualResources/Files.fr-FR.xlf
  Files/MultilingualResources/Files.nl-NL.xlf
  Files/MultilingualResources/Files.pl-PL.xlf
  Files/MultilingualResources/Files.ru-RU.xlf
  Files/MultilingualResources/Files.tr-TR.xlf
  Files/MultilingualResources/Files.uk-UA.xlf
  Files/MultilingualResources/Files.zh-Hans.xlf
  Files/Strings/en-US/Resources.resw
  Files/UserControls/LayoutModes/GenericFileBrowser.xaml.cs
  Files/UserControls/LayoutModes/PhotoAlbum.xaml.cs
  Files/UserControls/StatusBarControl.xaml
  Files/View Models/ItemViewModel.cs
  Files/View Models/SelectedItemPropertiesViewModel.cs
  Files/View Models/SettingsViewModel.cs
  Files/Views/InstanceTabsView.xaml
  Files/Views/InstanceTabsView.xaml.cs
Labels: needs-review

#613 new string translated into spanish
  Files/MultilingualResources/Files.es-ES.xlf
Labels: approved

#621 Translation update [Spanish]
  Files/MultilingualResources/Files.es-ES.xlf
Labels: approved

#609 Redesign Properties window [2]
  Files/Interacts/Interaction.cs
  Files/MultilingualResources/Files.de-DE.xlf
  Files/MultilingualResources/Files.es-ES.xlf
  Files/MultilingualResources/Files.fr-FR.xlf
  Files/MultilingualResources/Files.nl-NL.xlf
  Files/MultilingualResources/Files.pl-PL.xlf
  Files/MultilingualResources/Files.ru-RU.xlf
  Files/MultilingualResources/Files.tr-TR.xlf
  Files/MultilingualResources/Files.uk-UA.xlf
  Files/MultilingualResources/Files.zh-Hans.xlf
  Files/Properties.xaml
  Files/Properties.xaml.cs
  Files/ResourceDictionaries/ToolbarButtonStyle.xaml
  Files/Strings/en-US/Resources.resw
  Files/Strings/ru-RU/Resources.resw
  Files/Strings/uk-UA/Resources.resw
  Files/UserControls/NavigationToolbar/ModernNavigationToolbar.xaml
Labels: approved

#622 New strings translated [Spanish]
  Files/MultilingualResources/Files.es-ES.xlf
Labels: approved, needs-review

#603 Moved image to top
  README.md
Labels: needs-review

#623 Properties dialog
  Files/Files.csproj
  Files/MultilingualResources/Files.it-IT.xlf
  Files/Strings/es-ES/Resources.resw
  Files/Strings/it-IT/Resources.resw
  Files/Views/Pages/Properties.xaml
  Files/Views/Pages/Properties.xaml.cs
Labels: needs-review

#624 Experimental settings
  Files/Files.csproj
  Files/MultilingualResources/Files.de-DE.xlf
  Files/MultilingualResources/Files.es-ES.xlf
  Files/MultilingualResources/Files.fr-FR.xlf
  Files/MultilingualResources/Files.it-IT.xlf
  Files/MultilingualResources/Files.nl-NL.xlf
  Files/MultilingualResources/Files.pl-PL.xlf
  Files/MultilingualResources/Files.ru-RU.xlf
  Files/MultilingualResources/Files.tr-TR.xlf
  Files/MultilingualResources/Files.uk-UA.xlf
  Files/MultilingualResources/Files.zh-Hans.xlf
  Files/Strings/de-DE/Resources.resw
  Files/Strings/en-US/Resources.resw
  Files/Strings/it-IT/Resources.resw
  Files/Strings/nl-NL/Resources.resw
  Files/Strings/pl-PL/Resources.resw
  Files/Strings/tr-TR/Resources.resw
  Files/Strings/zh-Hans/Resources.resw
  Files/UserControls/LayoutModes/GenericFileBrowser.xaml.cs
  Files/View Models/SettingsViewModel.cs
  Files/Views/Pages/Settings.xaml
  Files/Views/Pages/Settings.xaml.cs
  Files/Views/SettingsPages/Experimental.xaml
  Files/Views/SettingsPages/Experimental.xaml.cs
  Files/Views/SettingsPages/Flags.xaml
Labels: needs-review

#625 Added option to open sidebar items in a new tab or window
  Files/Interacts/Interaction.cs
  Files/MultilingualResources/Files.de-DE.xlf
  Files/MultilingualResources/Files.es-ES.xlf
  Files/MultilingualResources/Files.fr-FR.xlf
  Files/MultilingualResources/Files.it-IT.xlf
  Files/MultilingualResources/Files.nl-NL.xlf
  Files/MultilingualResources/Files.pl-PL.xlf
  Files/MultilingualResources/Files.ru-RU.xlf
  Files/MultilingualResources/Files.tr-TR.xlf
  Files/MultilingualResources/Files.uk-UA.xlf
  Files/MultilingualResources/Files.zh-Hans.xlf
  Files/Strings/en-US/Resources.resw
  Files/UserControls/ModernSidebar.xaml
  Files/UserControls/ModernSidebar.xaml.cs
Labels: needs-review

#629 Translation Update [Spanish]
  Files/MultilingualResources/Files.es-ES.xlf
Labels: approved

#631 Fixed issue with detecting mouse button clicks
  Files/App.xaml.cs
Labels: needs-review

#649 Improved pipeline
  Files.Package/Package.appxmanifest
  azure-pipelines-build-test.yml
  azure-pipelines.yml
Labels: needs-review

#658 Upgrade to latest WinUI preview
  Files/Files.csproj
  Files/UserControls/ModernSidebar.xaml
Labels: needs-review

#640 Tabs now display the correct string for new tabs
  Files/Strings/en-US/Resources.resw
  Files/Views/InstanceTabsView.xaml.cs
Labels: needs-review

#653 Fixed text getting cut off on settings pages
  Files/Views/SettingsPages/FilesAndFolders.xaml
  Files/Views/SettingsPages/Preferences.xaml
Labels: needs-review

#654 Added analytics to track settings
  Files/View Models/SettingsViewModel.cs
Labels: approved

#656 Added link to sample profiles
  Files/MultilingualResources/Files.de-DE.xlf
  Files/MultilingualResources/Files.es-ES.xlf
  Files/MultilingualResources/Files.fr-FR.xlf
  Files/MultilingualResources/Files.it-IT.xlf
  Files/MultilingualResources/Files.nl-NL.xlf
  Files/MultilingualResources/Files.pl-PL.xlf
  Files/MultilingualResources/Files.ru-RU.xlf
  Files/MultilingualResources/Files.tr-TR.xlf
  Files/MultilingualResources/Files.uk-UA.xlf
  Files/MultilingualResources/Files.zh-Hans.xlf
  Files/Strings/en-US/Resources.resw
  Files/Views/SettingsPages/Preferences.xaml
Labels: approved

#662 Disabled loading url files
  Files/View Models/ItemViewModel.cs
Labels: approved

#648 Properties window close button
  Files/Views/Pages/Properties.xaml
Labels: approved

#665 v0.7.8
  Files.Package/Package.appxmanifest
Labels: needs-review

#677 Apply theme and acrylic changes without restart
  Files/App.xaml
  Files/App.xaml.cs
  Files/Dialogs/ConfirmDeleteDialog.xaml
  Files/Dialogs/ConsentDialog.xaml
  Files/Dialogs/ExceptionDialog.xaml
  Files/Dialogs/ExtractFilesDialog.xaml
  Files/Dialogs/PropertiesDialog.xaml
  Files/Dialogs/RenameDialog.xaml
  Files/Enums/ThemeStyle.cs
  Files/Files.csproj
  Files/Helpers/AppTheme.cs
  Files/Helpers/NegateConverter.cs
  Files/Helpers/ThemeHelper.cs
  Files/Interacts/Interaction.cs
  Files/MultilingualResources/Files.es-ES.xlf
  Files/Strings/en-US/Resources.resw
  Files/UserControls/LayoutModes/GenericFileBrowser.xaml
  Files/UserControls/LayoutModes/GenericFileBrowser.xaml.cs
  Files/UserControls/LayoutModes/PhotoAlbum.xaml
  Files/UserControls/ModernSidebar.xaml
  Files/UserControls/ModernSidebar.xaml.cs
  Files/View Models/SettingsViewModel.cs
  Files/Views/InstanceTabsView.xaml
  Files/Views/InstanceTabsView.xaml.cs
  Files/Views/Pages/ModernShellPage.xaml
  Files/Views/Pages/ModernShellPage.xaml.cs
  Files/Views/Pages/Properties.xaml
  Files/Views/Pages/Properties.xaml.cs
  Files/Views/SettingsPages/Appearance.xaml
  Files/Views/SettingsPages/Appearance.xaml.cs
  Files/Views/SettingsPages/Experimental.xaml
  Files/Views/SettingsPages/Experimental.xaml.cs
Labels: needs-review

#690 Fixes + checks (when launching from command line)
  Files.Launcher/Program.cs
  Files/App.xaml.cs
  Files/CommandLine/CommandLineParser.cs
  Files/CommandLine/ParsedCommandType.cs
  Files/Filesystem/DriveItem.cs
  Files/Filesystem/Drives.cs
  Files/Interacts/Interaction.cs
  Files/Views/InstanceTabsView.xaml.cs
Labels: needs-review

#687 Improvements on German Translation
  Files/MultilingualResources/Files.de-DE.xlf
  Files/Strings/de-DE/Resources.resw
Labels: approved, needs-review

#705 Added in the most active contributors
  Files/Views/SettingsPages/About.xaml
Labels: needs-review

#703 Update Files.it-IT.xlf
  Files/MultilingualResources/Files.it-IT.xlf
Labels: approved

#706 Fix properties window crash
  Files/Interacts/Interaction.cs
  Files/Views/Pages/Properties.xaml
  Files/Views/Pages/Properties.xaml.cs
Labels: approved

#681 Fixed status bar visibility on home page
  Files/Interacts/Interaction.cs
  Files/MultilingualResources/Files.de-DE.xlf
  Files/MultilingualResources/Files.es-ES.xlf
  Files/MultilingualResources/Files.fr-FR.xlf
  Files/MultilingualResources/Files.it-IT.xlf
  Files/MultilingualResources/Files.nl-NL.xlf
  Files/MultilingualResources/Files.pl-PL.xlf
  Files/MultilingualResources/Files.ru-RU.xlf
  Files/MultilingualResources/Files.tr-TR.xlf
  Files/MultilingualResources/Files.uk-UA.xlf
  Files/MultilingualResources/Files.zh-Hans.xlf
  Files/Strings/en-US/Resources.resw
  Files/Views/InstanceTabsView.xaml.cs
Labels: approved

#707 Fix theme when opening folder in new window
  Files/App.xaml.cs
Labels: approved

#620 Fix folder copying to sibling folder with almost the same name
  Files/Files.csproj
  Files/Helpers/StringExtensions.cs
  Files/Interacts/Interaction.cs
Labels: needs-review

#709 Translation update [Spanish]
  Files/MultilingualResources/Files.es-ES.xlf
  Files/Strings/es-ES/Resources.resw
Labels: approved

#708 Fix file size calculation
  Files/View Models/ItemViewModel.cs
Labels: approved

#714 v0.7.9
  Files.Package/Package.appxmanifest
  Files/MultilingualResources/Files.it-IT.xlf
  Files/Strings/es-ES/Resources.resw
  Files/Strings/it-IT/Resources.resw
Labels: needs-review
