Repository files-community/Files, pull requests merged in 2020-05, with the labels that each got.

#731 Display already loaded entries while loading files in a directory
  Files/Files.csproj
  Files/Helpers/DispatcherHelper.cs
  Files/View Models/ItemViewModel.cs
  Files/View Models/SettingsViewModel.cs
Labels: approved

#728 Fixed app crash
  Files/Files.csproj
  Files/Helpers/AcrylicTheme.cs
  Files/Helpers/ThemeHelper.cs
  Files/UserControls/ModernSidebar.xaml
  Files/View Models/SettingsViewModel.cs
  Files/Views/InstanceTabsView.xaml
  Files/Views/Pages/Properties.xaml
Labels: needs-review

#742 v0.8.0
  Files.Package/Package.appxmanifest
  Files/Files.csproj
  Files/Helpers/AcrylicTheme.cs
  Files/Helpers/DispatcherHelper.cs
  Files/Helpers/ThemeHelper.cs
  Files/UserControls/ModernSidebar.xaml
  Files/View Models/ItemViewModel.cs
  Files/View Models/SettingsViewModel.cs
  Files/Views/InstanceTabsView.xaml
  Files/Views/Pages/Properties.xaml
  builds/azure-pipelines-build-test.yml
  builds/azure-pipelines-non-store.yml
  builds/azure-pipelines.yml
Labels: approved

#701 Fix drives loading
  Files/Filesystem/Drives.cs
  Files/MultilingualResources/Files.es-ES.xlf
Labels: approved

#746 Parse command line before App launch
  Files/App.xaml.cs
  Files/Files.csproj
  Files/Program.cs
Labels: approved

#755 Add option to set an image as lockscreen background
  Files/Interacts/Interaction.cs
  Files/Strings/en-US/Resources.resw
  Files/UserControls/LayoutModes/GenericFileBrowser.xaml
  Files/UserControls/LayoutModes/PhotoAlbum.xaml
Labels: approved

#761 Fix context menu appearing when right clicking on empty space in List…
  Files/UserControls/LayoutModes/GenericFileBrowser.xaml
Labels: approved

#770 Add support for uppercase image extension
  Files/BaseLayout.cs
  Files/View Models/InteractionViewModel.cs
Labels: approved

#769 Update translation
  Files/MultilingualResources/Files.de-DE.xlf
  Files/MultilingualResources/Files.es-ES.xlf
  Files/MultilingualResources/Files.fr-FR.xlf
  Files/MultilingualResources/Files.it-IT.xlf
  Files/MultilingualResources/Files.nl-NL.xlf
  Files/MultilingualResources/Files.pl-PL.xlf
  Files/MultilingualResources/Files.ru-RU.xlf
  Files/MultilingualResources/Files.tr-TR.xlf
  Files/MultilingualResources/Files.uk-UA.xlf
  Files/MultilingualResources/Files.zh-Hans.xlf
  Files/Strings/en-US/Resources.resw
  Files/Strings/ru-RU/Resources.resw
  Files/Strings/uk-UA/Resources.resw
Labels: approved

#778 Fix null detection of file extension
  Files/View Models/InteractionViewModel.cs
Labels: approved

#780 Fixed file rename with space added opening QuickLook
  Files/Interacts/Interaction.cs
Labels: approved

#781 Translation Update [Spanish]
  Files/MultilingualResources/Files.es-ES.xlf
  Files/Strings/es-ES/Resources.resw
Labels: approved

#771 Upgrade WinUI to v2.4 and prepare for release candidate
  Files/App.xaml
  Files/Files.csproj
  Files/UserControls/ModernSidebar.xaml
  Files/View Models/ItemViewModel.cs
  Files/Views/InstanceTabsView.xaml
  Files/Views/Pages/ModernShellPage.xaml
  Files/Views/Pages/Settings.xaml
  Files/Views/Pages/Settings.xaml.cs
  Files/Views/SettingsPages/Experimental.xaml
Labels: approved

#717 Locked the search button since it is not yet implemented
  Files/UserControls/NavigationToolbar/ModernNavigationToolbar.xaml
Labels: approved

#787 Fixed grid view selection bugs
  Files/UserControls/LayoutModes/PhotoAlbum.xaml.cs
Labels: approved

#784 Increased version number to v0.8.1
  Files.Package/Package.appxmanifest
Labels: approved

#788 Added support for ctrl + click deselection in grid view.
  Files/UserControls/LayoutModes/PhotoAlbum.xaml
  Files/UserControls/LayoutModes/PhotoAlbum.xaml.cs
Labels: approved

#789 v0.8.1
  Files.Package/Package.appxmanifest
  Files/App.xaml
  Files/App.xaml.cs
  Files/BaseLayout.cs
  Files/Files.csproj
  Files/Filesystem/Drives.cs
  Files/Interacts/Interaction.cs
  Files/MultilingualResources/Files.de-DE.xlf
  Files/MultilingualResources/Files.es-ES.xlf
  Files/MultilingualResources/Files.fr-FR.xlf
  Files/MultilingualResources/Files.it-IT.xlf
  Files/MultilingualResources/Files.nl-NL.xlf
  Files/MultilingualResources/Files.pl-PL.xlf
  Files/MultilingualResources/Files.ru-RU.xlf
  Files/MultilingualResources/Files.tr-TR.xlf
  Files/MultilingualResources/Files.uk-UA.xlf
  Files/MultilingualResources/Files.zh-Hans.xlf
  Files/Program.cs
  Files/Strings/en-US/Resources.resw
  Files/Strings/es-ES/Resources.resw
  Files/Strings/ru-RU/Resources.resw
  Files/Strings/uk-UA/Resources.resw
  Files/UserControls/LayoutModes/GenericFileBrowser.xaml
  Files/UserControls/LayoutModes/PhotoAlbum.xaml
  Files/UserControls/LayoutModes/PhotoAlbum.xaml.cs
  Files/UserControls/ModernSidebar.xaml
  Files/UserControls/NavigationToolbar/ModernNavigationToolbar.xaml
  Files/View Models/InteractionViewModel.cs
  Files/View Models/ItemViewModel.cs
  Files/Views/InstanceTabsView.xaml
  Files/Views/Pages/ModernShellPage.xaml
  Files/Views/Pages/Settings.xaml
  Files/Views/Pages/Settings.xaml.cs
  Files/Views/SettingsPages/Experimental.xaml
  builds/azure-pipelines.yml
Labels: approved

#790 Fix blurry thumbnails for some items in grid view
  Files/UserControls/LayoutModes/GenericFileBrowser.xaml.cs
Labels: approved

#791 Switch ThumbnailMode to SingleItem for better thumbnails
  Files/View Models/ItemViewModel.cs
Labels: approved

#802 Fixed crash when using keyboard shortcuts the home page
  Files/Views/Pages/ModernShellPage.xaml.cs
Labels: approved, needs-review

#804 Optimized home page identifying
  Files/BaseLayout.cs
  Files/UserControls/ModernSidebar.xaml.cs
  Files/UserControls/YourHome.xaml.cs
  Files/Views/Pages/ModernShellPage.xaml.cs
Labels: approved

#806 Fix App Startup Crash By Deferring Adding Drives to UI
  Files/Filesystem/Drives.cs
Labels: approved

#813 Fix blurred disk drive icons
  Files/App.xaml.cs
  Files/Filesystem/DriveItem.cs
  Files/Filesystem/Drives.cs
  Files/Filesystem/INavigationControlItem.cs
  Files/Filesystem/LocationItem.cs
  Files/UserControls/ModernSidebar.xaml
  Files/View Models/SettingsViewModel.cs
Labels: approved

#816 Fixed OneDrive selection
  Files/Filesystem/DriveItem.cs
  Files/Filesystem/Drives.cs
  Files/UserControls/ModernSidebar.xaml
  Files/UserControls/ModernSidebar.xaml.cs
  Files/UserControls/YourHome.xaml.cs
  Files/View Models/ItemViewModel.cs
  Files/View Models/SettingsViewModel.cs
  Files/Views/Pages/ModernShellPage.xaml.cs
Labels: approved

#815 Update azure-pipelines-build-test.yml
  builds/azure-pipelines-build-test.yml
Labels: needs-review

#818 Fixed SideBar background flash when opening new tab page
  Files/UserControls/ModernSidebar.xaml
  Files/Views/Pages/ModernShellPage.xaml
Labels: approved

#824 Fix tab background color in dark mode when pointer over
  Files/App.xaml
Labels: approved

#812 Icon/Filesystem Fixes
  Files/View Models/ItemViewModel.cs
Labels: approved

#831 Fix files last modified date
  Files/View Models/ItemViewModel.cs
Labels: approved

#822 Add support for Tablet Mode's back button
  Files/App.xaml.cs
  Files/MultilingualResources/Files.ru-RU.xlf
  Files/MultilingualResources/Files.uk-UA.xlf
Labels: approved

#827 Added/improved layout modes
  Files/Assets/FolderIconLarge.svg
  Files/BaseLayout.cs
  Files/Files.csproj
  Files/Interacts/Interaction.cs
  Files/Strings/en-US/Resources.resw
  Files/UserControls/LayoutModes/GenericFileBrowser.xaml
  Files/UserControls/LayoutModes/GridViewBrowser.xaml
  Files/UserControls/LayoutModes/GridViewBrowser.xaml.cs
  Files/UserControls/ModernSidebar.xaml.cs
  Files/UserControls/NavigationToolbar/ModernNavigationToolbar.xaml.cs
  Files/UserControls/StatusBarControl.xaml
  Files/UserControls/YourHome.xaml.cs
  Files/View Models/ItemViewModel.cs
  Files/View Models/SettingsViewModel.cs
  Files/Views/Pages/ModernShellPage.xaml.cs
Labels: needs-review

#797 Optimization
  Files/App.xaml
  Files/BaseLayout.cs
  Files/Converters/StorageDeleteOptionToBooleanConverter.cs
  Files/Dialogs/ConfirmDeleteDialog.xaml
  Files/Files.csproj
  Files/Helpers/NegateConverter.cs
  Files/Interacts/Interaction.cs
  Files/MultilingualResources/Files.ru-RU.xlf
  Files/MultilingualResources/Files.uk-UA.xlf
  Files/UserControls/LayoutModes/GenericFileBrowser.xaml
  Files/UserControls/LayoutModes/GenericFileBrowser.xaml.cs
  Files/UserControls/LayoutModes/GridViewBrowser.xaml
  Files/UserControls/LayoutModes/GridViewBrowser.xaml.cs
  Files/UserControls/ModernSidebar.xaml.cs
  Files/UserControls/NavigationToolbar/ModernNavigationToolbar.xaml.cs
  Files/UserControls/YourHome.xaml.cs
  Files/View Models/InteractionViewModel.cs
  Files/View Models/ItemViewModel.cs
  Files/View Models/SelectedItemPropertiesViewModel.cs
  Files/View Models/SettingsViewModel.cs
  Files/Views/Pages/ModernShellPage.xaml.cs
  Files/Views/SettingsPages/Appearance.xaml
Labels: approved

#833 Fixed grid view height for tall icons
  Files/UserControls/LayoutModes/GridViewBrowser.xaml
Labels: approved

#832 v0.9.0.0
  Files.Package/Package.appxmanifest
Labels: approved

#837 Strings added + Translation [Spanish]
  Files/MultilingualResources/Files.de-DE.xlf
  Files/MultilingualResources/Files.es-ES.xlf
  Files/MultilingualResources/Files.fr-FR.xlf
  Files/MultilingualResources/Files.it-IT.xlf
  Files/MultilingualResources/Files.nl-NL.xlf
  Files/MultilingualResources/Files.pl-PL.xlf
  Files/MultilingualResources/Files.ru-RU.xlf
  Files/MultilingualResources/Files.tr-TR.xlf
  Files/MultilingualResources/Files.uk-UA.xlf
  Files/MultilingualResources/Files.zh-Hans.xlf
  Files/Strings/de-DE/Resources.resw
  Files/Strings/es-ES/Resources.resw
  Files/Strings/it-IT/Resources.resw
  Files/Strings/pl-PL/Resources.resw
  Files/Strings/ru-RU/Resources.resw
  Files/Strings/tr-TR/Resources.resw
  Files/Strings/uk-UA/Resources.resw
  Files/Strings/zh-Hans/Resources.resw
Labels: approved

#838 Massive Cleanup of YourHome Markup
  Files/Files.csproj
  Files/Helpers/DialogDisplayHelper.cs
  Files/Interacts/Interaction.cs
  Files/LocationsList.cs
  Files/MultilingualResources/Files.de-DE.xlf
  Files/MultilingualResources/Files.es-ES.xlf
  Files/MultilingualResources/Files.fr-FR.xlf
  Files/MultilingualResources/Files.it-IT.xlf
  Files/MultilingualResources/Files.nl-NL.xlf
  Files/MultilingualResources/Files.pl-PL.xlf
  Files/MultilingualResources/Files.ru-RU.xlf
  Files/MultilingualResources/Files.tr-TR.xlf
  Files/MultilingualResources/Files.uk-UA.xlf
  Files/MultilingualResources/Files.zh-Hans.xlf
  Files/Strings/en-US/Resources.resw
  Files/UserControls/YourHome.xaml
  Files/UserControls/YourHome.xaml.cs
  Files/View Models/ItemViewModel.cs
Labels: approved

#839 String added for "OK" Button + Translation [Spanish]
  Files/MultilingualResources/Files.de-DE.xlf
  Files/MultilingualResources/Files.es-ES.xlf
  Files/MultilingualResources/Files.fr-FR.xlf
  Files/MultilingualResources/Files.it-IT.xlf
  Files/MultilingualResources/Files.nl-NL.xlf
  Files/MultilingualResources/Files.pl-PL.xlf
  Files/MultilingualResources/Files.ru-RU.xlf
  Files/MultilingualResources/Files.tr-TR.xlf
  Files/MultilingualResources/Files.uk-UA.xlf
  Files/MultilingualResources/Files.zh-Hans.xlf
  Files/Strings/en-US/Resources.resw
  Files/Strings/es-ES/Resources.resw
  Files/Views/Pages/Properties.xaml
Labels: approved

#849 Add Tamil translation
  Files/Files.csproj
  Files/MultilingualResources/Files.ta.xlf
  Files/Strings/ta/Resources.resw
Labels: approved

#851 Missing strings added to Files.ta
  Files/MultilingualResources/Files.ta.xlf
Labels: approved

#853 Resources.resw [ta] Updated
  Files/Strings/ta/Resources.resw
Labels: approved

#858 Update translation
  Files/MultilingualResources/Files.ru-RU.xlf
  Files/MultilingualResources/Files.uk-UA.xlf
Labels: approved

#856 Update Files.de-DE.xlf
  Files/MultilingualResources/Files.de-DE.xlf
Labels: approved

#861 Updated resources [de, uk, ru] + fix
  Files/MultilingualResources/Files.de-DE.xlf
  Files/Strings/de-DE/Resources.resw
  Files/Strings/ru-RU/Resources.resw
  Files/Strings/uk-UA/Resources.resw
Labels: approved

#863 Updates Files.it-IT.xlf
  Files/MultilingualResources/Files.it-IT.xlf
Labels: approved

#865 Fixed tag
  Files/MultilingualResources/Files.it-IT.xlf
  Files/Strings/it-IT/Resources.resw
Labels: approved

#866 Update Files.ta.xlf
  Files/MultilingualResources/Files.ta.xlf
Labels: approved

#869 Updated resources [ta]
  Files/Strings/ta/Resources.resw
Labels: approved

#859 Reduced nav bar text size
  Files/UserControls/NavigationToolbar/ModernNavigationToolbar.xaml
Labels: approved

#872 ToolTip added for selection and layout mode button
  Files/MultilingualResources/Files.de-DE.xlf
  Files/MultilingualResources/Files.es-ES.xlf
  Files/MultilingualResources/Files.fr-FR.xlf
  Files/MultilingualResources/Files.it-IT.xlf
  Files/MultilingualResources/Files.nl-NL.xlf
  Files/MultilingualResources/Files.pl-PL.xlf
  Files/MultilingualResources/Files.ru-RU.xlf
  Files/MultilingualResources/Files.ta.xlf
  Files/MultilingualResources/Files.tr-TR.xlf
  Files/MultilingualResources/Files.uk-UA.xlf
  Files/MultilingualResources/Files.zh-Hans.xlf
  Files/Strings/en-US/Resources.resw
  Files/Strings/es-ES/Resources.resw
  Files/UserControls/StatusBarControl.xaml
Labels: approved

#860 Fix incorrect path while upward to root disk
  Files/Views/InstanceTabsView.xaml.cs
Labels: approved

#879 Properties dialog: Added strings and some changes
  Files/MultilingualResources/Files.de-DE.xlf
  Files/MultilingualResources/Files.es-ES.xlf
  Files/MultilingualResources/Files.fr-FR.xlf
  Files/MultilingualResources/Files.it-IT.xlf
  Files/MultilingualResources/Files.nl-NL.xlf
  Files/MultilingualResources/Files.pl-PL.xlf
  Files/MultilingualResources/Files.ru-RU.xlf
  Files/MultilingualResources/Files.ta.xlf
  Files/MultilingualResources/Files.tr-TR.xlf
  Files/MultilingualResources/Files.uk-UA.xlf
  Files/MultilingualResources/Files.zh-Hans.xlf
  Files/Strings/en-US/Resources.resw
  Files/Strings/es-ES/Resources.resw
  Files/Views/Pages/Properties.xaml
Labels: approved

#862 Alert the user when trying to delete a file which is in use
  Files/Interacts/Interaction.cs
  Files/MultilingualResources/Files.de-DE.xlf
  Files/MultilingualResources/Files.es-ES.xlf
  Files/MultilingualResources/Files.fr-FR.xlf
  Files/MultilingualResources/Files.it-IT.xlf
  Files/MultilingualResources/Files.nl-NL.xlf
  Files/MultilingualResources/Files.pl-PL.xlf
  Files/MultilingualResources/Files.ru-RU.xlf
  Files/MultilingualResources/Files.ta.xlf
  Files/MultilingualResources/Files.tr-TR.xlf
  Files/MultilingualResources/Files.uk-UA.xlf
  Files/MultilingualResources/Files.zh-Hans.xlf
  Files/Strings/en-US/Resources.resw
Labels: approved

#883 Translation update [Spanish]
  Files/MultilingualResources/Files.es-ES.xlf
  Files/MultilingualResources/Files.it-IT.xlf
  Files/MultilingualResources/Files.tr-TR.xlf
  Files/MultilingualResources/Files.zh-Hans.xlf
  Files/Strings/es-ES/Resources.resw
Labels: approved
