Repository files-community/Files, pull requests merged in 2020-09, with the labels that each got.

#1850 Fixed an issue where opening the properties window would sometimes crash the app on 1903/1909
  Files/Views/Pages/Properties.xaml.cs
Labels: approved

#1853 Updateed README.md with some info about Files UWP
  README.md
Labels: approved

#1851 Reordered buttons on the properties dialog
  Files/Views/Pages/Properties.xaml
Labels: approved

#1852 Updated strings
  Files/MultilingualResources/Files.de-DE.xlf
  Files/MultilingualResources/Files.es-ES.xlf
  Files/MultilingualResources/Files.fr-FR.xlf
  Files/MultilingualResources/Files.he-IL.xlf
  Files/MultilingualResources/Files.hi-IN.xlf
  Files/MultilingualResources/Files.it-IT.xlf
  Files/MultilingualResources/Files.ja-JP.xlf
  Files/MultilingualResources/Files.nl-NL.xlf
  Files/MultilingualResources/Files.or-IN.xlf
  Files/MultilingualResources/Files.pl-PL.xlf
  Files/MultilingualResources/Files.pt-BR.xlf
  Files/MultilingualResources/Files.ru-RU.xlf
  Files/MultilingualResources/Files.ta.xlf
  Files/MultilingualResources/Files.tr-TR.xlf
  Files/MultilingualResources/Files.uk-UA.xlf
  Files/MultilingualResources/Files.zh-Hans.xlf
  Files/Strings/he-IL/Resources.resw
Labels: approved

#1866 Translation update [pt-BR]
  Files/MultilingualResources/Files.pt-BR.xlf
  Files/Strings/pt-BR/Resources.resw
Labels: approved

#1863 Updated the confirm delete dialog to include the number of selected items
  Files/BaseLayout.cs
  Files/Dialogs/ConfirmDeleteDialog.xaml
  Files/Dialogs/ConfirmDeleteDialog.xaml.cs
  Files/MultilingualResources/Files.de-DE.xlf
  Files/MultilingualResources/Files.es-ES.xlf
  Files/MultilingualResources/Files.fr-FR.xlf
  Files/MultilingualResources/Files.he-IL.xlf
  Files/MultilingualResources/Files.hi-IN.xlf
  Files/MultilingualResources/Files.it-IT.xlf
  Files/MultilingualResources/Files.ja-JP.xlf
  Files/MultilingualResources/Files.nl-NL.xlf
  Files/MultilingualResources/Files.or-IN.xlf
  Files/MultilingualResources/Files.pl-PL.xlf
  Files/MultilingualResources/Files.pt-BR.xlf
  Files/MultilingualResources/Files.ru-RU.xlf
  Files/MultilingualResources/Files.ta.xlf
  Files/MultilingualResources/Files.tr-TR.xlf
  Files/MultilingualResources/Files.uk-UA.xlf
  Files/MultilingualResources/Files.zh-Hans.xlf
  Files/Strings/de-DE/Resources.resw
  Files/Strings/en-US/Resources.resw
  Files/Strings/es-ES/Resources.resw
  Files/Strings/fr-FR/Resources.resw
  Files/Strings/he-IL/Resources.resw
  Files/Strings/hi-IN/Resources.resw
  Files/Strings/it-IT/Resources.resw
  Files/Strings/ja-JP/Resources.resw
  Files/Strings/nl-NL/Resources.resw
  Files/Strings/or-IN/Resources.resw
  Files/Strings/pl-PL/Resources.resw
  Files/Strings/pt-BR/Resources.resw
  Files/Strings/ru-RU/Resources.resw
  Files/Strings/ta/Resources.resw
  Files/Strings/tr-TR/Resources.resw
  Files/Strings/uk-UA/Resources.resw
  Files/Strings/zh-Hans/Resources.resw
  Files/UserControls/StatusBarControl.xaml
  Files/View Models/SelectedItemsPropertiesViewModel.cs
Labels: approved

#1867 0.14.0.0
  Files.Launcher/Properties/AssemblyInfo.cs
  Files.Package/Package.appxmanifest
  Files/View Models/SettingsViewModel.cs
  Files/Views/LayoutModes/GenericFileBrowser.xaml
  Files/Views/LayoutModes/GridViewBrowser.xaml
Labels: approved

#1868 Translation Update [es-ES]
  Files/MultilingualResources/Files.es-ES.xlf
  Files/Strings/es-ES/Resources.resw
Labels: approved

#1862 Properties: added string for "Cancel" button
  Files/MultilingualResources/Files.de-DE.xlf
  Files/MultilingualResources/Files.es-ES.xlf
  Files/MultilingualResources/Files.fr-FR.xlf
  Files/MultilingualResources/Files.he-IL.xlf
  Files/MultilingualResources/Files.hi-IN.xlf
  Files/MultilingualResources/Files.it-IT.xlf
  Files/MultilingualResources/Files.ja-JP.xlf
  Files/MultilingualResources/Files.nl-NL.xlf
  Files/MultilingualResources/Files.or-IN.xlf
  Files/MultilingualResources/Files.pl-PL.xlf
  Files/MultilingualResources/Files.pt-BR.xlf
  Files/MultilingualResources/Files.ru-RU.xlf
  Files/MultilingualResources/Files.ta.xlf
  Files/MultilingualResources/Files.tr-TR.xlf
  Files/MultilingualResources/Files.uk-UA.xlf
  Files/MultilingualResources/Files.zh-Hans.xlf
  Files/Strings/en-US/Resources.resw
  Files/Strings/es-ES/Resources.resw
Labels: approved

#1597 Tiles and List View: Gray text for file properties
  Files/Views/LayoutModes/GenericFileBrowser.xaml
  Files/Views/LayoutModes/GridViewBrowser.xaml
Labels: approved

#1877 Removed duplicate extract all menu item
  Files/BaseLayout.cs
  Files/Dialogs/ExtractFilesDialog.xaml
  Files/Dialogs/ExtractFilesDialog.xaml.cs
  Files/Files.csproj
  Files/Interacts/Interaction.cs
  Files/MultilingualResources/Files.de-DE.xlf
  Files/MultilingualResources/Files.es-ES.xlf
  Files/MultilingualResources/Files.fr-FR.xlf
  Files/MultilingualResources/Files.he-IL.xlf
  Files/MultilingualResources/Files.hi-IN.xlf
  Files/MultilingualResources/Files.it-IT.xlf
  Files/MultilingualResources/Files.ja-JP.xlf
  Files/MultilingualResources/Files.nl-NL.xlf
  Files/MultilingualResources/Files.or-IN.xlf
  Files/MultilingualResources/Files.pl-PL.xlf
  Files/MultilingualResources/Files.pt-BR.xlf
  Files/MultilingualResources/Files.ru-RU.xlf
  Files/MultilingualResources/Files.ta.xlf
  Files/MultilingualResources/Files.tr-TR.xlf
  Files/MultilingualResources/Files.uk-UA.xlf
  Files/MultilingualResources/Files.zh-Hans.xlf
  Files/Strings/de-DE/Resources.resw
  Files/Strings/en-US/Resources.resw
  Files/Strings/es-ES/Resources.resw
  Files/Strings/fr-FR/Resources.resw
  Files/Strings/he-IL/Resources.resw
  Files/Strings/hi-IN/Resources.resw
  Files/Strings/it-IT/Resources.resw
  Files/Strings/ja-JP/Resources.resw
  Files/Strings/nl-NL/Resources.resw
  Files/Strings/or-IN/Resources.resw
  Files/Strings/pl-PL/Resources.resw
  Files/Strings/pt-BR/Resources.resw
  Files/Strings/ru-RU/Resources.resw
  Files/Strings/ta/Resources.resw
  Files/Strings/tr-TR/Resources.resw
  Files/Strings/uk-UA/Resources.resw
  Files/Strings/zh-Hans/Resources.resw
  Files/Views/LayoutModes/GenericFileBrowser.xaml
  Files/Views/LayoutModes/GridViewBrowser.xaml
Labels: approved

#1854 Improve codebase quality in properties
  Files/Files.csproj
  Files/ResourceDictionaries/PropertiesStyles.xaml
  Files/UserControls/FileIcon.xaml
  Files/UserControls/FileIcon.xaml.cs
  Files/View Models/Properties/PropertiesTab.cs
  Files/Views/Pages/PropertiesGeneral.xaml
  Files/Views/Pages/PropertiesGeneral.xaml.cs
  Files/Views/Pages/PropertiesShortcut.xaml
  Files/Views/Pages/PropertiesShortcut.xaml.cs
Labels: approved

#1885 Update Resources.resw with improved labels for more intuitiveness
  Files/Strings/en-US/Resources.resw
Labels: approved

#1888 Update CODE_OF_CONDUCT.md with some minor changes
  CODE_OF_CONDUCT.md
Labels: approved

#1889 Added link to code of conduct in README.md
  README.md
Labels: approved

#1890 Moved set as lockscreen and set as background to a sub menu
  Files/MultilingualResources/Files.de-DE.xlf
  Files/MultilingualResources/Files.es-ES.xlf
  Files/MultilingualResources/Files.fr-FR.xlf
  Files/MultilingualResources/Files.he-IL.xlf
  Files/MultilingualResources/Files.hi-IN.xlf
  Files/MultilingualResources/Files.it-IT.xlf
  Files/MultilingualResources/Files.ja-JP.xlf
  Files/MultilingualResources/Files.nl-NL.xlf
  Files/MultilingualResources/Files.or-IN.xlf
  Files/MultilingualResources/Files.pl-PL.xlf
  Files/MultilingualResources/Files.pt-BR.xlf
  Files/MultilingualResources/Files.ru-RU.xlf
  Files/MultilingualResources/Files.ta.xlf
  Files/MultilingualResources/Files.tr-TR.xlf
  Files/MultilingualResources/Files.uk-UA.xlf
  Files/MultilingualResources/Files.zh-Hans.xlf
  Files/Strings/en-US/Resources.resw
  Files/Views/LayoutModes/GenericFileBrowser.xaml
  Files/Views/LayoutModes/GridViewBrowser.xaml
Labels: approved

#1896 Translation Update [es-ES]
  Files/MultilingualResources/Files.es-ES.xlf
  Files/Strings/es-ES/Resources.resw
Labels: approved

#1833 Added settings to choose multitasking preferences
  Files/App.xaml.cs
  Files/BaseLayout.cs
  Files/Converters/MultiBooleanConverter.cs
  Files/Dialogs/ExceptionDialog.xaml.cs
  Files/Files.csproj
  Files/IShellPage.cs
  Files/Interacts/Interaction.cs
  Files/MultilingualResources/Files.de-DE.xlf
  Files/MultilingualResources/Files.es-ES.xlf
  Files/MultilingualResources/Files.fr-FR.xlf
  Files/MultilingualResources/Files.he-IL.xlf
  Files/MultilingualResources/Files.hi-IN.xlf
  Files/MultilingualResources/Files.it-IT.xlf
  Files/MultilingualResources/Files.ja-JP.xlf
  Files/MultilingualResources/Files.nl-NL.xlf
  Files/MultilingualResources/Files.or-IN.xlf
  Files/MultilingualResources/Files.pl-PL.xlf
  Files/MultilingualResources/Files.pt-BR.xlf
  Files/MultilingualResources/Files.ru-RU.xlf
  Files/MultilingualResources/Files.ta.xlf
  Files/MultilingualResources/Files.tr-TR.xlf
  Files/MultilingualResources/Files.uk-UA.xlf
  Files/MultilingualResources/Files.zh-Hans.xlf
  Files/Strings/de-DE/Resources.resw
  Files/Strings/en-US/Resources.resw
  Files/Strings/es-ES/Resources.resw
  Files/Strings/it-IT/Resources.resw
  Files/Strings/nl-NL/Resources.resw
  Files/Strings/pt-BR/Resources.resw
  Files/Strings/ru-RU/Resources.resw
  Files/Strings/uk-UA/Resources.resw
  Files/UserControls/ModernNavigationToolbar.xaml
  Files/UserControls/ModernNavigationToolbar.xaml.cs
  Files/UserControls/MultitaskingControl/HorizontalMultitaskingControl.xaml
  Files/UserControls/MultitaskingControl/HorizontalMultitaskingControl.xaml.cs
  Files/UserControls/MultitaskingControl/VerticalTabViewControl.xaml
  Files/UserControls/MultitaskingControl/VerticalTabViewControl.xaml.cs
  Files/UserControls/SidebarControl.xaml
  Files/UserControls/YourHome.xaml.cs
  Files/View Models/InteractionViewModel.cs
  Files/View Models/SettingsViewModel.cs
  Files/Views/LayoutModes/GenericFileBrowser.xaml
  Files/Views/LayoutModes/GridViewBrowser.xaml
  Files/Views/MainPage.xaml
  Files/Views/MainPage.xaml.cs
  Files/Views/ModernShellPage.xaml
  Files/Views/ModernShellPage.xaml.cs
  Files/Views/Settings.xaml
  Files/Views/Settings.xaml.cs
  Files/Views/SettingsPages/Experimental.xaml
  Files/Views/SettingsPages/Multitasking.xaml
  Files/Views/SettingsPages/Multitasking.xaml.cs
Labels: approved

#1902 Update README.md
  README.md
Labels: approved

#1881 Fixed a crash that would sometimes occur when selecting some options on the right click context menu
  Files.Launcher/Program.cs
  Files.Launcher/Win32API_ContextMenu.cs
Labels: approved

#1915 Update Files.de-DE.xlf
  Files/MultilingualResources/Files.de-DE.xlf
Labels: approved

#1917 Fixed an issue where the file access consent dialog would sometimes show even after permission was already granted
  Files/Filesystem/Drives.cs
Labels: approved

#1918 Fixed a crash that would sometimes occur on startup
  Files/UserControls/SidebarControl.xaml.cs
  Files/Views/ModernShellPage.xaml.cs
Labels: approved

#1906 Added a copy location button to the right click context menu
  Files/BaseLayout.cs
  Files/Interacts/Interaction.cs
  Files/MultilingualResources/Files.de-DE.xlf
  Files/MultilingualResources/Files.es-ES.xlf
  Files/MultilingualResources/Files.fr-FR.xlf
  Files/MultilingualResources/Files.he-IL.xlf
  Files/MultilingualResources/Files.hi-IN.xlf
  Files/MultilingualResources/Files.it-IT.xlf
  Files/MultilingualResources/Files.ja-JP.xlf
  Files/MultilingualResources/Files.nl-NL.xlf
  Files/MultilingualResources/Files.or-IN.xlf
  Files/MultilingualResources/Files.pl-PL.xlf
  Files/MultilingualResources/Files.pt-BR.xlf
  Files/MultilingualResources/Files.ru-RU.xlf
  Files/MultilingualResources/Files.ta.xlf
  Files/MultilingualResources/Files.tr-TR.xlf
  Files/MultilingualResources/Files.uk-UA.xlf
  Files/MultilingualResources/Files.zh-Hans.xlf
  Files/Strings/en-US/Resources.resw
  Files/UserControls/ModernNavigationToolbar.xaml
  Files/View Models/SettingsViewModel.cs
  Files/Views/LayoutModes/GenericFileBrowser.xaml
  Files/Views/LayoutModes/GridViewBrowser.xaml
  Files/Views/SettingsPages/Preferences.xaml
Labels: approved

#1916 Open github new issue page from crash notification
  Files/App.xaml.cs
Labels: approved

#1921 Improved context menu load time
  Files.Launcher/Program.cs
Labels: approved

#1919 StatusCenter: Improve reliability of file operations, enable limited progress reporting, reorganize code
  Files/BaseLayout.cs
  Files/Commands/Delete.cs
  Files/Commands/Paste.cs
  Files/Files.csproj
  Files/Interacts/Interaction.cs
  Files/MultilingualResources/Files.de-DE.xlf
  Files/MultilingualResources/Files.es-ES.xlf
  Files/MultilingualResources/Files.fr-FR.xlf
  Files/MultilingualResources/Files.he-IL.xlf
  Files/MultilingualResources/Files.hi-IN.xlf
  Files/MultilingualResources/Files.it-IT.xlf
  Files/MultilingualResources/Files.ja-JP.xlf
  Files/MultilingualResources/Files.nl-NL.xlf
  Files/MultilingualResources/Files.or-IN.xlf
  Files/MultilingualResources/Files.pl-PL.xlf
  Files/MultilingualResources/Files.pt-BR.xlf
  Files/MultilingualResources/Files.ru-RU.xlf
  Files/MultilingualResources/Files.ta.xlf
  Files/MultilingualResources/Files.tr-TR.xlf
  Files/MultilingualResources/Files.uk-UA.xlf
  Files/MultilingualResources/Files.zh-Hans.xlf
  Files/Strings/de-DE/Resources.resw
  Files/UserControls/ModernNavigationToolbar.xaml.cs
  Files/UserControls/MultitaskingControl/HorizontalMultitaskingControl.xaml.cs
  Files/UserControls/MultitaskingControl/VerticalTabViewControl.xaml.cs
  Files/UserControls/SidebarControl.xaml.cs
  Files/UserControls/StatusBarControl.xaml
  Files/UserControls/StatusCenter.xaml
  Files/UserControls/StatusCenter.xaml.cs
  Files/View Models/ItemViewModel.cs
  Files/Views/ModernShellPage.xaml.cs
Labels: approved

#1926 Fixed an issue where navigating away from the home page sometimes wouldn't work
  Files/UserControls/YourHome.xaml.cs
  Files/View Models/ItemViewModel.cs
Labels: approved

#1927 Translation Update [es-ES]
  Files/MultilingualResources/Files.es-ES.xlf
  Files/Strings/es-ES/Resources.resw
  Files/Strings/pt-BR/Resources.resw
Labels: approved

#1901 Updated localization
  Files/MultilingualResources/Files.de-DE.xlf
  Files/MultilingualResources/Files.es-ES.xlf
  Files/MultilingualResources/Files.fr-FR.xlf
  Files/MultilingualResources/Files.he-IL.xlf
  Files/MultilingualResources/Files.hi-IN.xlf
  Files/MultilingualResources/Files.it-IT.xlf
  Files/MultilingualResources/Files.ja-JP.xlf
  Files/MultilingualResources/Files.nl-NL.xlf
  Files/MultilingualResources/Files.or-IN.xlf
  Files/MultilingualResources/Files.pl-PL.xlf
  Files/MultilingualResources/Files.pt-BR.xlf
  Files/MultilingualResources/Files.ru-RU.xlf
  Files/MultilingualResources/Files.ta.xlf
  Files/MultilingualResources/Files.tr-TR.xlf
  Files/MultilingualResources/Files.uk-UA.xlf
  Files/MultilingualResources/Files.zh-Hans.xlf
  Files/Strings/de-DE/Resources.resw
  Files/Strings/en-US/Resources.resw
  Files/UserControls/MultitaskingControl/VerticalTabViewControl.xaml
Labels: approved

#1933 Update German localization
  Files/MultilingualResources/Files.de-DE.xlf
Labels: approved

#1938 Update Files.fr-FR.xlf
  Files/MultilingualResources/Files.fr-FR.xlf
  Files/Strings/de-DE/Resources.resw
  Files/Strings/fr-FR/Resources.resw
Labels: approved

#1856 Show dialog to restart app after language changed
  Files/App.xaml.cs
  Files/Dialogs/RestartDialog.xaml
  Files/Dialogs/RestartDialog.xaml.cs
  Files/Files.csproj
  Files/Strings/en-US/Resources.resw
  Files/View Models/SettingsViewModel.cs
  Files/Views/MainPage.xaml.cs
  Files/Views/SettingsPages/Preferences.xaml
  Files/Views/SettingsPages/Preferences.xaml.cs
Labels: approved

#1941 Fix crash when dropping tab outside tabstrip
  Files/UserControls/MultitaskingControl/HorizontalMultitaskingControl.xaml.cs
Labels: approved

#1943 Hide windows explorer's paste command from context menu
  Files.Launcher/Program.cs
Labels: approved

#1953 Updated strings
  Files.Package/Package.appxmanifest
  Files/MultilingualResources/Files.de-DE.xlf
  Files/MultilingualResources/Files.es-ES.xlf
  Files/MultilingualResources/Files.fr-FR.xlf
  Files/MultilingualResources/Files.he-IL.xlf
  Files/MultilingualResources/Files.hi-IN.xlf
  Files/MultilingualResources/Files.it-IT.xlf
  Files/MultilingualResources/Files.ja-JP.xlf
  Files/MultilingualResources/Files.nl-NL.xlf
  Files/MultilingualResources/Files.or-IN.xlf
  Files/MultilingualResources/Files.pl-PL.xlf
  Files/MultilingualResources/Files.pt-BR.xlf
  Files/MultilingualResources/Files.ru-RU.xlf
  Files/MultilingualResources/Files.ta.xlf
  Files/MultilingualResources/Files.tr-TR.xlf
  Files/MultilingualResources/Files.uk-UA.xlf
  Files/MultilingualResources/Files.zh-Hans.xlf
  Files/Strings/de-DE/Resources.resw
  Files/Strings/es-ES/Resources.resw
  Files/Strings/fr-FR/Resources.resw
  Files/Strings/he-IL/Resources.resw
  Files/Strings/hi-IN/Resources.resw
  Files/Strings/it-IT/Resources.resw
  Files/Strings/nl-NL/Resources.resw
  Files/Strings/or-IN/Resources.resw
  Files/Strings/pl-PL/Resources.resw
  Files/Strings/pt-BR/Resources.resw
  Files/Strings/ru-RU/Resources.resw
  Files/Strings/ta/Resources.resw
  Files/Strings/uk-UA/Resources.resw
  Files/Strings/zh-Hans/Resources.resw
  builds/azure-pipelines-release.yml
  builds/azure-pipelines.yml
Labels: approved

#1954 Translation Update [es-ES]
  Files/MultilingualResources/Files.es-ES.xlf
  Files/Strings/es-ES/Resources.resw
Labels: approved

#1959 CodeMaid
  Files/Commands/Delete.cs
  Files/Commands/Paste.cs
  Files/Converters/MultiBooleanConverter.cs
  Files/Dialogs/RestartDialog.xaml
  Files/Dialogs/RestartDialog.xaml.cs
  Files/IShellPage.cs
  Files/Interacts/Interaction.cs
  Files/ResourceDictionaries/PropertiesStyles.xaml
  Files/UserControls/FileIcon.xaml
  Files/UserControls/FileIcon.xaml.cs
  Files/UserControls/MultitaskingControl/HorizontalMultitaskingControl.xaml.cs
  Files/UserControls/StatusCenter.xaml
  Files/UserControls/StatusCenter.xaml.cs
  Files/View Models/InteractionViewModel.cs
  Files/View Models/Properties/PropertiesTab.cs
  Files/View Models/SettingsViewModel.cs
  Files/Views/MainPage.xaml.cs
  Files/Views/ModernShellPage.xaml.cs
  Files/Views/Pages/PropertiesGeneral.xaml
  Files/Views/Pages/PropertiesShortcut.xaml
  Files/Views/SettingsPages/Multitasking.xaml.cs
  Files/Views/SettingsPages/Preferences.xaml
Labels: approved

#1955 translation updated
  Files/MultilingualResources/Files.zh-Hans.xlf
Labels: approved

#1793 More Precise Exception Handling for Item Rename Operation
  Files/Interacts/Interaction.cs
  Files/MultilingualResources/Files.de-DE.xlf
  Files/MultilingualResources/Files.es-ES.xlf
  Files/MultilingualResources/Files.fr-FR.xlf
  Files/MultilingualResources/Files.he-IL.xlf
  Files/MultilingualResources/Files.hi-IN.xlf
  Files/MultilingualResources/Files.it-IT.xlf
  Files/MultilingualResources/Files.ja-JP.xlf
  Files/MultilingualResources/Files.nl-NL.xlf
  Files/MultilingualResources/Files.or-IN.xlf
  Files/MultilingualResources/Files.pl-PL.xlf
  Files/MultilingualResources/Files.pt-BR.xlf
  Files/MultilingualResources/Files.ru-RU.xlf
  Files/MultilingualResources/Files.ta.xlf
  Files/MultilingualResources/Files.tr-TR.xlf
  Files/MultilingualResources/Files.uk-UA.xlf
  Files/MultilingualResources/Files.zh-Hans.xlf
  Files/Strings/en-US/Resources.resw
  Files/Strings/zh-Hans/Resources.resw
Labels: approved

#1966 Translation update [pt-BR]
  Files/MultilingualResources/Files.pt-BR.xlf
  Files/Strings/pt-BR/Resources.resw
Labels: approved

#1967 Use ItemsRepeater control for YourHome library cards
  Files/UserControls/Widgets/LibraryCards.xaml
  Files/UserControls/YourHome.xaml
Labels: needs-review

#1970 v0.15.0
  Files.Package/Package.appxmanifest
Labels: approved

#1973 Fix a crash that would occur when no multitasking option was selected
  Files/BaseLayout.cs
  Files/Views/SettingsPages/Multitasking.xaml
Labels: approved

#1974 Fix properties navigation background
  Files/Views/Pages/Properties.xaml
Labels: approved

#1976 Fix an issue where the "Empty Recycle Bin" menu entry was always disabled
  Files.Launcher/Program.cs
Labels: approved

#1983 Fixed an issue where the progress status displayed as zero when pasting one item
  Files/Commands/Paste.cs
Labels: triage approved

#1945 Fixed and issue with the context menu not appearing when right clicking on exe files
  Files.Launcher/Files.Launcher.csproj
  Files.Launcher/Win32API_ContextMenu.cs
Labels: approved

#1986 Remove "uwp" from README
  README.md
Labels: approved

#1977 Fixed a crash that would sometimes occur when right clicking an item using a touch screen
  Files/Views/LayoutModes/GenericFileBrowser.xaml
  Files/Views/LayoutModes/GenericFileBrowser.xaml.cs
Labels: approved

#1989 Improvements to README.md wording
  README.md
Labels: approved

#1990 Fix properties navigation background
  Files/Views/Pages/Properties.xaml
Labels: approved

#1991 Remove colon from QuickLook in context menu
  Files/MultilingualResources/Files.de-DE.xlf
  Files/MultilingualResources/Files.es-ES.xlf
  Files/MultilingualResources/Files.fr-FR.xlf
  Files/MultilingualResources/Files.he-IL.xlf
  Files/MultilingualResources/Files.hi-IN.xlf
  Files/MultilingualResources/Files.it-IT.xlf
  Files/MultilingualResources/Files.ja-JP.xlf
  Files/MultilingualResources/Files.nl-NL.xlf
  Files/MultilingualResources/Files.or-IN.xlf
  Files/MultilingualResources/Files.pl-PL.xlf
  Files/MultilingualResources/Files.pt-BR.xlf
  Files/MultilingualResources/Files.ru-RU.xlf
  Files/MultilingualResources/Files.ta.xlf
  Files/MultilingualResources/Files.tr-TR.xlf
  Files/MultilingualResources/Files.uk-UA.xlf
  Files/MultilingualResources/Files.zh-Hans.xlf
  Files/Strings/en-US/Resources.resw
Labels: approved

#1992 Update German translation
  Files/MultilingualResources/Files.de-DE.xlf
Labels: approved

#1994 0.15.4
  Files.Package/Package.appxmanifest
Labels: approved

#1996 Fixed a crash that sometimes occurs when pressing Ctrl + C / V / X
  Files/Commands/Paste.cs
  Files/Dialogs/BitlockerDialog.xaml.cs
  Files/Interacts/Interaction.cs
  Files/Views/LayoutModes/GenericFileBrowser.xaml.cs
  Files/Views/LayoutModes/GridViewBrowser.xaml.cs
Labels: approved

#2000 Fixed an issue with sorting items
  Files/Views/LayoutModes/GenericFileBrowser.xaml.cs
Labels: approved

#2010 Fixed an issue with localized file types in tiles view
  Files/Views/LayoutModes/GridViewBrowser.xaml
Labels: approved
