Repository files-community/Files, pull requests merged in 2022-08, with the labels that each got.

#9477 Optimized RD file
  src/Files.Uwp/Properties/Default.rd.xml
Labels: approved

#9640 Optimized rd.xml
  src/Files.Uwp/Properties/Default.rd.xml
Labels: approved

#9633 Add support for more archive types using 7zip
  src/Files.FullTrust/MessageHandlers/Win32MessageHandler.cs
  src/Files.FullTrust/Win32API.cs
  src/Files.Package/7z.dll
  src/Files.Package/7z64.dll
  src/Files.Package/Files.Package.wapproj
  src/Files.Package/Package.appxmanifest
  src/Files.Package/nupkgs/SevenZipSharp.1.0.0.nupkg
  src/Files.Package/nupkgs/SharpZipLib.1.3.4.nupkg
  src/Files.Shared/Extensions/LinqExtensions.cs
  src/Files.Uwp/Files.Uwp.csproj
  src/Files.Uwp/Filesystem/BaseStorage/BaseStorageFile.cs
  src/Files.Uwp/Filesystem/BaseStorage/IBaseStorageFolder.cs
  src/Files.Uwp/Filesystem/Search/FolderSearch.cs
  src/Files.Uwp/Filesystem/StorageEnumerators/Win32StorageEnumerator.cs
  src/Files.Uwp/Filesystem/StorageItems/FtpStorageFile.cs
  src/Files.Uwp/Filesystem/StorageItems/SystemStorageFile.cs
  src/Files.Uwp/Filesystem/StorageItems/ZipStorageFile.cs
  src/Files.Uwp/Filesystem/StorageItems/ZipStorageFolder.cs
  src/Files.Uwp/Helpers/ContextFlyoutItemHelper.cs
  src/Files.Uwp/Helpers/FileExtensionHelpers.cs
  src/Files.Uwp/Helpers/FileThumbnailHelper.cs
  src/Files.Uwp/Helpers/ZipHelpers.cs
  src/Files.Uwp/Interacts/BaseLayoutCommandImplementationModel.cs
  src/Files.Uwp/ViewModels/ItemViewModel.cs
  src/Files.Uwp/ViewModels/MainPageViewModel.cs
  src/Files.Uwp/ViewModels/Previews/ArchivePreviewViewModel.cs
  src/Files.Uwp/ViewModels/Previews/FolderPreviewViewModel.cs
  src/Files.Uwp/ViewModels/Properties/FileProperties.cs
  src/Files.Uwp/ViewModels/Properties/FolderProperties.cs
  src/Files.Uwp/Views/SettingsPages/About.xaml
Labels: approved

#9653 Fix folders sometimes using wrong grouping option
  src/Files.Uwp/Helpers/LayoutPreferences/LayoutPreferences.cs
Labels: approved

#9660 Release: v2.3.5
  src/Files.Package/Files.Package.wapproj
  src/Files.Package/Package.appxmanifest
  src/Files.Uwp/Files.Uwp.csproj
Labels: approved

#9667 Appcenter fixes for 2.3.5
  src/Files.Shared/Extensions/LinqExtensions.cs
  src/Files.Uwp/Filesystem/StorageItems/ZipStorageFile.cs
  src/Files.Uwp/Filesystem/StorageItems/ZipStorageFolder.cs
  src/Files.Uwp/UserControls/Menus/FileTagsContextMenu.xaml.cs
Labels: approved

#9661 Add indicator spacing in properties page & make security icon use up to date font
  src/Files.Uwp/Views/Pages/Properties.xaml
Labels: approved

#9648 Added CTRL+H shortcut to toggle hidden folder visibility. (#6867)
  src/Files.Uwp/Views/ColumnShellPage.xaml
  src/Files.Uwp/Views/ColumnShellPage.xaml.cs
  src/Files.Uwp/Views/ModernShellPage.xaml
  src/Files.Uwp/Views/ModernShellPage.xaml.cs
Labels: approved

#9669 Fix issue causing user settings to be repeatedly reloaded from file in some cases
  src/Files.Uwp/App.xaml.cs
  src/Files.Uwp/Filesystem/StorageHistory/Helpers/StorageHistoryHelpers.cs
  src/Files.Uwp/Serialization/Implementation/CachingJsonSettingsDatabase.cs
Labels: approved

#9668 v2.3.6 release
  src/Files.Package/Package.appxmanifest
Labels: approved

#9544 Introduce abstract storage layer
  Files.sln
  src/Files.Backend/Files.Backend.csproj
  src/Files.Backend/Services/IFileExplorerService.cs
  src/Files.Sdk.Storage/Enums/CreationCollisionOption.cs
  src/Files.Sdk.Storage/Enums/NameCollisionOption.cs
  src/Files.Sdk.Storage/Enums/StorableKind.cs
  src/Files.Sdk.Storage/Extensions/StorageExtensions.cs
  src/Files.Sdk.Storage/Files - Backup.Sdk.Storage.csproj
  src/Files.Sdk.Storage/Files.Sdk.Storage.csproj
  src/Files.Sdk.Storage/IFile.cs
  src/Files.Sdk.Storage/IFolder.cs
  src/Files.Sdk.Storage/IStorable.cs
  src/Files.Sdk.Storage/LocatableStorage/ILocatableFile.cs
  src/Files.Sdk.Storage/LocatableStorage/ILocatableFolder.cs
  src/Files.Sdk.Storage/LocatableStorage/ILocatableStorable.cs
  src/Files.Sdk.Storage/ModifiableStorage/IModifiableFile.cs
  src/Files.Sdk.Storage/ModifiableStorage/IModifiableFolder.cs
  src/Files.Sdk.Storage/ModifiableStorage/IModifiableStorable.cs
  src/Files.Sdk.Storage/Services/IDeviceEnumeratorService.cs
  src/Files.Sdk.Storage/Services/IFileSystemService.cs
  src/Files.Sdk.Storage/StorageEnumeration/IStorageEnumerator.cs
  src/Files.Sdk.Storage/StorageProperties/IStoragePropertiesCollection.cs
  src/Files.Sdk.Storage/StorageProperties/IStorageProperty.cs
  src/Files.Shared/Extensions/EnumerableExtensions.cs
  src/Files.Shared/Helpers/PathHelpers.cs
  src/Files.Uwp.Storage/Files.Uwp.Storage.csproj
  src/Files.Uwp.Storage/FtpStorage/FtpFileSystemService.cs
  src/Files.Uwp.Storage/FtpStorage/FtpHelpers.cs
  src/Files.Uwp.Storage/FtpStorage/FtpManager.cs
  src/Files.Uwp.Storage/FtpStorage/FtpStorable.cs
  src/Files.Uwp.Storage/FtpStorage/FtpStorageFile.cs
  src/Files.Uwp.Storage/FtpStorage/FtpStorageFolder.cs
  src/Files.Uwp.Storage/IsExternalInit.cs
  src/Files.Uwp.Storage/Properties/AssemblyInfo.cs
  src/Files.Uwp.Storage/Properties/Files.Uwp.Storage.rd.xml
  src/Files.Uwp.Storage/WindowsStorage/WindowsStorable.cs
  src/Files.Uwp.Storage/WindowsStorage/WindowsStorageFile.cs
  src/Files.Uwp.Storage/WindowsStorage/WindowsStorageFolder.cs
  src/Files.Uwp/Files.Uwp.csproj
  src/Files.Uwp/Filesystem/StorageItems/FtpStorageFile.cs
  src/Files.Uwp/Filesystem/StorageItems/FtpStorageFolder.cs
  src/Files.Uwp/Filesystem/StorageItems/NativeStorageFile.cs
  src/Files.Uwp/Filesystem/StorageItems/ShellStorageFile.cs
  src/Files.Uwp/Filesystem/StorageItems/ShellStorageFolder.cs
  src/Files.Uwp/Filesystem/StorageItems/SystemStorageFile.cs
  src/Files.Uwp/Filesystem/StorageItems/ZipStorageFile.cs
  src/Files.Uwp/Filesystem/StorageItems/ZipStorageFolder.cs
  src/Files.Uwp/Helpers/FtpHelpers.cs
  src/Files.Uwp/ServicesImplementation/FileExplorerService.cs
Labels: approved

#9611 New Crowdin updates
  src/Files.Uwp/Strings/de-DE/Resources.resw
  src/Files.Uwp/Strings/fr-FR/Resources.resw
  src/Files.Uwp/Strings/it-IT/Resources.resw
  src/Files.Uwp/Strings/ru-RU/Resources.resw
Labels: approved

#9700 Folder path is now displayed when hovering a tab. (#6808)
  src/Files.Uwp/Helpers/MultitaskingTabsHelpers.cs
  src/Files.Uwp/UserControls/MultitaskingControl/HorizontalMultitaskingControl.xaml
  src/Files.Uwp/UserControls/MultitaskingControl/TabItem/TabItem.cs
  src/Files.Uwp/UserControls/MultitaskingControl/VerticalTabViewControl.xaml
  src/Files.Uwp/ViewModels/MainPageViewModel.cs
Labels: approved

#9716 Fix google drive detection
  src/Files.Shared/Extensions/TaskExtensions.cs
  src/Files.Uwp/Filesystem/Cloud/Detector/GoogleDriveCloudDetector.cs
  src/Files.Uwp/Properties/Default.rd.xml
Labels: approved

#9726 Fix archive extraction
  src/Files.Package/nupkgs/SevenZipSharp.1.0.0.nupkg
  src/Files.Uwp/Filesystem/StorageItems/ZipStorageFile.cs
  src/Files.Uwp/Helpers/ZipHelpers.cs
  src/Files.Uwp/ViewModels/PreviewPaneViewModel.cs
  src/Files.Uwp/ViewModels/Previews/ArchivePreviewViewModel.cs
Labels: approved

#9728 Version v2.3.7
  src/Files.Package/Package.appxmanifest
Labels: approved

#9712 5275 set multiple images as desktop background
  src/Files.Uwp/BaseLayout.cs
  src/Files.Uwp/Helpers/ContextFlyoutItemHelper.cs
  src/Files.Uwp/Helpers/FileExtensionHelpers.cs
  src/Files.Uwp/ViewModels/SelectedItemsPropertiesViewModel.cs
Labels: needs-review

#9744 (Manually) Bump FluentFTP from 36.1.0 to 39.3.0 dependencies
  src/Files.Sdk.Storage/Files - Backup.Sdk.Storage.csproj
  src/Files.Uwp.Storage/Files.Uwp.Storage.csproj
  src/Files.Uwp.Storage/FtpStorage/FtpFileSystemService.cs
  src/Files.Uwp.Storage/FtpStorage/FtpStorageFolder.cs
  src/Files.Uwp/Files.Uwp.csproj
  src/Files.Uwp/Filesystem/ListedItem.cs
  src/Files.Uwp/Filesystem/StorageItems/FtpStorageFile.cs
  src/Files.Uwp/Filesystem/StorageItems/FtpStorageFolder.cs
  src/Files.Uwp/Filesystem/StorageItems/ZipStorageFolder.cs
Labels: approved

#9748 Fix for hardcoded OS drives
  src/Files.Uwp/Helpers/CommonPaths.cs
  src/Files.Uwp/Helpers/UIHelpers.cs
  src/Files.Uwp/Views/Pages/PropertiesCustomization.xaml.cs
Labels: approved

#9752 Fixed missing icon for network folder
  src/Files.Uwp/DataModels/NavigationControlItems/DriveItem.cs
Labels: approved

#9710 Feature: Enabled tags by default and removed option to turn them off
  src/Files.Backend/Services/Settings/IPreferencesSettingsService.cs
  src/Files.Uwp/BaseLayout.cs
  src/Files.Uwp/Filesystem/ListedItem.cs
  src/Files.Uwp/Helpers/ContextFlyoutItemHelper.cs
  src/Files.Uwp/ServicesImplementation/Settings/PreferencesSettingsService.cs
  src/Files.Uwp/Strings/en-US/Resources.resw
  src/Files.Uwp/UserControls/InnerNavigationToolbar.xaml
  src/Files.Uwp/UserControls/SidebarControl.xaml
  src/Files.Uwp/ViewModels/ItemViewModel.cs
  src/Files.Uwp/ViewModels/Previews/BasePreviewModel.cs
  src/Files.Uwp/ViewModels/Previews/FolderPreviewViewModel.cs
  src/Files.Uwp/ViewModels/SettingsViewModels/AppearanceViewModel.cs
  src/Files.Uwp/ViewModels/SettingsViewModels/ExperimentalViewModel.cs
  src/Files.Uwp/ViewModels/SidebarViewModel.cs
  src/Files.Uwp/Views/LayoutModes/DetailsLayoutBrowser.xaml.cs
  src/Files.Uwp/Views/SettingsPages/Appearance.xaml
  src/Files.Uwp/Views/SettingsPages/Experimental.xaml
Labels: approved

#9764 Removed x86 build from pipeline
  builds/azure-pipelines-release.yml
Labels: approved

#9766 Fix - Selecting a tag on the sidebar doesn't highlight it
  src/Files.Uwp/Views/MainPage.xaml.cs
  src/Files.Uwp/Views/ModernShellPage.xaml.cs
Labels: approved

#9754 Added option to set current directory setup as the default
  src/Files.Uwp/Strings/en-US/Resources.resw
  src/Files.Uwp/ViewModels/FolderSettingsViewModel.cs
  src/Files.Uwp/Views/LayoutModes/DetailsLayoutBrowser.xaml
  src/Files.Uwp/Views/LayoutModes/DetailsLayoutBrowser.xaml.cs
Labels: approved

#9305 Show selected items size details when selecting by dragging the mouse
  src/Files.Uwp/UserControls/Selection/RectangleSelection_ListViewBase.cs
Labels: approved

#9785 Feature: Added an option to set default columns
  src/Files.Backend/Services/Settings/IPreferencesSettingsService.cs
  src/Files.Uwp/Helpers/AdaptiveLayoutHelpers.cs
  src/Files.Uwp/ServicesImplementation/Settings/PreferencesSettingsService.cs
  src/Files.Uwp/Strings/en-US/Resources.resw
  src/Files.Uwp/ViewModels/FolderSettingsViewModel.cs
  src/Files.Uwp/ViewModels/ItemViewModel.cs
  src/Files.Uwp/ViewModels/SettingsViewModels/PreferencesViewModel.cs
  src/Files.Uwp/ViewModels/ToolbarViewModel.cs
  src/Files.Uwp/Views/SettingsPages/Preferences.xaml
Labels: approved

#9786 Removed vertical tab flyout
  src/Files.Backend/Services/Settings/IMultitaskingSettingsService.cs
  src/Files.Uwp/Files.Uwp.csproj
  src/Files.Uwp/ResourceDictionaries/TabViewItem_shared.xaml
  src/Files.Uwp/ResourceDictionaries/TabView_vertical.xaml
  src/Files.Uwp/ServicesImplementation/Settings/MultitaskingSettingsService.cs
  src/Files.Uwp/Strings/en-US/Resources.resw
  src/Files.Uwp/UserControls/MultitaskingControl/TabItem/TabItemControl.xaml
  src/Files.Uwp/UserControls/MultitaskingControl/VerticalTabViewControl.xaml
  src/Files.Uwp/UserControls/MultitaskingControl/VerticalTabViewControl.xaml.cs
  src/Files.Uwp/ViewModels/SettingsViewModels/MultitaskingViewModel.cs
  src/Files.Uwp/Views/MainPage.xaml
  src/Files.Uwp/Views/MainPage.xaml.cs
  src/Files.Uwp/Views/SettingsPages/Multitasking.xaml
Labels: approved

#9782 Feature: Display uncompressed size when viewing properties for archives
  src/Files.Uwp/Filesystem/StorageItems/ZipStorageFolder.cs
  src/Files.Uwp/Strings/en-US/Resources.resw
  src/Files.Uwp/ViewModels/Properties/FileProperties.cs
  src/Files.Uwp/ViewModels/Properties/FolderProperties.cs
  src/Files.Uwp/ViewModels/SelectedItemsPropertiesViewModel.cs
  src/Files.Uwp/Views/Pages/PropertiesGeneral.xaml
Labels: approved

#9777 Move tags to a sub menu flyout
  src/Files.Uwp/BaseLayout.cs
  src/Files.Uwp/Files.Uwp.csproj
  src/Files.Uwp/Helpers/MenuFlyoutHelper.cs
  src/Files.Uwp/UserControls/Menus/FileTagsContextMenu.cs
  src/Files.Uwp/UserControls/Menus/FileTagsContextMenu.xaml
  src/Files.Uwp/UserControls/Menus/FileTagsContextMenu.xaml.cs
  src/Files.Uwp/UserControls/Menus/MenuFlyoutItemWithImage.xaml
  src/Files.Uwp/UserControls/Menus/MenuFlyoutItemWithImage.xaml.cs
  src/Files.Uwp/ViewModels/SettingsViewModels/PreferencesViewModel.cs
Labels: approved

#9775 Feature: Redid set as background flyout
  src/Files.Uwp/Interacts/BaseLayoutCommandImplementationModel.cs
  src/Files.Uwp/Interacts/BaseLayoutCommandsViewModel.cs
  src/Files.Uwp/Interacts/IBaseLayoutCommandImplementationModel.cs
  src/Files.Uwp/ResourceDictionaries/ToolbarButtonStyle.xaml
  src/Files.Uwp/Strings/en-US/Resources.resw
  src/Files.Uwp/UserControls/AddressToolbar.xaml
  src/Files.Uwp/UserControls/InnerNavigationToolbar.xaml
  src/Files.Uwp/ViewModels/ToolbarViewModel.cs
  src/Files.Uwp/Views/ColumnShellPage.xaml.cs
  src/Files.Uwp/Views/ModernShellPage.xaml.cs
Labels: approved

#9787 Added button to reset layout preferences in settings
  src/Files.Uwp/Strings/en-US/Resources.resw
  src/Files.Uwp/ViewModels/SettingsViewModels/PreferencesViewModel.cs
  src/Files.Uwp/Views/SettingsPages/Preferences.xaml
Labels: approved

#9797 Fix settings export
  src/Files.Package/nupkgs/SevenZipSharp.1.0.0.nupkg
  src/Files.Uwp/Filesystem/StorageItems/ZipStorageFolder.cs
  src/Files.Uwp/Helpers/FileExtensionHelpers.cs
  src/Files.Uwp/ViewModels/SettingsViewModels/AboutViewModel.cs
Labels: approved

#9802 Preview build V2.3.10
  builds/azure-pipelines-release.yml
  src/Files.Package/Package.appxmanifest
Labels: approved

#9810 Add cast from IDictionary to ConcurrentDictionary
  src/Files.Shared/Extensions/LinqExtensions.cs
Labels: approved

#9811 v2.3.11 release
  src/Files.Package/Package.appxmanifest
Labels: triage approved

#9843 Feature: Added support for multiple tag search
  src/Files.Uwp/Filesystem/Search/FolderSearch.cs
Labels: approved

#9852 Fixed Crowdin config
  README.md
  crowdin.yml
Labels: approved

#9859 Fixed release pipeline
  builds/azure-pipelines-release.yml
  builds/azure-pipelines.yml
  src/Files.Package/Package.appxmanifest
Labels: approved

#9862 Add specs folder and drafts
  specs/disco/istorage-enum.md
  specs/disco/listeditem.md
  specs/disco/spec-template.md
  specs/disco/storage-layer.md
Labels: approved

#9857 Get rid of FullTrust for ContextMenu and AppLaunch handlers
  src/Files.App/App.xaml.cs
  src/Files.App/BaseLayout.cs
  src/Files.App/Extensions/ShellNewEntryExtensions.cs
  src/Files.App/Files.App.csproj
  src/Files.App/Filesystem/FilesystemOperations/ShellFilesystemOperations.cs
  src/Files.App/Helpers/ContextFlyoutItemHelper.cs
  src/Files.App/Helpers/LibraryHelper.cs
  src/Files.App/Helpers/NavigationHelpers.cs
  src/Files.App/Helpers/ShellContextMenuHelper.cs
  src/Files.App/Helpers/StorageSenseHelper.cs
  src/Files.App/Helpers/Win32Helpers.cs
  src/Files.App/Interacts/BaseLayoutCommandImplementationModel.cs
  src/Files.App/Shell/ContextMenu.cs
  src/Files.App/Shell/ContextMenuItem.cs
  src/Files.App/Shell/LaunchHelper.cs
  src/Files.App/Shell/ShellFolderExtensions.cs
  src/Files.App/Shell/ShellLibrary2.cs
  src/Files.App/Shell/ShellNewMenuHelper.cs
  src/Files.App/Shell/Win32API.cs
  src/Files.App/UserControls/AddressToolbar.xaml.cs
  src/Files.App/UserControls/SidebarControl.xaml.cs
  src/Files.App/ViewModels/ItemViewModel.cs
  src/Files.App/ViewModels/Properties/CompatibilityProperties.cs
  src/Files.App/ViewModels/SettingsViewModels/ExperimentalViewModel.cs
  src/Files.App/ViewModels/SettingsViewModels/PreferencesViewModel.cs
  src/Files.App/ViewModels/ToolbarViewModel.cs
  src/Files.FullTrust/Files.FullTrust.csproj
  src/Files.FullTrust/MessageHandlers/ContextMenuHandler.cs
  src/Files.FullTrust/Program.cs
  src/Files.Shared/ContextMenu.cs
Labels: approved

#9868 Fix localized strings appearing empty in Compatibility properties
  src/Files.App/Extensions/StringExtensions.cs
Labels: approved

#9865 Partially remove win32 message and recycle bin handlers
  src/Files.App/DataModels/NavigationControlItems/DriveItem.cs
  src/Files.App/Filesystem/RecentItemsManager.cs
  src/Files.App/Filesystem/StorageItems/ShellStorageFile.cs
  src/Files.App/Filesystem/StorageItems/ShellStorageFolder.cs
  src/Files.App/Helpers/BitmapHelper.cs
  src/Files.App/Helpers/FileThumbnailHelper.cs
  src/Files.App/Helpers/NativeWinApiHelper.cs
  src/Files.App/Helpers/RecycleBinHelpers.cs
  src/Files.App/Helpers/UIHelpers.cs
  src/Files.App/Shell/Win32API.cs
  src/Files.App/Shell/Win32Shell.cs
  src/Files.App/UserControls/SidebarControl.xaml.cs
  src/Files.App/ViewModels/SettingsViewModels/ExperimentalViewModel.cs
  src/Files.App/Views/CustomFolderIcons.xaml
  src/Files.App/Views/CustomFolderIcons.xaml.cs
  src/Files.App/Views/Pages/PropertiesGeneral.xaml.cs
  src/Files.FullTrust/MessageHandlers/RecycleBinHandler.cs
  src/Files.FullTrust/MessageHandlers/Win32MessageHandler.cs
  src/Files.FullTrust/Program.cs
  src/Files.FullTrust/Win32API.cs
  src/Files.Shared/IconFileInfo.cs
Labels: approved

#9872 Fix: Fixed appcenter reporting
  src/Files.App/Files.App.csproj
  src/Files.Package/Package.appxmanifest
Labels: approved
