Repository files-community/Files, pull requests merged in 2022-01, with the labels that each got.

#7391 Fix folder shortcuts opening in explorer
  src/Files.Launcher/Helpers/ShellFolderHelpers.cs
  src/Files.Launcher/MessageHandlers/FileOperationsHandler.cs
  src/Files/Filesystem/FilesystemOperations/Helpers/FilesystemHelpers.cs
  src/Files/Filesystem/StorageEnumerators/Win32StorageEnumerator.cs
  src/Files/Helpers/ItemListDisplayHelpers/SortingHelper.cs
Labels: approved

#7394 Install fonts through powershell
  src/Files.Launcher/MessageHandlers/ContextMenuHandler.cs
Labels: approved

#7401 Add support for nextcloud
  src/Common/CloudProvider.cs
  src/Files.Launcher/Helpers/CloudDrivesDetector.cs
Labels: approved

#7406 Detect Yandex.Disk cloud drive
  src/Common/CloudProvider.cs
  src/Files.Launcher/Helpers/CloudDrivesDetector.cs
Labels: approved

#7408 Open recycle bin & this pc in Files when set as default explorer
  src/Files.Launcher/Assets/FilesOpenDialog/SetFilesAsDefault.reg
  src/Files.Launcher/Assets/FilesOpenDialog/UnsetFilesAsDefault.reg
  src/Files.Launcher/MessageHandlers/Win32MessageHandler.cs
  src/Files/App.xaml.cs
  src/Files/Helpers/CommonPaths.cs
  src/Files/Helpers/MultitaskingTabsHelpers.cs
  src/Files/ViewModels/MainPageViewModel.cs
  src/Files/Views/ColumnShellPage.xaml.cs
Labels: approved

#7405 Update Files.de-DE.xlf
  src/Files/MultilingualResources/Files.de-DE.xlf
Labels: approved

#7411 Update SessionManager to allow program files as WinAppDriver location
  tests/Files.InteractionTests/SessionManager.cs
Labels: approved

#7418 Update Files.de-DE.xlf
  src/Files/MultilingualResources/Files.de-DE.xlf
Labels: approved

#7422 Downgrade dotnet SDK to 6.0.100
  builds/azure-pipelines-release.yml
  builds/azure-pipelines.yml
Labels: approved

#7423 Fix for issues #7412, #7396
  src/Files/Extensions/DateTimeExtensions.cs
  src/Files/ViewModels/NavToolbarViewModel.cs
Labels: approved

#7416 Properties improvements
  src/Files/Dialogs/SettingsDialog.xaml
  src/Files/Strings/en-US/Resources.resw
  src/Files/ViewModels/SelectedItemsPropertiesViewModel.cs
  src/Files/Views/Pages/PropertiesGeneral.xaml
Labels: approved

#7429 Update app id for interaction tests
  tests/Files.InteractionTests/SessionManager.cs
Labels: approved

#7440 Update Files.pt-PT.xlf
  src/Files/MultilingualResources/Files.pt-PT.xlf
Labels: approved

#7390 Fix issues with keyboard focus in Details view
  src/Files/Behaviors/StickyHeaderBehavior.cs
  src/Files/Events/ContextItemsChangedEventArgs.cs
  src/Files/Files.csproj
  src/Files/Helpers/AcrylicTheme.cs
  src/Files/Helpers/ThemeHelper.cs
  src/Files/ViewModels/SettingsViewModel.cs
  src/Files/Views/LayoutModes/ColumnViewBase.xaml.cs
  src/Files/Views/LayoutModes/DetailsLayoutBrowser.xaml
  src/Files/Views/LayoutModes/DetailsLayoutBrowser.xaml.cs
  src/Files/Views/LayoutModes/GridViewBrowser.xaml.cs
Labels: approved

#7425 Improve keyboard navigation in column view
  src/Files/UserControls/Selection/RectangleSelection_ListViewBase.cs
  src/Files/Views/ColumnShellPage.xaml.cs
  src/Files/Views/LayoutModes/ColumnViewBase.xaml.cs
  src/Files/Views/LayoutModes/ColumnViewBrowser.xaml
  src/Files/Views/LayoutModes/ColumnViewBrowser.xaml.cs
  src/Files/Views/LayoutModes/GridViewBrowser.xaml.cs
  src/Files/Views/ModernShellPage.xaml.cs
  src/Files/Views/PaneHolderPage.xaml.cs
Labels: approved

#7141 Improve taskbar jumplist
  src/Files/Helpers/JumpListManager.cs
  src/Files/ViewModels/MainPageViewModel.cs
Labels: approved

#7455 Fix text selection when renaming
  src/Files/UserControls/Selection/RectangleSelection_ListViewBase.cs
  src/Files/Views/LayoutModes/ColumnViewBase.xaml.cs
  src/Files/Views/LayoutModes/DetailsLayoutBrowser.xaml.cs
  src/Files/Views/LayoutModes/GridViewBrowser.xaml.cs
Labels: approved

#7456 [Default explorer] Open control panel in existing window
  src/Files.Launcher/Program.cs
  src/Files.Launcher/Win32API.cs
Labels: approved

#7445 feat: Extend DetailsLayout editing element width
  src/Files/Views/LayoutModes/DetailsLayoutBrowser.xaml
  src/Files/Views/LayoutModes/DetailsLayoutBrowser.xaml.cs
Labels: approved

#7463 Remove unnecessary definitions from control panel fix
  src/Files.Launcher/Win32API.cs
Labels: approved

#7464 Do not block while loading drive properties
  src/Files/DataModels/NavigationControlItems/DriveItem.cs
Labels: approved

#7439 Fix advanced properties opening in the wrong window
  src/Files/Views/Pages/PropertiesSecurity.xaml.cs
Labels: approved

#7469 Update Files.zh-Hans.xlf
  src/Files/MultilingualResources/Files.zh-Hans.xlf
Labels: approved

#7480 Check negative textbox width
  src/Files/Strings/zh-Hans/Resources.resw
  src/Files/Views/LayoutModes/DetailsLayoutBrowser.xaml.cs
Labels: approved

#7481 Fix crash if navigation is triggered while renaming
  src/Files/Views/LayoutModes/ColumnViewBase.xaml.cs
  src/Files/Views/LayoutModes/DetailsLayoutBrowser.xaml.cs
  src/Files/Views/LayoutModes/GridViewBrowser.xaml.cs
Labels: approved

#7470 Open new columns in the column layout on a single click
  src/Files/Views/LayoutModes/ColumnViewBase.xaml.cs
Labels: approved

#7488 Update Files.it-IT.xlf
  src/Files/MultilingualResources/Files.it-IT.xlf
Labels: approved

#7489 Update Files.en-GB.xlf
  src/Files/MultilingualResources/Files.en-GB.xlf
Labels: approved

#7484 Fix focus cycle in column view when some settings change
  src/Files/BaseLayout.cs
  src/Files/Behaviors/StickyHeaderBehavior.cs
  src/Files/Views/ColumnShellPage.xaml.cs
  src/Files/Views/ModernShellPage.xaml.cs
Labels: approved

#7503 Updated resw
  src/Files/MultilingualResources/Files.it-IT.xlf
  src/Files/Strings/en-GB/Resources.resw
  src/Files/Strings/it-IT/Resources.resw
Labels: approved

#7467 Bumped version number to v2.1
  src/Files.Package/Package.appxmanifest
Labels: approved

#7500 Properly toggle "permanent delete" check in confirmation dialog
  src/Common/ShellOperationResult.cs
  src/Files.Launcher/Helpers/FileUtils.cs
  src/Files.Launcher/Helpers/ShellFolderHelpers.cs
  src/Files.Launcher/MessageHandlers/FileOperationsHandler.cs
  src/Files/Filesystem/FilesystemOperations/Helpers/FilesystemHelpers.cs
  src/Files/Filesystem/FilesystemOperations/ShellFilesystemOperations.cs
  src/Files/Helpers/RecycleBinHelpers.cs
  src/Files/ViewModels/StatusCenterViewModel.cs
Labels: approved

#7450 Fixed padding on customization page
  src/Files/Views/CustomFolderIcons.xaml
  src/Files/Views/Pages/PropertiesCustomization.xaml
Labels: approved

#7506 fix link to Files docs in CONTRIBUTING.md
  .github/CONTRIBUTING.md
Labels: approved

#7399 Add running interaction tests as part of CI
  .gitignore
  builds/Files_SelfSigned.pfx
  builds/azure-pipelines.yml
  src/Files/UserControls/Settings/SettingsBlockControl.xaml.cs
  src/Files/Views/SettingsPages/Experimental.xaml
  tests/Files.InteractionTests/SessionManager.cs
  tests/Files.InteractionTests/Tests/GeneralAppTests.cs
  tests/Files.InteractionTests/Tests/SettingsTests.cs
Labels: approved

#7517 Simplified the readme file
  .github/issue_label_bot.yaml
  .github/workflows/codeql-analysis.yml
  README.md
Labels: approved

#7538 Fixed folder size visibility in properties for hidden folders
  src/Files/ViewModels/Properties/FolderProperties.cs
Labels: approved

#7545 Updated Dutch translations
  src/Files/MultilingualResources/Files.nl-NL.xlf
Labels: approved

#7558 Ability to set tags on read-only folders
  src/Files/Filesystem/FileTagsHelper.cs
Labels: approved

#7555 Fix crash when deleting items from bin & bin is grouped
  src/Files/Helpers/ItemListDisplayHelpers/BulkConcurrentObservableCollection.cs
  src/Files/Views/PaneHolderPage.xaml.cs
Labels: approved

#7570 update README Prerequisites with required dependencies
  README.md
Labels: approved

#7567 Update Files.pt-BR.xlf
  src/Files/MultilingualResources/Files.pt-BR.xlf
Labels: approved

#7577 Fix german translations causing crash
  src/Files/MultilingualResources/Files.de-DE.xlf
  src/Files/MultilingualResources/Files.it-IT.xlf
  src/Files/MultilingualResources/Files.nl-NL.xlf
  src/Files/Strings/de-DE/Resources.resw
  src/Files/Strings/it-IT/Resources.resw
  src/Files/Strings/nl-NL/Resources.resw
  src/Files/Strings/pt-BR/Resources.resw
Labels: approved

#7557 When multiple files are selected, open them together
  src/Files/Helpers/NavigationHelpers.cs
  src/Files/Helpers/Win32Helpers.cs
Labels: approved

#7483 Fix crash when checking cloud sync status
  src/Files/ViewModels/ItemViewModel.cs
Labels: approved

#7504 Fix issues with back/forward and pathbar navigation in ColumnView
  src/Files/Views/ColumnShellPage.xaml.cs
  src/Files/Views/LayoutModes/ColumnViewBase.xaml.cs
  src/Files/Views/LayoutModes/ColumnViewBrowser.xaml.cs
Labels: approved

#7551 Added sideload link to the readme
  README.md
Labels: approved

#7608 Added privacy section to the readme
  Privacy.md
  README.md
Labels: approved

#7607 Added App Center tracking on startup
  src/Files/App.xaml.cs
  src/Files/Files.csproj
  src/Files/Services/IAppearanceSettingsService.cs
  src/Files/Services/IBaseSettingsService.cs
  src/Files/Services/IBundlesSettingsService.cs
  src/Files/Services/IFileTagsSettingsService.cs
  src/Files/Services/ILayoutSettingsService.cs
  src/Files/Services/IMultitaskingSettingsService.cs
  src/Files/Services/IPreferencesSettingsService.cs
  src/Files/Services/IPreviewPaneSettingsService.cs
  src/Files/Services/IUserSettingsService.cs
  src/Files/Services/IWidgetsSettingsService.cs
  src/Files/Services/Implementation/AppearanceSettingsService.cs
  src/Files/Services/Implementation/BundlesSettingsService.cs
  src/Files/Services/Implementation/FileTagsSettingsService.cs
  src/Files/Services/Implementation/LayoutSettingsService.cs
  src/Files/Services/Implementation/MultitaskingSettingsService.cs
  src/Files/Services/Implementation/PreferencesSettingsService.cs
  src/Files/Services/Implementation/PreviewPaneSettingsService.cs
  src/Files/Services/Implementation/UserSettingsService.cs
  src/Files/Services/Implementation/WidgetsSettingsService.cs
Labels: approved

#7613 Fixed AppCenter initialization
  src/Files/App.xaml.cs
Labels: approved

#7619 Changed default dual pane width to 50%
  src/Files/Views/PaneHolderPage.xaml
Labels: approved

#7649 Fix mistranslations in `Files.ja-JP.xlf`.
  src/Files/MultilingualResources/Files.ja-JP.xlf
Labels: approved

#7632 Update Japanese translation
  src/Files/MultilingualResources/Files.ja-JP.xlf
Labels: approved

#7648 Translation update [es-Latam]
  src/Files/MultilingualResources/Files.es-419.xlf
Labels: approved

#7618 Fixed Inconsistency between file creation flyouts
  src/Files/UserControls/InnerNavigationToolbar.xaml
Labels: approved

#7647 Update Spanish translations
  src/Files/MultilingualResources/Files.es-419.xlf
Labels: approved

#7651 Updated privacy policy
  src/Files/Strings/en-US/Resources.resw
Labels: approved

#7656 Add global.json to force sdk 6.0.100
  src/Files.Launcher/global.json
Labels: triage approved

#7697 Update Japanese translation
  src/Files/MultilingualResources/Files.ja-JP.xlf
Labels: approved

#7653 Added more Arabic translation
  src/Files/MultilingualResources/Files.ar.xlf
Labels: approved

#7706 Update azure-pipelines-release.yml
  builds/azure-pipelines-release.yml
Labels: approved

#7688 Update Hungarian translation
  src/Files/MultilingualResources/Files.hu-HU.xlf
Labels: approved

#7711 Update translations [pl-PL]
  src/Files/MultilingualResources/Files.pl-PL.xlf
Labels: approved

#7698 Fixed string resource for properties button
  src/Files/UserControls/InnerNavigationToolbar.xaml
Labels: approved

#7616 Bundled themes inside of the app
  src/Files/Constants.cs
  src/Files/Files.csproj
  src/Files/Helpers/ExternalResourcesHelper.cs
  src/Files/Themes/Acrylic.xaml
  src/Files/Themes/Black Pixel.xaml
  src/Files/Themes/Blue Acrylic.xaml
  src/Files/Themes/Bound to be Blue.xaml
  src/Files/Themes/Bronze.xaml
  src/Files/Themes/Burgundy.xaml
  src/Files/Themes/Deep Sea.xaml
  src/Files/Themes/Discord.xaml
  src/Files/Themes/Dracula.xaml
  src/Files/Themes/Glass.xaml
  src/Files/Themes/Green Grass.xaml
  src/Files/Themes/Lavender.xaml
  src/Files/Themes/Leaf Green.xaml
  src/Files/Themes/Luxury Red.xaml
  src/Files/Themes/Magentistic.xaml
  src/Files/Themes/Mica Imitation.xaml
  src/Files/Themes/Middle Blue.xaml
  src/Files/Themes/Nord.xaml
  src/Files/Themes/Red Wave.xaml
  src/Files/Themes/Solarized.xaml
  src/Files/Themes/Turquoise.xaml
  src/Files/UserControls/Settings/ThemeSampleDisplayControl.xaml
  src/Files/ViewModels/SettingsViewModel.cs
Labels: approved

#7717 Update Package.appxmanifest v2.1.2
  src/Files.Package/Package.appxmanifest
Labels: needs-review

#7508 Added access keys to the toolbar
  src/Files/UserControls/InnerNavigationToolbar.xaml
Labels: approved

#7727 Update Spanish translations
  src/Files/MultilingualResources/Files.es-ES.xlf
Labels: approved

#7744 Detect Jottacloud cloud drive
  src/Common/CloudProvider.cs
  src/Files.Launcher/Helpers/CloudDrivesDetector.cs
Labels: approved

#7753 Update Vietnamese translation
  src/Files/MultilingualResources/Files.vi.xlf
Labels: approved

#7725 Reduced minimum sidebar width from 250 to 180
  src/Files/Constants.cs
Labels: approved

#7767 Run with PowerShell button on toolbar
  src/Files/Strings/en-US/Resources.resw
  src/Files/UserControls/InnerNavigationToolbar.xaml
  src/Files/ViewModels/NavToolbarViewModel.cs
  src/Files/Views/ModernShellPage.xaml.cs
Labels: approved

#7657 Select newly created files or folders
  src/Files/ViewModels/ItemViewModel.cs
  src/Files/Views/ColumnShellPage.xaml.cs
  src/Files/Views/ModernShellPage.xaml.cs
Labels: approved

#7787 Fixed an issue preventing users from creating multiple bundles
  src/Files/UserControls/Widgets/BundlesWidget.xaml
Labels: approved

#7786 Added support for Segoe UI Variable on Windows 11
  src/BackgroundTasks/BackgroundTasks.csproj
  src/Files.Launcher/Files.Launcher.csproj
  src/Files.Package/Files.Package.wapproj
  src/Files/Files.csproj
Labels: approved

#7817 Latvian translation updated
  src/Files/MultilingualResources/Files.lv-LV.xlf
Labels: approved

#7766 Improve zh-Hant translation
  src/Files/MultilingualResources/Files.zh-Hant.xlf
Labels: approved

#7790 Added info bar to clarify the risks for the option to set Files as the default file manager
  src/Files/Strings/en-US/Resources.resw
  src/Files/Views/SettingsPages/Experimental.xaml
Labels: approved

#7795 Added set as background button on toolbar when selecting image
  src/Files/Files.csproj
  src/Files/Filesystem/ListedItem.cs
  src/Files/Helpers/FileExtensionHelpers.cs
  src/Files/Strings/en-US/Resources.resw
  src/Files/UserControls/InnerNavigationToolbar.xaml
  src/Files/ViewModels/NavToolbarViewModel.cs
  src/Files/Views/ModernShellPage.xaml.cs
Labels: approved

#7831 Translation zh-Hans Updated
  src/Files/MultilingualResources/Files.zh-Hans.xlf
Labels: approved

#7842 Fixed an issue that avoid compiling the project
  src/Files/MultilingualResources/Files.ar.xlf
Labels: approved

#7867 Fixed an issue where folders weren't removed from the JumpList
  src/Files/Helpers/JumpListManager.cs
Labels: approved

#7881 Fixed image thumbnails not appearing
  src/Files/ViewModels/ItemViewModel.cs
  src/Files/ViewModels/Previews/BasePreviewModel.cs
  src/Files/ViewModels/Previews/FolderPreviewViewModel.cs
  src/Files/ViewModels/Properties/FileProperties.cs
Labels: approved

#7402 Migrate from FilesystemResult to SafeWrapper
  src/Files.Shared/Enums/OperationErrorCode.cs
  src/Files.Shared/SafetyHelpers/ExceptionReporters/DefaultSafeWrapperExceptionReporter.cs
  src/Files.Shared/SafetyHelpers/ExceptionReporters/ISafeWrapperExceptionReporter.cs
  src/Files.Shared/SafetyHelpers/SafeWrapperResult.cs
  src/Files.Shared/SafetyHelpers/SafeWrapperResult_T.cs
  src/Files.Shared/SafetyHelpers/SafeWrapperRoutines.cs
  src/Files/App.xaml.cs
  src/Files/ExceptionReporters/FilesystemExceptionReporter.cs
  src/Files/Files.csproj
  src/Files/Filesystem/StorageFileHelpers/FilesystemResult.cs
Labels: approved

#7884 add keybaord shortcut to duplicate tab
  src/Files/Views/ColumnShellPage.xaml
  src/Files/Views/ColumnShellPage.xaml.cs
  src/Files/Views/MainPage.xaml
  src/Files/Views/ModernShellPage.xaml
  src/Files/Views/ModernShellPage.xaml.cs
Labels: approved

#7824 Removed extra controls from the Visual Tree
  src/Files/UserControls/Widgets/DrivesWidget.xaml
  src/Files/UserControls/Widgets/FolderWidget.xaml
  src/Files/UserControls/Widgets/RecentFilesWidget.xaml
  src/Files/Views/LayoutModes/DetailsLayoutBrowser.xaml
  src/Files/Views/LayoutModes/GridViewBrowser.xaml
  src/Files/Views/ModernShellPage.xaml
  src/Files/Views/PaneHolderPage.xaml
Labels: approved

#7859 Added support for opening applications from the pathbox
  src/Files.Launcher/MessageHandlers/ApplicationLaunchHandler.cs
  src/Files.Launcher/Win32API.cs
  src/Files/Helpers/Win32Helpers.cs
  src/Files/ViewModels/NavToolbarViewModel.cs
Labels: approved

#7901 Added ctrl+shift+k shortcut to duplicate tab
  src/Files/UserControls/MultitaskingControl/HorizontalMultitaskingControl.xaml
  src/Files/ViewModels/MainPageViewModel.cs
  src/Files/Views/ColumnShellPage.xaml
  src/Files/Views/ColumnShellPage.xaml.cs
  src/Files/Views/MainPage.xaml
  src/Files/Views/ModernShellPage.xaml
  src/Files/Views/ModernShellPage.xaml.cs
Labels: approved

#7763 Fixed Nextcloud detection
  src/Files.Launcher/Helpers/CloudDrivesDetector.cs
Labels: approved

#7900 Correctly cancel all directory watchers
  src/Files/ViewModels/ItemViewModel.cs
Labels: approved

#7846 Added Install Font button when selecting a font file
  src/Files.Launcher/MessageHandlers/InstallOperationsHandler.cs
  src/Files.Launcher/Program.cs
  src/Files/Helpers/FileExtensionHelpers.cs
  src/Files/Interacts/BaseLayoutCommandImplementationModel.cs
  src/Files/Interacts/BaseLayoutCommandsViewModel.cs
  src/Files/Interacts/IBaseLayoutCommandImplementationModel.cs
  src/Files/Strings/en-US/Resources.resw
  src/Files/UserControls/InnerNavigationToolbar.xaml
  src/Files/ViewModels/NavToolbarViewModel.cs
  src/Files/Views/ColumnShellPage.xaml.cs
  src/Files/Views/ModernShellPage.xaml.cs
Labels: approved

#7832 Added rotate left/right button on toolbar when selecting images
  src/Files/Helpers/BitmapHelper.cs
  src/Files/Interacts/BaseLayoutCommandImplementationModel.cs
  src/Files/Interacts/BaseLayoutCommandsViewModel.cs
  src/Files/Interacts/IBaseLayoutCommandImplementationModel.cs
  src/Files/Interacts/ItemManipulationModel.cs
  src/Files/Strings/en-US/Resources.resw
  src/Files/UserControls/InnerNavigationToolbar.xaml
  src/Files/ViewModels/NavToolbarViewModel.cs
  src/Files/Views/ColumnShellPage.xaml.cs
  src/Files/Views/LayoutModes/GridViewBrowser.xaml.cs
  src/Files/Views/ModernShellPage.xaml.cs
Labels: approved

#7915 Adjusted padding of TabViewScrollButtons
  src/Files/ResourceDictionaries/TabView_themeresources.xaml
Labels: approved

#7937 Added sideload link to readme
  README.md
Labels: approved

#7931 Fixed loading of items under network
  src/Files.Launcher/Helpers/ShellFolderHelpers.cs
Labels: approved

#7860 Added Install button on toolbar when selecting INF files
  src/Files.Launcher/MessageHandlers/InstallOperationsHandler.cs
  src/Files.Launcher/Win32API.cs
  src/Files/Helpers/FileExtensionHelpers.cs
  src/Files/Interacts/BaseLayoutCommandImplementationModel.cs
  src/Files/Interacts/BaseLayoutCommandsViewModel.cs
  src/Files/Interacts/IBaseLayoutCommandImplementationModel.cs
  src/Files/UserControls/InnerNavigationToolbar.xaml
  src/Files/ViewModels/NavToolbarViewModel.cs
  src/Files/Views/ColumnShellPage.xaml.cs
  src/Files/Views/ModernShellPage.xaml.cs
Labels: approved

#7936 Swapped grid for canvas
  src/Files/UserControls/ColoredIcon.xaml
Labels: approved

#7935 Removed extra items from the status bar visual tree
  src/Files/UserControls/StatusBarControl.xaml
Labels: approved

#7938 Switched to SizeChanged for better performance
  src/Files/UserControls/Selection/RectangleSelection_ListViewBase.cs
Labels: approved

#7870 Dev/lubl/infra srvinterface
  src/Files.Backend/Enums/FolderLayoutModes.cs
  src/Files.Backend/Enums/SortOptions.cs
  src/Files.Backend/EventArguments/BaseJsonSettingsModelEventArgs.cs
  src/Files.Backend/Files.Backend.csproj
  src/Files.Backend/Helpers/NativeFileOperationsHelper.cs
  src/Files.Backend/Models/IFileTag.cs
  src/Files.Backend/Models/JsonSettings/BaseJsonSettingsModel.cs
  src/Files.Backend/Models/JsonSettings/BaseObservableJsonSettingsModel.cs
  src/Files.Backend/Models/JsonSettings/IJsonSettingsDatabase.cs
  src/Files.Backend/Models/JsonSettings/IJsonSettingsSerializer.cs
  src/Files.Backend/Models/JsonSettings/ISettingsSerializer.cs
  src/Files.Backend/Models/JsonSettings/ISettingsSharingContext.cs
  src/Files.Backend/Models/JsonSettings/Implementation/CachingJsonSettingsDatabase.cs
  src/Files.Backend/Models/JsonSettings/Implementation/DefaultJsonSettingsDatabase.cs
  src/Files.Backend/Models/JsonSettings/Implementation/DefaultJsonSettingsSerializer.cs
  src/Files.Backend/Models/JsonSettings/Implementation/DefaultSettingsSerializer.cs
  src/Files.Backend/Services/IAppearanceSettingsService.cs
  src/Files.Backend/Services/IBundlesSettingsService.cs
  src/Files.Backend/Services/IFileTagsSettingsService.cs
  src/Files.Backend/Services/ILayoutSettingsService.cs
  src/Files.Backend/Services/IMultitaskingSettingsService.cs
  src/Files.Backend/Services/IPreferencesSettingsService.cs
  src/Files.Backend/Services/IPreviewPaneSettingsService.cs
  src/Files.Backend/Services/IWidgetsSettingsService.cs
  src/Files.Launcher/Files.Launcher.csproj
  src/Files.Shared/CompatibilityOptions.cs
  src/Files.Shared/Enums/OperationErrorCode.cs
  src/Files.Shared/Extensions.cs
  src/Files.Shared/SafetyHelpers/ExceptionReporters/DefaultSafeWrapperExceptionReporter.cs
  src/Files.Shared/SafetyHelpers/ExceptionReporters/ISafeWrapperExceptionReporter.cs
  src/Files.Shared/SafetyHelpers/SafeWrapperResult.cs
  src/Files.Shared/SafetyHelpers/SafeWrapperResult_T.cs
  src/Files.Shared/SafetyHelpers/SafeWrapperRoutines.cs
  src/Files/App.xaml.cs
  src/Files/Enums/FormFactorMode.cs
  src/Files/ExceptionReporters/FilesystemExceptionReporter.cs
  src/Files/Files.csproj
  src/Files/Filesystem/FileTagsHelper.cs
  src/Files/Filesystem/StorageFileHelpers/FilesystemResult.cs
  src/Files/Helpers/AppServiceConnectionHelper.cs
  src/Files/Models/FileTagModel.cs
Labels: approved

#7949 Removed extra controls from visual tree
  src/Files/UserControls/InnerNavigationToolbar.xaml
  src/Files/UserControls/NavigationToolbar.xaml
  src/Files/Views/PaneHolderPage.xaml
Labels: approved

#7891 Fixed repeatedly clicking Restore Default button causing crash
  src/Files/Views/CustomFolderIcons.xaml.cs
Labels: approved

#7946 Update Files.de-DE.xlf
  src/Files/MultilingualResources/Files.de-DE.xlf
Labels: approved

#7882 Fixed delete dialog primary button focus issue
  src/Files/Dialogs/FilesystemOperationDialog.xaml
  src/Files/Dialogs/FilesystemOperationDialog.xaml.cs
Labels: approved

#7955 Updated and completed traditional Chinese translation (Files.zh-Hant.xlf)
  src/Files/MultilingualResources/Files.zh-Hant.xlf
Labels: approved

#7934 Improved visual tree for breadcrumb control
  src/Files/UserControls/PathBreadcrumb.xaml
Labels: approved

#7974 Translated ko-kr
  src/Files/MultilingualResources/Files.ko-KR.xlf
Labels: approved

#7920 Added support for expanding the preview pane further than 400px
  src/Files/Views/MainPage.xaml
Labels: approved

#7982 Updated Traditional Chinese Files.zh-Hant.xlf
  src/Files/MultilingualResources/Files.zh-Hant.xlf
Labels: approved

#7969 Removed extra resources to improve performance
  src/Files/App.xaml
  src/Files/Themes/Acrylic.xaml
  src/Files/Themes/Black Pixel.xaml
  src/Files/Themes/Glass.xaml
  src/Files/Themes/Mica Imitation.xaml
  src/Files/UserControls/PreviewPane.xaml
  src/Files/UserControls/StatusBarControl.xaml
  src/Files/UserControls/Widgets/RecentFilesWidget.xaml
  src/Files/Views/ModernShellPage.xaml
  src/Files/Views/PaneHolderPage.xaml
  src/Files/Views/SettingsPages/Appearance.xaml
Labels: approved

#7939 Removed extra control from MainPage visual tree
  src/Files/Views/MainPage.xaml
Labels: approved

#7985 Fixed missing description in experimental settings page
  src/Files/Views/SettingsPages/Experimental.xaml
Labels: approved

#7970 Fixed an issue where the status center badge was always visible
  src/Files/UserControls/NavigationToolbar.xaml
Labels: approved

#8005 Fixed a crash when opening the conflicts dialog
  src/Files/Dialogs/FilesystemOperationDialog.xaml.cs
Labels: approved

#8010 Fixed a crash when clicking pathbox items
  src/Files/ViewModels/NavToolbarViewModel.cs
Labels: approved

#8014 Fixed back button in columns view (again)
  src/Files/Views/LayoutModes/ColumnViewBrowser.xaml.cs
Labels: approved

#8008 Fix weird open in terminal label
  src/Files/Helpers/ContextFlyoutItemHelper.cs
  src/Files/UserControls/InnerNavigationToolbar.xaml
  src/Files/ViewModels/NavToolbarViewModel.cs
Labels: approved

#8015 Add "Close tabs to the left" and "Close others" to tab context menu
  src/Files/Helpers/MultitaskingTabsHelpers.cs
  src/Files/MultilingualResources/Files.it-IT.xlf
  src/Files/Strings/en-US/Resources.resw
  src/Files/Strings/it-IT/Resources.resw
  src/Files/UserControls/MultitaskingControl/BaseMultitaskingControl.cs
  src/Files/UserControls/MultitaskingControl/HorizontalMultitaskingControl.xaml
  src/Files/UserControls/MultitaskingControl/HorizontalMultitaskingControl.xaml.cs
Labels: approved

#8026 Fixed acrylic themes
  src/Files/Themes/Acrylic.xaml
  src/Files/Themes/Blue Acrylic.xaml
  src/Files/Themes/Glass.xaml
  src/Files/Themes/Mica Imitation.xaml
Labels: approved

#8034 Update Package.appxmanifest
  src/Files.Package/Package.appxmanifest
Labels: approved

#8066 Change "Close others" to "Close other tabs"
  src/Files/Helpers/MultitaskingTabsHelpers.cs
  src/Files/Strings/en-US/Resources.resw
  src/Files/UserControls/MultitaskingControl/BaseMultitaskingControl.cs
  src/Files/UserControls/MultitaskingControl/HorizontalMultitaskingControl.xaml
  src/Files/UserControls/MultitaskingControl/HorizontalMultitaskingControl.xaml.cs
Labels: approved

#8068 Fix ListedItem unsubscribe
  src/Files/Filesystem/ListedItem.cs
Labels: approved
