Repository files-community/Files, pull requests merged in 2022-12, with the labels that each got.

#10613 Fix: Fixed sponsors link
  src/Files.App/Constants.cs
Labels: approved

#10612 Fix: Fixed issue where original date and path was missing from Recycle Bin
  src/Files.App/Filesystem/StorageItems/ShellStorageFile.cs
  src/Files.App/Filesystem/StorageItems/ShellStorageFolder.cs
Labels: approved

#10648 Fix: Fix duplicate window opening when pressing Ctrl+N
  src/Files.App/Helpers/NavigationHelpers.cs
  src/Files.App/Helpers/UniversalLogWriter.cs
  src/Files.App/ViewModels/MainPageViewModel.cs
  src/Files.App/ViewModels/ToolbarViewModel.cs
  src/Files.App/Views/ColumnShellPage.xaml.cs
  src/Files.App/Views/ModernShellPage.xaml.cs
  src/Files.Shared/Logger.cs
Labels: approved

#10667 Fix: Fixed error when compressing a single folder
  src/Files.App/Filesystem/Archive/ArchiveCreator.cs
Labels: approved

#10666 Fix: Fixed issue where previewing css files caused app to crash
  src/Files.App/Filesystem/BaseStorage/BaseStorageFile.cs
Labels: approved

#10665 Fix: Fixed opening a tag from sidebar in a new tab
  src/Files.App/Helpers/ContextFlyoutItemHelper.cs
  src/Files.App/Views/ModernShellPage.xaml.cs
  src/Files.App/Views/PaneHolderPage.xaml.cs
Labels: approved

#10596 Feature: Add support for choosing the default sorting and grouping options
  src/Files.App/Helpers/LayoutPreferences/LayoutPreferences.cs
  src/Files.App/ServicesImplementation/Settings/FoldersSettingsService.cs
  src/Files.App/ServicesImplementation/Settings/LayoutSettingsService.cs
  src/Files.App/Strings/en-US/Resources.resw
  src/Files.App/ViewModels/FolderSettingsViewModel.cs
  src/Files.App/ViewModels/ItemViewModel.cs
  src/Files.App/ViewModels/SettingsViewModels/FoldersViewModel.cs
  src/Files.App/ViewModels/SettingsViewModels/PreferencesViewModel.cs
  src/Files.App/Views/SettingsPages/Folders.xaml
  src/Files.Backend/Services/Settings/IFoldersSettingsService.cs
  src/Files.Backend/Services/Settings/ILayoutSettingsService.cs
  src/Files.Shared/Enums/SortOption.cs
Labels: approved

#10684 Updated bug report template
  .github/ISSUE_TEMPLATE/bug_report.yml
Labels: approved

#10686 Fix: Fixed issue where the prompt to review would crash the app
  src/Files.App/Views/MainPage.xaml.cs
Labels: approved

#10696 Fix: Fixed crash with BundlesViewModel_OpenPathEvent
  src/Files.App/Helpers/NavigationHelpers.cs
Labels: needs-review

#10716 Feature: Added a new theme for fake mica
  src/Files.App/Assets/Themes/MicaBlurDark.jpg
  src/Files.App/Assets/Themes/MicaBlurLight.jpg
  src/Files.App/Files.App.csproj
  src/Files.App/Themes/Fake Mica.xaml
Labels: approved

#10751 Added Josh-65 to sponsor page
  .github/FUNDING.yml
Labels: approved

#10728 Fix: Fixed crash that would occur when switching between Network and Recycle Bin
  src/Files.App/Filesystem/RecentItem.cs
  src/Files.App/Filesystem/StorageItems/ShellStorageFile.cs
  src/Files.App/Shell/ShellFolderExtensions.cs
Labels: approved

#10771 Fix: Fixed opening an executable pinned to start menu
  src/Files.App/Helpers/ShellContextMenuHelper.cs
  src/Files.App/MainWindow.xaml.cs
  src/Files.App/Program.cs
Labels: approved

#10772 Codebase quality: Use helper method for checking .lnk and .url extensions
  src/Files.App/Filesystem/FilesystemOperations/FilesystemOperations.cs
  src/Files.App/Filesystem/StorageEnumerators/UniversalStorageEnumerator.cs
  src/Files.App/Filesystem/StorageEnumerators/Win32StorageEnumerator.cs
  src/Files.App/Filesystem/StorageItems/NativeStorageFile.cs
  src/Files.App/Helpers/FileExtensionHelpers.cs
  src/Files.App/Helpers/FileOperationsHelpers.cs
  src/Files.App/Helpers/FileThumbnailHelper.cs
  src/Files.App/Helpers/NavigationHelpers.cs
  src/Files.App/Helpers/StorageHelpers.cs
  src/Files.App/Shell/Win32Shell.cs
  src/Files.App/ViewModels/Properties/FileProperties.cs
  src/Files.App/ViewModels/Widgets/Bundles/BundleContainerViewModel.cs
  src/Files.App/ViewModels/Widgets/Bundles/BundleItemViewModel.cs
Labels: approved

#10795 Fix: Fixed crash that would occur when updating from the store
  src/Files.App/ServicesImplementation/UpdateService.cs
Labels: approved

#10801 Feature: Add pCloud to the cloud drive section
  src/Files.App/Helpers/CloudDrivesDetector.cs
  src/Files.Shared/Cloud/CloudProviders.cs
Labels: approved

#10819 Feature: iCloud Drive and Photos namespace detection
  src/Files.App/Filesystem/Cloud/Detector/AppleCloudDetector.cs
  src/Files.App/Filesystem/Cloud/Detector/CloudDetector.cs
  src/Files.App/Helpers/CloudDrivesDetector.cs
  src/Files.Shared/Cloud/CloudProviders.cs
Labels: approved

#10814 Feature: Implement the fundamental for rich progress
  .editorconfig
  src/BackgroundTasks/UpdateTask.cs
  src/Files.App.Storage/WindowsStorage/WindowsStorageFolder.cs
  src/Files.App/App.xaml.cs
  src/Files.App/DataModels/NavigationControlItems/DriveItem.cs
  src/Files.App/Filesystem/Archive/ArchiveCreator.cs
  src/Files.App/Filesystem/Archive/IArchiveCreator.cs
  src/Files.App/Filesystem/FilesystemOperations/FileSystemProgress.cs
  src/Files.App/Filesystem/FilesystemOperations/FilesystemOperations.cs
  src/Files.App/Filesystem/FilesystemOperations/Helpers/FilesystemHelpers.cs
  src/Files.App/Filesystem/FilesystemOperations/IFilesystemOperations.cs
  src/Files.App/Filesystem/FilesystemOperations/ShellFilesystemOperations.cs
  src/Files.App/Filesystem/ListedItem.cs
  src/Files.App/Filesystem/StorageHistory/StorageHistoryOperations.cs
  src/Files.App/Filesystem/StorageItems/ShellStorageFolder.cs
  src/Files.App/Helpers/FileOperationsHelpers.cs
  src/Files.App/Helpers/NativeWinApiHelper.cs
  src/Files.App/Helpers/UIFilesystemHelpers.cs
  src/Files.App/Helpers/ZipHelpers.cs
  src/Files.App/Interacts/BaseLayoutCommandImplementationModel.cs
  src/Files.App/ServicesImplementation/Settings/PaneSettingsService.cs
  src/Files.App/ValueConverters/ColorModelToColorConverter.cs
  src/Files.App/ViewModels/Dialogs/DecompressArchiveDialogViewModel.cs
  src/Files.App/ViewModels/Properties/FileProperties.cs
  src/Files.App/ViewModels/SidebarViewModel.cs
  src/Files.App/ViewModels/StatusCenterViewModel.cs
  src/Files.App/Views/LayoutModes/ColumnViewBase.xaml.cs
  src/Files.Backend/Constants.cs
Labels: approved

#10839 Fix: Fixed issue where the network icon was blank
  src/Files.App/DataModels/NavigationControlItems/DriveItem.cs
Labels: approved

#10845 Feature: Added support for Creative Cloud
  src/Files.App/Helpers/CloudDrivesDetector.cs
  src/Files.Shared/Cloud/CloudProviders.cs
Labels: approved

#10846 Code quality: Use FileExtensionHelpers more widely
  src/Files.App/Filesystem/ListedItem.cs
  src/Files.App/Helpers/ContextFlyoutItemHelper.cs
  src/Files.App/Helpers/FileExtensionHelpers.cs
  src/Files.App/Helpers/ShellContextMenuHelper.cs
  src/Files.App/Program.cs
  src/Files.App/Shell/LaunchHelper.cs
  src/Files.App/ViewModels/Properties/FileProperties.cs
  src/Files.App/Views/Pages/Properties.xaml.cs
Labels: approved, codebase quality

#10847 Fix: Fixed issue where the wrong recent item was being removed
  src/Files.App/UserControls/Widgets/RecentFilesWidget.xaml.cs
Labels: approved

#10852 Fix: Added missing txt and zip options in the new file menu
  src/Files.App/Shell/ShellNewMenuHelper.cs
Labels: approved

#10818 Feature: Removed accent color from non-selected items in the column layout
  src/Files.App/Views/LayoutModes/ColumnViewBase.xaml
  src/Files.App/Views/LayoutModes/ColumnViewBase.xaml.cs
  src/Files.App/Views/LayoutModes/ColumnViewBrowser.xaml.cs
Labels: approved

#10777 Feature: Display banner when recent items are turned off from File Explorer
  src/Files.App/Filesystem/RecentItems.cs
  src/Files.App/Strings/en-US/Resources.resw
  src/Files.App/UserControls/Widgets/RecentFilesWidget.xaml
  src/Files.App/UserControls/Widgets/RecentFilesWidget.xaml.cs
Labels: approved

#10874 Fix: Fixed exception when parsing new menu items
  src/Files.App/Shell/ShellNewMenuHelper.cs
Labels: approved

#10872 Feature: Show shortcuts & hidden files in network folders
  src/Files.App/ViewModels/ItemViewModel.cs
Labels: approved

#10865 Fix: Fixed issue where file operations didn't work in AppData
  src/Files.App (Package)/Package.appxmanifest
Labels: approved

#10597 Fix: Prevent Visual Studio from stopping when deleting an item
  src/Files.App/Helpers/FileOperationsHelpers.cs
Labels: approved

#10873 Feature: Show notification only when app crashes
  src/Files.App/App.xaml.cs
Labels: approved

#10880 Fix: Fixed issue where it didn't work to edit/remove startup page
  src/Files.App/Views/SettingsPages/Preferences.xaml
Labels: approved

#10867 Performance: Optimized the recent files widget
  src/Files.App/Filesystem/RecentItem.cs
  src/Files.App/Filesystem/RecentItems.cs
  src/Files.App/UserControls/Widgets/RecentFilesWidget.xaml.cs
Labels: approved

#10890 Feature: Added detection for Nutstore cloud
  src/Files.App/Helpers/CloudDrivesDetector.cs
  src/Files.Shared/Cloud/CloudProviders.cs
Labels: approved

#10467 Code Quality: Refactoring of SidebarControl.xaml.cs
  src/Files.App/UserControls/SidebarControl.xaml
  src/Files.App/UserControls/SidebarControl.xaml.cs
Labels: needs-review
