Repository files-community/Files, pull requests merged in 2022-10, with the labels that each got.

#10097 Fixed: Draging files over items select them
  src/Files.App/BaseLayout.cs
Labels: approved

#10040 Code quality: Remove nullable reference warnings
  src/Files.App/CommandLine/CommandLineParser.cs
  src/Files.App/DataModels/AppModel.cs
  src/Files.App/DataModels/SidebarPinnedModel.cs
  src/Files.App/DataModels/TerminalFileModel.cs
  src/Files.App/Filesystem/Cloud/Detector/GoogleDriveCloudDetector.cs
  src/Files.App/Filesystem/Cloud/Detector/SynologyDriveCloudDetector.cs
  src/Files.App/Filesystem/FilesystemOperations/Helpers/FilesystemHelpers.cs
  src/Files.App/Filesystem/ListedItem.cs
  src/Files.App/Filesystem/Search/FolderSearch.cs
  src/Files.App/Filesystem/StorageEnumerators/UniversalStorageEnumerator.cs
  src/Files.App/Filesystem/StorageEnumerators/Win32StorageEnumerator.cs
  src/Files.App/Helpers/AdaptiveLayoutHelpers.cs
  src/Files.App/Helpers/AsyncManualResetEvent.cs
  src/Files.App/Helpers/ContextFlyoutItemHelper.cs
  src/Files.App/Helpers/ItemListDisplayHelpers/GroupingHelper.cs
  src/Files.App/Helpers/LayoutPreferences/LayoutPreferences.cs
  src/Files.App/Helpers/NavigationHelpers.cs
  src/Files.App/ServicesImplementation/DateTimeFormatter/UserDateTimeFormatter.cs
  src/Files.App/ServicesImplementation/Settings/UserSettingsService.cs
  src/Files.App/UserControls/AddressToolbar.xaml.cs
  src/Files.App/UserControls/FilePreviews/MediaPreview.xaml.cs
  src/Files.App/UserControls/InnerNavigationToolbar.xaml.cs
  src/Files.App/UserControls/MultitaskingControl/HorizontalMultitaskingControl.xaml.cs
  src/Files.App/UserControls/RestartControl.xaml.cs
  src/Files.App/UserControls/SidebarControl.xaml.cs
  src/Files.App/UserControls/Widgets/BundlesWidget.xaml.cs
  src/Files.App/UserControls/Widgets/DrivesWidget.xaml.cs
  src/Files.App/UserControls/Widgets/FolderWidget.xaml.cs
  src/Files.App/UserControls/Widgets/RecentFilesWidget.xaml.cs
  src/Files.App/ViewModels/FolderSettingsViewModel.cs
  src/Files.App/ViewModels/ItemViewModel.cs
  src/Files.App/ViewModels/MainPageViewModel.cs
  src/Files.App/ViewModels/PreviewPaneViewModel.cs
  src/Files.App/ViewModels/Previews/BasePreviewModel.cs
  src/Files.App/ViewModels/SettingsViewModels/AppearanceViewModel.cs
  src/Files.App/ViewModels/SettingsViewModels/ExperimentalViewModel.cs
  src/Files.App/ViewModels/SettingsViewModels/MultitaskingViewModel.cs
  src/Files.App/ViewModels/SettingsViewModels/PreferencesViewModel.cs
  src/Files.App/ViewModels/SidebarViewModel.cs
  src/Files.App/ViewModels/ToolbarViewModel.cs
  src/Files.App/ViewModels/Widgets/Bundles/BundleItemViewModel.cs
  src/Files.App/Views/ColumnShellPage.xaml.cs
  src/Files.App/Views/LayoutModes/ColumnViewBase.xaml.cs
  src/Files.App/Views/LayoutModes/GridViewBrowser.xaml.cs
  src/Files.App/Views/MainPage.xaml.cs
  src/Files.App/Views/ModernShellPage.xaml.cs
  src/Files.App/Views/PaneHolderPage.xaml.cs
  src/Files.App/Views/WidgetsPage.xaml.cs
Labels: needs-review

#10114 Code quality: Reduced duplicate code for the sidebar
  src/Files.App/Constants.cs
  src/Files.App/Filesystem/WSLDistroManager.cs
  src/Files.App/ViewModels/MainPageViewModel.cs
  src/Files.App/ViewModels/SidebarViewModel.cs
Labels: approved

#10118 Fix: UpdateService Bundle Path
  src/Files.App/ServicesImplementation/SideloadUpdateService.cs
Labels: approved

#10089 Feature: Added option to change default layout mode
  src/Files.App/Helpers/AdaptiveLayoutHelpers.cs
  src/Files.App/Helpers/LayoutPreferences/LayoutPreferences.cs
  src/Files.App/ServicesImplementation/Settings/LayoutSettingsService.cs
  src/Files.App/ServicesImplementation/Settings/PreferencesSettingsService.cs
  src/Files.App/Strings/en-US/Resources.resw
  src/Files.App/ViewModels/FolderSettingsViewModel.cs
  src/Files.App/ViewModels/SettingsViewModels/PreferencesViewModel.cs
  src/Files.App/Views/SettingsPages/Preferences.xaml
  src/Files.Backend/Services/Settings/ILayoutSettingsService.cs
  src/Files.Backend/Services/Settings/IPreferencesSettingsService.cs
  src/Files.Shared/Enums/FolderLayoutModes.cs
Labels: needs-review

#10117 Feature: Added option to set default column sizes
  src/Files.App/Helpers/LayoutPreferences/LayoutPreferences.cs
  src/Files.App/ServicesImplementation/Settings/LayoutSettingsService.cs
  src/Files.App/ServicesImplementation/Settings/PreferencesSettingsService.cs
  src/Files.App/ViewModels/FolderSettingsViewModel.cs
  src/Files.App/ViewModels/SettingsViewModels/PreferencesViewModel.cs
  src/Files.Backend/Services/Settings/IPreferencesSettingsService.cs
Labels: approved

#10130 Feature: Display error modal when shortcut target cannot be found
  src/Files.App/Helpers/DynamicDialogFactory.cs
  src/Files.App/Helpers/NavigationHelpers.cs
  src/Files.App/Shell/Win32Shell.cs
  src/Files.App/Strings/en-US/Resources.resw
  src/Files.Shared/ShellLinkItem.cs
Labels: approved

#9886 Feature: Display recent searches when clicking on the search box
  src/Files.App/DataModels/SuggestionModel.cs
  src/Files.App/ISearchBox.cs
  src/Files.App/UserControls/SearchBox.xaml
  src/Files.App/ViewModels/SearchBoxViewModel.cs
  src/Files.App/ViewModels/ToolbarViewModel.cs
  src/Files.App/Views/ColumnShellPage.xaml.cs
  src/Files.App/Views/ModernShellPage.xaml.cs
Labels: approved

#10180 Fix: Folder suggestions are not showing in the Address bar
  src/Files.App/UserControls/AddressToolbar.xaml
Labels: approved

#9959 Fix: Fixed an issue where clicking Home on the sidebar wouldn't cancel tag searches
  src/Files.App/Views/ModernShellPage.xaml.cs
Labels: approved

#9997 Feature: Added menu option to compress items into archive
  src/Files.App/Helpers/ContextFlyoutItemHelper.cs
  src/Files.App/Helpers/ZipHelpers.cs
  src/Files.App/Interacts/BaseLayoutCommandImplementationModel.cs
  src/Files.App/Interacts/BaseLayoutCommandsViewModel.cs
  src/Files.App/Interacts/IBaseLayoutCommandImplementationModel.cs
  src/Files.App/Strings/en-US/Resources.resw
  src/Files.Shared/Enums/FileOperationType.cs
Labels: needs-review

#10196 Fix: Fixed issue where default file manager affected other user accounts
  src/Files.FullTrust/Assets/FilesOpenDialog/SetFilesAsDefault.reg
Labels: approved

#10203 Fix: Fixed issue where tags section showed "move" option
  src/Files.App/UserControls/SidebarControl.xaml.cs
Labels: approved

#10207 Feature: Merged similar settings into "Open items with a single click"
  src/Files.App/ServicesImplementation/Settings/FoldersSettingsService.cs
  src/Files.App/Strings/en-US/Resources.resw
  src/Files.App/ViewModels/SettingsViewModels/FoldersViewModel.cs
  src/Files.App/Views/LayoutModes/ColumnViewBase.xaml.cs
  src/Files.App/Views/LayoutModes/DetailsLayoutBrowser.xaml.cs
  src/Files.App/Views/LayoutModes/GridViewBrowser.xaml.cs
  src/Files.App/Views/SettingsPages/Folders.xaml
  src/Files.Backend/Services/Settings/IFoldersSettingsService.cs
Labels: needs-review

#10202 Fix: Fixed issue where GridSplitter style was missing on the details layout
  src/Files.App/Views/LayoutModes/DetailsLayoutBrowser.xaml
  src/Files.App/Views/LayoutModes/DetailsLayoutBrowser.xaml.cs
Labels: approved

#10212 Code: Fixed typo
  src/Files.App/ViewModels/Properties/FolderProperties.cs
  src/Files.App/ViewModels/SelectedItemsPropertiesViewModel.cs
  src/Files.App/Views/Pages/PropertiesGeneral.xaml
Labels: approved

#10219 Fix: Fixed issue where right clicking on sidebar items showed the wrong menu options
  src/Files.App/UserControls/SidebarControl.xaml.cs
Labels: approved

#10239 Fix: Fixed issue where columns sometimes had no width
  src/Files.App/ServicesImplementation/Settings/FoldersSettingsService.cs
Labels: approved

#10250 Code: Implement inter-process synchronization for LiteDB
  src/Files.App/Filesystem/FileTagsHelper.cs
  src/Files.App/Filesystem/ListedItem.cs
  src/Files.App/Filesystem/Search/FolderSearch.cs
  src/Files.App/Helpers/FileOperationsHelpers.cs
  src/Files.App/Helpers/FileTagsHelpers.cs
  src/Files.App/Helpers/LayoutPreferences/LayoutPrefsDb.cs
  src/Files.App/MainWindow.xaml.cs
  src/Files.App/ViewModels/FolderSettingsViewModel.cs
  src/Files.App/ViewModels/ItemViewModel.cs
  src/Files.App/ViewModels/SettingsViewModels/AboutViewModel.cs
  src/Files.App/ViewModels/SettingsViewModels/FoldersViewModel.cs
  src/Files.Backend/Files.Backend.csproj
  src/Files.Sdk.Storage/Files.Sdk.Storage.csproj
  src/Files.Shared/FileTagsDb.cs
  src/Files.Shared/Files.Shared.csproj
Labels: approved

#10241 Fix: Fixed issue where untagged files were sometimes displayed in the search results
  src/Files.App/Views/ModernShellPage.xaml.cs
Labels: approved

#10243 Feature: Added extract archive button inside archives
  src/Files.App/Helpers/FileExtensionHelpers.cs
  src/Files.App/Interacts/BaseLayoutCommandImplementationModel.cs
  src/Files.App/UserControls/InnerNavigationToolbar.xaml
  src/Files.App/ViewModels/ToolbarViewModel.cs
Labels: approved

#10206 Feature: Code quality issue template
  .github/ISSUE_TEMPLATE/code_quality_issue.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
Labels: approved

#10253 Fixed issues involving #10243
  src/Files.App/UserControls/InnerNavigationToolbar.xaml
  src/Files.App/ViewModels/ToolbarViewModel.cs
Labels: approved

#10240 Fix: Fixed an issue where the name column had a max width
  src/Files.App/ViewModels/ColumnsViewModel.cs
  src/Files.App/Views/LayoutModes/DetailsLayoutBrowser.xaml
Labels: approved

#10259 Fix: Fixed issue where the progress bar wasn't shown when connecting new drives
  src/Files.App/DataModels/NavigationControlItems/DriveItem.cs
Labels: approved

#10242 Feature: Improved the tooltip when hovering over drives
  src/Files.App/DataModels/NavigationControlItems/DriveItem.cs
  src/Files.App/UserControls/SidebarControl.xaml
Labels: approved

#10258 Fix: Fixed issue where drives had the wrong order in the sidebar
  src/Files.App/UserControls/Widgets/DrivesWidget.xaml.cs
  src/Files.App/ViewModels/SidebarViewModel.cs
Labels: approved

#10260 Fix: Fixed issue with the text alignment in the properties window
  src/Files.App/UserControls/SidebarControl.xaml
  src/Files.App/Views/Pages/PropertiesGeneral.xaml
Labels: approved

#9961 Fix: Fixed issue where turning off grouping can show an empty view
  src/Files.App/Views/LayoutModes/ColumnViewBase.xaml
  src/Files.App/Views/LayoutModes/ColumnViewBase.xaml.cs
  src/Files.App/Views/LayoutModes/ColumnViewBrowser.xaml.cs
  src/Files.App/Views/LayoutModes/DetailsLayoutBrowser.xaml
  src/Files.App/Views/LayoutModes/DetailsLayoutBrowser.xaml.cs
  src/Files.App/Views/LayoutModes/GridViewBrowser.xaml
  src/Files.App/Views/LayoutModes/GridViewBrowser.xaml.cs
Labels: needs-review

#10269 Feature: Display drive letter of the connected network drives
  src/Files.App/DataModels/NavigationControlItems/DriveItem.cs
Labels: approved

#10274 Fix: Fixed progress ring style in drive tooltip
  src/Files.App/UserControls/SidebarControl.xaml
  src/Files.App/Views/Pages/PropertiesGeneral.xaml
Labels: approved

#10285 Remove OpenProtectedFileForRead function
  src/Files.App/Filesystem/StorageItems/ZipStorageFile.cs
  src/Files.App/Helpers/FileOperationsHelpers.cs
  src/Files.App/Helpers/NativeFileOperationsHelper.cs
Labels: approved

#10293 Fix: Fixed issue where renaming a shortcut that had a blank name would cause a crash
  src/Files.App/Helpers/UIFilesystemHelpers.cs
Labels: approved

#10295 Fix: Fixed issue where the sidebars right click menu would sometimes get cut off
  src/Files.App/UserControls/SidebarControl.xaml.cs
Labels: approved

#10299 Fix: Remove icons from extract flyout
  src/Files.App/UserControls/InnerNavigationToolbar.xaml
Labels: changes requested

#10306 Feature: Open selected folders in new tab using Ctrl+Enter
  src/Files.App/Views/ColumnShellPage.xaml.cs
  src/Files.App/Views/LayoutModes/ColumnViewBase.xaml.cs
  src/Files.App/Views/LayoutModes/DetailsLayoutBrowser.xaml.cs
  src/Files.App/Views/LayoutModes/GridViewBrowser.xaml.cs
  src/Files.App/Views/ModernShellPage.xaml.cs
Labels: approved

#10318 Feature: Improve loading animations on the home page
  src/Files.App/UserControls/Widgets/DrivesWidget.xaml.cs
  src/Files.App/UserControls/Widgets/FolderWidget.xaml.cs
  src/Files.App/ViewModels/Pages/YourHomeViewModel.cs
Labels: approved

#10303 Fix: Fixed issue where the drive letter was included in the name
  src/Files.App/Views/Pages/PropertiesGeneral.xaml
  src/Files.App/Views/Pages/PropertiesGeneral.xaml.cs
Labels: approved

#10322 Feature: Optimize startup speed
  src/Files.App/App.xaml.cs
  src/Files.App/Helpers/UniversalLogWriter.cs
  src/Files.App/MainWindow.xaml.cs
Labels: approved

#10329 Feature: Lazily loading themes to improve startup time
  src/Files.App/App.xaml.cs
  src/Files.App/Dialogs/DynamicDialog.xaml
  src/Files.App/Dialogs/ElevateConfirmDialog.xaml
  src/Files.App/Files.App.csproj
  src/Files.App/Helpers/ExternalResourcesHelper.cs
  src/Files.App/Strings/en-US/Resources.resw
  src/Files.App/UserControls/PathBreadcrumb.xaml
  src/Files.App/ViewModels/SettingsViewModels/AppearanceViewModel.cs
  src/Files.App/ViewModels/SettingsViewModels/FoldersViewModel.cs
  src/Files.App/ViewModels/SettingsViewModels/PreferencesViewModel.cs
  src/Files.App/Views/LayoutModes/GridViewBrowser.xaml
  src/Files.App/Views/MainPage.xaml.cs
  src/Files.App/Views/Pages/PropertiesLibrary.xaml
  src/Files.App/Views/Pages/PropertiesLibrary.xaml.cs
  src/Files.App/Views/SettingsPages/Appearance.xaml
  src/Files.App/Views/SettingsPages/Appearance.xaml.cs
  src/Files.App/Views/SettingsPages/Experimental.xaml
  src/Files.App/Views/SettingsPages/Folders.xaml
  src/Files.App/Views/SettingsPages/Preferences.xaml
Labels: approved

#10339 Fix: Fixed column Type text
  src/Files.App/Strings/en-US/Resources.resw
Labels: approved

#10353 Fix FilesLauncher and CustomOpenDialog projects
  src/Files.App/Helpers/FileOperationsHelpers.cs
  src/Files.OpenDialog/CustomOpenDialog/CustomOpenDialog.vcxproj
  src/Files.OpenDialog/FilesLauncher/FilesLauncher.vcxproj
  src/Files.OpenDialog/FilesLauncher/packages.config
Labels: approved

#10349 Fix: Fixed issue where double tap to rename was no longer working
  src/Files.App/Views/LayoutModes/ColumnViewBase.xaml.cs
  src/Files.App/Views/LayoutModes/DetailsLayoutBrowser.xaml.cs
  src/Files.App/Views/LayoutModes/GridViewBrowser.xaml.cs
Labels: approved

#10352 Fix: Fixed notification on Win+E
  src/Files.App/App.xaml.cs
Labels: approved

#10341 Fix: Fixed issue where emptying recycle bin wouldn't display the operation in the status center
  src/Files.App/Helpers/RecycleBinHelpers.cs
  src/Files.App/Strings/en-US/Resources.resw
Labels: needs-review

#10364 Fixed crash that would occur when emptying recycle bin from the sidebar
  src/Files.App/ViewModels/ItemViewModel.cs
Labels: approved

#10323 Fix: Fixed issue where delete modal displayed duplicate items
  src/Files.App/Filesystem/FilesystemOperations/ShellFilesystemOperations.cs
Labels: approved
