Repository files-community/Files, pull requests merged in 2023-02, with the labels that each got.

#11125 Fix: Fixed showing a negative elapsed time in case of a future timestamp
  src/Files.App/ServicesImplementation/DateTimeFormatter/ApplicationDateTimeFormatter.cs
  src/Files.App/Strings/en-US/Resources.resw
  src/Files.App/ViewModels/SettingsViewModels/PreferencesViewModel.cs
Labels: approved

#11087 Fix: Fixed wrong date format when language is set to Default
  src/Files.App/ServicesImplementation/DateTimeFormatter/AbstractDateTimeFormatter.cs
Labels: needs-review

#11130 Fix: Fixed issue with environment variables not working for shortcuts
  src/Files.App/Helpers/UIFilesystemHelpers.cs
  src/Files.App/ViewModels/Properties/FolderProperties.cs
Labels: approved

#11094 Codebase Quality: Made RecycleBinHelpers static
  src/Files.App/BaseLayout.cs
  src/Files.App/Filesystem/FilesystemOperations/FilesystemOperations.cs
  src/Files.App/Filesystem/FilesystemOperations/Helpers/FilesystemHelpers.cs
  src/Files.App/Filesystem/FilesystemOperations/ShellFilesystemOperations.cs
  src/Files.App/Helpers/RecycleBinHelpers.cs
  src/Files.App/Interacts/BaseLayoutCommandImplementationModel.cs
  src/Files.App/UserControls/SidebarControl.xaml.cs
  src/Files.App/ViewModels/SidebarViewModel.cs
Labels: approved

#11063 Feature: Use the tab key to select the next file while renaming
  src/Files.App/UserControls/SearchBox.xaml
  src/Files.App/UserControls/SearchBox.xaml.cs
  src/Files.App/ViewModels/SearchBoxViewModel.cs
  src/Files.App/Views/LayoutModes/ColumnViewBase.xaml.cs
  src/Files.App/Views/LayoutModes/DetailsLayoutBrowser.xaml.cs
  src/Files.App/Views/LayoutModes/GridViewBrowser.xaml.cs
  src/Files.App/Views/LayoutModes/StandardLayoutMode.cs
Labels: needs-review

#11100 Fix: Fixed issue with creating new archives in a library
  src/Files.App/Interacts/BaseLayoutCommandImplementationModel.cs
Labels: approved

#11013 Feature: Show error when a shortcut can't be created
  src/Files.App/Dialogs/CreateShortcutDialog.xaml
  src/Files.App/Dialogs/CreateShortcutDialog.xaml.cs
  src/Files.App/Filesystem/FilesystemOperations/ShellFilesystemOperations.cs
  src/Files.App/Helpers/UIFilesystemHelpers.cs
  src/Files.App/Interacts/BaseLayoutCommandImplementationModel.cs
  src/Files.App/Strings/en-US/Resources.resw
  src/Files.App/ViewModels/Dialogs/CreateShortcutDialogViewModel.cs
Labels: approved

#11131 Fix: Fixed issue where multiselect broke open with single click
  src/Files.App/Views/LayoutModes/DetailsLayoutBrowser.xaml.cs
  src/Files.App/Views/LayoutModes/GridViewBrowser.xaml.cs
Labels: approved

#11133 Feature: Added support for hiding the edit tags menu
  src/Files.App/BaseLayout.cs
  src/Files.App/ServicesImplementation/Settings/AppearanceSettingsService.cs
  src/Files.App/Strings/en-US/Resources.resw
  src/Files.App/ViewModels/SettingsViewModels/AppearanceViewModel.cs
  src/Files.App/Views/SettingsPages/Appearance.xaml
  src/Files.Backend/Services/Settings/IAppearanceSettingsService.cs
Labels: approved

#11120 Feature: Sync pinned favorites with File Explorer
  src/Files.App/App.xaml.cs
  src/Files.App/Controllers/SidebarPinnedController.cs
  src/Files.App/DataModels/NavigationControlItems/DriveItem.cs
  src/Files.App/DataModels/SidebarPinnedModel.cs
  src/Files.App/Filesystem/ListedItem.cs
  src/Files.App/Filesystem/QuickAccessManager.cs
  src/Files.App/Helpers/SidebarHelpers.cs
  src/Files.App/Interacts/BaseLayoutCommandImplementationModel.cs
  src/Files.App/ServicesImplementation/QuickAccessService.cs
  src/Files.App/UserControls/SidebarControl.xaml.cs
  src/Files.App/UserControls/Widgets/DrivesWidget.xaml.cs
  src/Files.App/ViewModels/SettingsViewModels/AdvancedViewModel.cs
  src/Files.App/ViewModels/SidebarViewModel.cs
  src/Files.Backend/Services/IQuickAccessService.cs
Labels: approved

#11011 Codebase: Make private service fields readonly
  src/Files.App/Filesystem/FilesystemOperations/FilesystemOperations.cs
  src/Files.App/Filesystem/FilesystemOperations/ShellFilesystemOperations.cs
  src/Files.App/Filesystem/ListedItem.cs
  src/Files.App/Filesystem/Search/FolderSearch.cs
  src/Files.App/ServicesImplementation/FileTagsService.cs
  src/Files.App/ViewModels/ItemViewModel.cs
  src/Files.App/ViewModels/PreviewPaneViewModel.cs
  src/Files.App/ViewModels/SettingsViewModels/AboutViewModel.cs
  src/Files.App/ViewModels/SettingsViewModels/AdvancedViewModel.cs
  src/Files.App/ViewModels/Widgets/Bundles/BundleItemViewModel.cs
  src/Files.App/Views/ColumnShellPage.xaml.cs
  src/Files.App/Views/ModernShellPage.xaml.cs
Labels: approved

#11140 Fix: Fixed crash that would sometimes occur when pinning folders to the sidebar
  src/Files.App/ServicesImplementation/QuickAccessService.cs
Labels: approved

#11146 Fix: Fixed typo in resources.resw
  src/Files.App/Strings/en-US/Resources.resw
Labels: approved

#10948 Code quality: Refactoring and improvements
  src/Files.App/BaseLayout.cs
  src/Files.App/DataModels/SidebarPinnedModel.cs
  src/Files.App/Filesystem/FilesystemOperations/ShellFilesystemOperations.cs
  src/Files.App/Helpers/ContextFlyoutItemHelper.cs
  src/Files.App/Helpers/DriveHelpers.cs
  src/Files.App/Helpers/ItemModelListToContextFlyoutHelper.cs
  src/Files.App/Helpers/NavigationHelpers.cs
  src/Files.App/Helpers/ShellContextMenuHelper.cs
  src/Files.App/Shell/ContextMenu.cs
  src/Files.App/Shell/ShellNewMenuHelper.cs
  src/Files.App/UserControls/SidebarControl.xaml
  src/Files.App/UserControls/SidebarControl.xaml.cs
  src/Files.App/UserControls/Widgets/DrivesWidget.xaml.cs
  src/Files.App/ViewModels/ItemViewModel.cs
  src/Files.App/ViewModels/MainPageViewModel.cs
  src/Files.App/Views/LayoutModes/DetailsLayoutBrowser.xaml.cs
Labels: approved

#11148 Feature: Add support for Autodesk drive
  src/Files.App/Helpers/CloudDrivesDetector.cs
  src/Files.Shared/Cloud/CloudProviders.cs
Labels: approved

#11165 Fix: Fixed app crash when opening details tab in file properties
  src/Files.App/ViewModels/Properties/FileProperties.cs
Labels: approved

#11144 Feature: Prompt for credentials when connecting smb
  src/Files.App/Filesystem/NetworkDrivesAPI.cs
  src/Files.App/Helpers/DynamicDialogFactory.cs
  src/Files.App/Helpers/NavigationHelpers.cs
  src/Files.App/Strings/en-US/Resources.resw
  src/Files.App/ViewModels/ToolbarViewModel.cs
Labels: approved

#11169 Fix: Fixed quick access widgets when there are few items
  src/Files.App/DataModels/SidebarPinnedModel.cs
  src/Files.App/Filesystem/RecentItems.cs
  src/Files.App/ServicesImplementation/QuickAccessService.cs
  src/Files.App/Shell/Win32Shell.cs
  src/Files.App/UserControls/Widgets/QuickAccessWidget.xaml.cs
  src/Files.Backend/Services/IQuickAccessService.cs
  src/Files.Shared/ShellFileItem.cs
Labels: approved

#11188 Fix: Fixed icon not showing in stable and preview builds
  src/Files.App/App.xaml.cs
  src/Files.App/Constants.cs
  src/Files.App/Helpers/FilePropertiesHelpers.cs
  src/Files.App/MainWindow.xaml.cs
Labels: approved

#11187 Fix: Fixed issue where it didn't work to unpin Recycle Bin from sidebar
  src/Files.App/Filesystem/QuickAccessManager.cs
  src/Files.App/ServicesImplementation/QuickAccessService.cs
Labels: approved

#11186 Feature: Add menu flyout to widget header
  src/Files.App/Strings/en-US/Resources.resw
  src/Files.App/UserControls/Widgets/BundlesWidget.xaml.cs
  src/Files.App/UserControls/Widgets/DrivesWidget.xaml
  src/Files.App/UserControls/Widgets/DrivesWidget.xaml.cs
  src/Files.App/UserControls/Widgets/FileTagsWidget.xaml.cs
  src/Files.App/UserControls/Widgets/QuickAccessWidget.xaml.cs
  src/Files.App/UserControls/Widgets/RecentFilesWidget.xaml.cs
  src/Files.App/UserControls/Widgets/WidgetsListControl.xaml
  src/Files.App/ViewModels/Widgets/IWidgetItemModel.cs
  src/Files.App/ViewModels/Widgets/WidgetsListControlItemViewModel.cs
Labels: needs-review

#11192 Feature: Added shortcut to open folders in terminal
  src/Files.App/Views/ColumnShellPage.xaml.cs
  src/Files.App/Views/ModernShellPage.xaml.cs
Labels: approved

#11185 Feature: Show confirmation dialog when the undo operation is to delete items.
  src/Files.App/Filesystem/StorageHistory/Helpers/StorageHistoryHelpers.cs
  src/Files.App/Filesystem/StorageHistory/StorageHistoryOperations.cs
Labels: approved

#11201 Fix: Fixed the dialog may not be shown when undoing to delete items
  src/Files.App/Filesystem/FilesystemOperations/Helpers/FilesystemHelpers.cs
  src/Files.App/Helpers/RecycleBinHelpers.cs
  src/Files.App/Views/ColumnShellPage.xaml.cs
  src/Files.App/Views/ModernShellPage.xaml.cs
Labels: approved

#11198 Fixed: DetailsLayout Margin/Padding is not set correctly
  src/Files.App/ViewModels/ColumnsViewModel.cs
  src/Files.App/Views/LayoutModes/DetailsLayoutBrowser.xaml
Labels: approved

#11003 Feature: Close column when selecting a file
  src/Files.App/Views/LayoutModes/ColumnViewBase.xaml.cs
  src/Files.App/Views/LayoutModes/ColumnViewBrowser.xaml.cs
Labels: needs-review

#11212 Feature: Added option to confirm permanent deletion only
  src/Files.App/Filesystem/FilesystemOperations/Helpers/FilesystemHelpers.cs
  src/Files.App/Filesystem/FilesystemOperations/Helpers/IFilesystemHelpers.cs
  src/Files.App/Filesystem/StorageHistory/StorageHistoryOperations.cs
  src/Files.App/Helpers/NavigationHelpers.cs
  src/Files.App/Helpers/RecycleBinHelpers.cs
  src/Files.App/ServicesImplementation/Settings/FoldersSettingsService.cs
  src/Files.App/Strings/en-US/Resources.resw
  src/Files.App/ViewModels/SettingsViewModels/FoldersViewModel.cs
  src/Files.App/Views/ColumnShellPage.xaml.cs
  src/Files.App/Views/ModernShellPage.xaml.cs
  src/Files.App/Views/SettingsPages/Folders.xaml
  src/Files.Backend/Services/Settings/IFoldersSettingsService.cs
  src/Files.Shared/Enums/DeleteConfirmationPolicy.cs
Labels: approved

#11154 Feature: Added support for changing groups direction
  src/Files.App/BaseLayout.cs
  src/Files.App/Helpers/ContextFlyoutItemHelper.cs
  src/Files.App/Helpers/ItemListDisplayHelpers/GroupingHelper.cs
  src/Files.App/Helpers/LayoutPreferences/LayoutPreferences.cs
  src/Files.App/ServicesImplementation/DateTimeFormatter/AbstractDateTimeFormatter.cs
  src/Files.App/ServicesImplementation/Settings/LayoutSettingsService.cs
  src/Files.App/UserControls/InnerNavigationToolbar.xaml
  src/Files.App/ViewModels/FolderSettingsViewModel.cs
  src/Files.App/ViewModels/ItemViewModel.cs
  src/Files.App/ViewModels/ToolbarViewModel.cs
  src/Files.Backend/Services/Settings/ILayoutSettingsService.cs
Labels: approved

#11220 Feature: Added settings for default order directions
  src/Files.App/Helpers/LayoutPreferences/LayoutPreferences.cs
  src/Files.App/ServicesImplementation/Settings/FoldersSettingsService.cs
  src/Files.App/ServicesImplementation/Settings/LayoutSettingsService.cs
  src/Files.App/Strings/en-US/Resources.resw
  src/Files.App/ViewModels/FolderSettingsViewModel.cs
  src/Files.App/ViewModels/ItemViewModel.cs
  src/Files.App/ViewModels/SettingsViewModels/FoldersViewModel.cs
  src/Files.App/Views/SettingsPages/Folders.xaml
  src/Files.Backend/Services/Settings/IFoldersSettingsService.cs
  src/Files.Backend/Services/Settings/ILayoutSettingsService.cs
Labels: approved

#11222 Fix: Fixed issue where archive files were incorrectly grouped by size
  src/Files.App/Helpers/ItemListDisplayHelpers/GroupingHelper.cs
  src/Files.App/ViewModels/ItemViewModel.cs
Labels: approved

#11225 Feature: Start a search when clicking tags in the details layout
  src/Files.App/Views/LayoutModes/DetailsLayoutBrowser.xaml
  src/Files.App/Views/LayoutModes/DetailsLayoutBrowser.xaml.cs
Labels: approved

#11191 Feature: Restart after applying update
  src/Files.App/ServicesImplementation/SideloadUpdateService.cs
Labels: approved

#11230 Fix: Fixed issue where option to hide details pane wasn't working
  src/Files.App/UserControls/Pane/PreviewPane.xaml
Labels: approved

#11231 Repo: Updated readme file
  README.md
Labels: approved

#11232 Fix: Fixed "NotAFolder" error when changing the language
  src/Files.App/App.xaml.cs
  src/Files.App/DataModels/NavigationControlItems/LocationItem.cs
  src/Files.App/Filesystem/Search/FolderSearch.cs
  src/Files.App/Helpers/CommonPaths.cs
  src/Files.App/Helpers/MultitaskingTabsHelpers.cs
  src/Files.App/Helpers/NavigationHelpers.cs
  src/Files.App/UserControls/SidebarControl.xaml.cs
  src/Files.App/ViewModels/ItemViewModel.cs
  src/Files.App/ViewModels/MainPageViewModel.cs
  src/Files.App/ViewModels/SettingsViewModels/PreferencesViewModel.cs
  src/Files.App/ViewModels/SidebarViewModel.cs
  src/Files.App/ViewModels/ToolbarViewModel.cs
  src/Files.App/Views/ColumnShellPage.xaml.cs
  src/Files.App/Views/MainPage.xaml.cs
  src/Files.App/Views/ModernShellPage.xaml.cs
  src/Files.App/Views/PaneHolderPage.xaml.cs
  src/Files.App/Views/WidgetsPage.xaml.cs
Labels: approved

#11237 Fix: Fixed selecting wrong items when creating or renaming an item
  src/Files.App/Views/LayoutModes/DetailsLayoutBrowser.xaml.cs
  src/Files.App/Views/LayoutModes/GridViewBrowser.xaml.cs
Labels: approved

#11240 Feature: Tweaked border brush on path and search box
  src/Files.App/UserControls/AddressToolbar.xaml
  src/Files.App/UserControls/SearchBox.xaml
Labels: approved

#11238 Feature: Add support for removing tag in the details layout
  src/Files.App/Views/LayoutModes/DetailsLayoutBrowser.xaml
  src/Files.App/Views/LayoutModes/DetailsLayoutBrowser.xaml.cs
Labels: needs-review

#11245 Fix: Fixed issue where BaseContextFlyout was not closed after selecting an item
  src/Files.App/BaseLayout.cs
Labels: approved

#11248 Fix: Fixed issue where the right click menu didn't load properly in folders that have archive extensions
  src/Files.App/Filesystem/StorageItems/ZipStorageFolder.cs
Labels: approved

#11204 Feature: Add shell context menu for widgets
  src/Files.App/Filesystem/RecentItem.cs
  src/Files.App/Helpers/ShellContextMenuHelper.cs
  src/Files.App/ServicesImplementation/QuickAccessService.cs
  src/Files.App/UserControls/SidebarControl.xaml.cs
  src/Files.App/UserControls/Widgets/DrivesWidget.xaml
  src/Files.App/UserControls/Widgets/DrivesWidget.xaml.cs
  src/Files.App/UserControls/Widgets/FileTagsWidget.xaml
  src/Files.App/UserControls/Widgets/FileTagsWidget.xaml.cs
  src/Files.App/UserControls/Widgets/HomePageWidget.cs
  src/Files.App/UserControls/Widgets/QuickAccessWidget.xaml
  src/Files.App/UserControls/Widgets/QuickAccessWidget.xaml.cs
  src/Files.App/UserControls/Widgets/RecentFilesWidget.xaml
  src/Files.App/UserControls/Widgets/RecentFilesWidget.xaml.cs
  src/Files.App/UserControls/Widgets/WidgetCardItem.cs
  src/Files.Backend/Services/IQuickAccessService.cs
Labels: needs-review

#11253 Fix: Fixed double separator showing up when opening context menu for files
  src/Files.App/BaseLayout.cs
Labels: approved

#11262 Fix: Fixed icon in preview build
  src/Files.App/App.xaml.cs
Labels: approved

#11243 Feature: Disable show more options menu item until shell items are loaded
  src/Files.App/BaseLayout.cs
  src/Files.App/Helpers/ContextFlyoutItemHelper.cs
  src/Files.App/Helpers/ShellContextMenuHelper.cs
  src/Files.App/Strings/en-US/Resources.resw
  src/Files.App/UserControls/SidebarControl.xaml.cs
  src/Files.App/UserControls/Widgets/DrivesWidget.xaml.cs
  src/Files.App/UserControls/Widgets/QuickAccessWidget.xaml.cs
  src/Files.App/UserControls/Widgets/RecentFilesWidget.xaml.cs
Labels: needs-review

#10782 Code Quality: Refactored AdaptiveLayoutHelpers
  src/Files.App/Helpers/AdaptiveLayoutHelpers.cs
  src/Files.App/ViewModels/ItemViewModel.cs
  src/Files.App/Views/ModernShellPage.xaml.cs
Labels: needs-review

#11276 Fix: Fixed CI AppCenter secret
  builds/azure-pipelines-release.yml
  src/Files.App/App.xaml.cs
Labels: approved

#11285 Feature: Added support for hiding open in new tab/window options
  builds/azure-pipelines.yml
  src/Files.App/BaseLayout.cs
  src/Files.App/Helpers/ContextFlyoutItemHelper.cs
  src/Files.App/ServicesImplementation/Settings/AppearanceSettingsService.cs
  src/Files.App/Strings/en-US/Resources.resw
  src/Files.App/UserControls/SidebarControl.xaml.cs
  src/Files.App/UserControls/Widgets/DrivesWidget.xaml.cs
  src/Files.App/UserControls/Widgets/QuickAccessWidget.xaml.cs
  src/Files.App/ViewModels/SettingsViewModels/AppearanceViewModel.cs
  src/Files.App/Views/SettingsPages/Appearance.xaml
  src/Files.Backend/Services/Settings/IAppearanceSettingsService.cs
Labels: approved

#11286 Feature: Apply app theme to settings dialog
  src/Files.App/Dialogs/SettingsDialog.xaml
Labels: approved

#11027 Fix: Fixed issue with resizing the status column
  src/Files.App/Shell/Win32Shell.cs
  src/Files.App/ViewModels/ColumnsViewModel.cs
Labels: approved

#11301 Fix: Fixed context menu hang in recent files and other widgets
  src/Files.App/UserControls/Widgets/HomePageWidget.cs
  src/Files.App/UserControls/Widgets/RecentFilesWidget.xaml.cs
Labels: approved

#11302 Feature: Removed sidebar toggles from settings dialog
  src/Files.App/ViewModels/SettingsViewModels/PreferencesViewModel.cs
  src/Files.App/Views/SettingsPages/Preferences.xaml
Labels: approved

#11281 Feature: Added shortcut to open Windows Terminal as administrator
  src/Files.App/Views/ColumnShellPage.xaml.cs
  src/Files.App/Views/ModernShellPage.xaml.cs
Labels: approved

#11310 Fix: Fixed closing app when the item flyout is open to hang
  src/Files.App/App.xaml.cs
  src/Files.App/BaseLayout.cs
  src/Files.App/UserControls/SidebarControl.xaml.cs
  src/Files.App/UserControls/Widgets/FileTagsWidget.xaml.cs
  src/Files.App/UserControls/Widgets/HomePageWidget.cs
  src/Files.App/UserControls/Widgets/RecentFilesWidget.xaml.cs
Labels: approved

#11034 Code Quality: Shell page refactoring
  src/Files.App/Views/BaseShellPage.cs
  src/Files.App/Views/ColumnShellPage.xaml
  src/Files.App/Views/ColumnShellPage.xaml.cs
  src/Files.App/Views/ModernShellPage.xaml
  src/Files.App/Views/ModernShellPage.xaml.cs
Labels: needs-review

#11313 Feature: Updated color icons
  src/Files.App/Assets/Custom Glyphs/Colored-Icons.ttf
  src/Files.App/Assets/Custom Glyphs/Colored_Icons.sfd
  src/Files.App/Helpers/ContextFlyoutItemHelper.cs
  src/Files.App/UserControls/ColoredIcon.xaml
  src/Files.App/UserControls/ColoredIcon.xaml.cs
  src/Files.App/UserControls/InnerNavigationToolbar.xaml
  src/Files.App/ViewModels/ContextMenuFlyoutItemViewModel.cs
Labels: approved

#11309 Fix: Remove deleted tags from items
  src/Files.App/ServicesImplementation/Settings/FileTagsSettingsService.cs
  src/Files.App/ViewModels/ItemViewModel.cs
  src/Files.App/Views/LayoutModes/DetailsLayoutBrowser.xaml.cs
  src/Files.App/Views/SettingsPages/Advanced.xaml.cs
Labels: approved

#11316 Fix: Fixed settings background in dark mode
  src/Files.App/App.xaml
  src/Files.App/Dialogs/SettingsDialog.xaml
Labels: approved

#11306 Feature: Support for reordering tags
  src/Files.App/ServicesImplementation/Settings/FileTagsSettingsService.cs
  src/Files.App/ViewModels/SettingsViewModels/AdvancedViewModel.cs
  src/Files.App/Views/SettingsPages/Advanced.xaml
  src/Files.App/Views/SettingsPages/Advanced.xaml.cs
  tests/Files.InteractionTests/Tests/FolderTests.cs
Labels: approved

#11325 Fix: Fixed showOpenWithMenu not working
  src/Files.App/Helpers/ShellContextMenuHelper.cs
Labels: approved

#11304 Feature: Move open with to main menu when right clicking recent files
  src/Files.App/Helpers/ShellContextMenuHelper.cs
  src/Files.App/UserControls/Widgets/RecentFilesWidget.xaml.cs
Labels: approved

#11328 Fix: Fixed issue with tab icon not loading properly
  src/Files.App/Assets/FilesOpenDialog/FilesLauncher.exe
  src/Files.App/UserControls/MultitaskingControl/HorizontalMultitaskingControl.xaml
  src/Files.App/UserControls/MultitaskingControl/HorizontalMultitaskingControl.xaml.cs
Labels: approved

#11327 RichCommand: Base and commands ShowFileExtensions/ShowHiddenItems
  src/Files.App/Actions/IAction.cs
  src/Files.App/Actions/IToggleAction.cs
  src/Files.App/Actions/Show/ShowFileExtensionsAction.cs
  src/Files.App/Actions/Show/ShowHiddenItemsAction.cs
  src/Files.App/App.xaml.cs
  src/Files.App/Commands/CommandCodes.cs
  src/Files.App/Commands/IRichCommand.cs
  src/Files.App/Commands/Manager/CommandManager.cs
  src/Files.App/Commands/Manager/ICommandManager.cs
  src/Files.App/Strings/en-US/Resources.resw
  src/Files.App/UserControls/InnerNavigationToolbar.xaml
  src/Files.App/UserControls/InnerNavigationToolbar.xaml.cs
Labels: needs-review

#11193 Fix: Refactor smb credentials dialog logic
  src/Files.App/Helpers/NavigationHelpers.cs
  src/Files.App/ViewModels/ItemViewModel.cs
  src/Files.App/ViewModels/ToolbarViewModel.cs
Labels: needs-review

#11335 Fix: Fixed issue where online-only files deleted before confirmation
  src/Files.App/Helpers/FileOperationsHelpers.cs
Labels: approved

#11346 Enforce tabs for Xaml in EditorConfig and Xaml Styler
  .editorconfig
  Settings.XamlStyler
Labels: approved

#11329 Feature: Show the "send to" option in the main menu
  src/Files.App/BaseLayout.cs
  src/Files.App/Helpers/ContextFlyoutItemHelper.cs
  src/Files.App/Helpers/ShellContextMenuHelper.cs
  src/Files.App/Strings/en-US/Resources.resw
  src/Files.App/UserControls/SidebarControl.xaml.cs
  src/Files.App/UserControls/Widgets/DrivesWidget.xaml.cs
  src/Files.App/UserControls/Widgets/QuickAccessWidget.xaml.cs
  src/Files.App/UserControls/Widgets/RecentFilesWidget.xaml.cs
Labels: approved

#11344 Feature: Improve Column View
  src/Files.App/Views/LayoutModes/ColumnViewBase.xaml.cs
  src/Files.App/Views/LayoutModes/ColumnViewBrowser.xaml.cs
Labels: approved

#11347 Fix: Fixed crash that would occur after changing background color
  src/Files.App/ViewModels/SettingsViewModels/AppearanceViewModel.cs
Labels: approved

#11348 Fix: Fixed issue where compatibility settings weren't working
  src/Files.App/ViewModels/Properties/CompatibilityProperties.cs
  src/Files.Shared/CompatibilityOptions.cs
Labels: approved

#11349 Fix: Fixed issue where it didn't work to change the library default directory
  src/Files.App/Filesystem/LibraryManager.cs
  src/Files.App/Views/Pages/PropertiesLibrary.xaml
  src/Files.App/Views/Pages/PropertiesLibrary.xaml.cs
Labels: approved

#11351 Fix: A small fix to Improve Column View
  src/Files.App/Views/LayoutModes/ColumnViewBrowser.xaml.cs
Labels: approved

#11365 Feature: Display "Play all" button on toolbar when selecting multiple media files.
  src/Files.App/Interacts/BaseLayoutCommandImplementationModel.cs
  src/Files.App/Interacts/BaseLayoutCommandsViewModel.cs
  src/Files.App/Interacts/IBaseLayoutCommandImplementationModel.cs
  src/Files.App/Strings/en-US/Resources.resw
  src/Files.App/UserControls/InnerNavigationToolbar.xaml
  src/Files.App/ViewModels/ToolbarViewModel.cs
  src/Files.App/Views/BaseShellPage.cs
  src/Files.Backend/Helpers/FileExtensionHelpers.cs
Labels: approved

#11374 Feature: Show rotate options in main context menu
  src/Files.App/Helpers/ContextFlyoutItemHelper.cs
  src/Files.App/Helpers/ShellContextMenuHelper.cs
Labels: approved

#11357 Codebase: Join both context menus in BaseLayout
  src/Files.App/BaseLayout.cs
  src/Files.App/Helpers/ContextFlyoutItemHelper.cs
Labels: approved

#11358 Feature: Add flyout to confirm tag deletion
  src/Files.App/Strings/en-US/Resources.resw
  src/Files.App/Views/SettingsPages/Tags.xaml
  src/Files.App/Views/SettingsPages/Tags.xaml.cs
Labels: approved

#11367 RichCommand: HotKeys + Open/FullScreen
  src/Files.App/Actions/Global/OpenHelpAction.cs
  src/Files.App/Actions/Global/ToggleFullScreenAction.cs
  src/Files.App/Actions/IAction.cs
  src/Files.App/Actions/Show/ToggleShowFileExtensionsAction.cs
  src/Files.App/Actions/Show/ToggleShowHiddenItemsAction.cs
  src/Files.App/Commands/CommandCodes.cs
  src/Files.App/Commands/HotKey.cs
  src/Files.App/Commands/IRichCommand.cs
  src/Files.App/Commands/Manager/CommandManager.cs
  src/Files.App/Commands/Manager/HotKeyChangedEventArgs.cs
  src/Files.App/Commands/Manager/ICommandManager.cs
  src/Files.App/Strings/en-US/Resources.resw
  src/Files.App/UserControls/InnerNavigationToolbar.xaml
  src/Files.App/Views/ColumnShellPage.xaml
  src/Files.App/Views/ColumnShellPage.xaml.cs
  src/Files.App/Views/MainPage.xaml
  src/Files.App/Views/MainPage.xaml.cs
  src/Files.App/Views/ModernShellPage.xaml
  src/Files.App/Views/ModernShellPage.xaml.cs
Labels: needs-review

#11386 Fix: Fixed minimum menu width for recent files widget
  src/Files.App/UserControls/Widgets/RecentFilesWidget.xaml.cs
Labels: approved

#11387 Fix: Fixed issue where the sidebar scrollbar wasn't clickable
  src/Files.App/UserControls/SidebarControl.xaml
Labels: approved

#11388 Fix: Fixed issue where the preview pane had the wrong cursor when resizing
  src/Files.App/ResourceDictionaries/DefaultGridSplitterStyle.xaml
  src/Files.App/Views/MainPage.xaml
  src/Files.App/Views/MainPage.xaml.cs
Labels: approved

#11390 Fix: Added "Apply this action to all conflicting items" to Resouces.resw
  src/Files.App/Dialogs/FilesystemOperationDialog.xaml
  src/Files.App/Strings/en-US/Resources.resw
Labels: approved

#11392 Fixed: Right clicking empty space doesn't show context menu
  src/Files.App/Helpers/ContextFlyoutItemHelper.cs
Labels: approved

#11393 Fix: Fixed typo in English resources
  src/Files.App/Strings/en-US/Resources.resw
Labels: approved

#11399 Feature: Remember previously selected option in conflicts dialog
  src/Files.App/Dialogs/FilesystemOperationDialog.xaml
  src/Files.App/Dialogs/FilesystemOperationDialog.xaml.cs
  src/Files.App/ServicesImplementation/Settings/PreferencesSettingsService.cs
  src/Files.App/ValueConverters/EnumConverters/ConflictResolveOptionToIndexConverter.cs
  src/Files.Backend/Services/Settings/IPreferencesSettingsService.cs
  src/Files.Backend/ViewModels/Dialogs/FileSystemDialog/FileSystemDialogConflictItemViewModel.cs
  src/Files.Backend/ViewModels/Dialogs/FileSystemDialog/FileSystemDialogViewModel.cs
Labels: approved

#11364 Feature: Moved "format drive" to main context menu
  src/Files.App/DataModels/NavigationControlItems/DriveItem.cs
  src/Files.App/DataModels/NavigationControlItems/INavigationControlItem.cs
  src/Files.App/Filesystem/ListedItem.cs
  src/Files.App/Helpers/ContextFlyoutItemHelper.cs
  src/Files.App/Helpers/ShellContextMenuHelper.cs
  src/Files.App/Interacts/BaseLayoutCommandImplementationModel.cs
  src/Files.App/Interacts/BaseLayoutCommandsViewModel.cs
  src/Files.App/Interacts/IBaseLayoutCommandImplementationModel.cs
  src/Files.App/Strings/en-US/Resources.resw
  src/Files.App/UserControls/SidebarControl.xaml.cs
  src/Files.App/UserControls/Widgets/DrivesWidget.xaml.cs
Labels: approved

#11402 Feature: Added media file resolution to the details pane
  src/Files.App/Resources/PreviewPanePropertiesInformation.json
  src/Files.App/Strings/en-US/Resources.resw
Labels: approved

#11376 Feature: Opacity Icon
  src/Files.App/Files.App.csproj
  src/Files.App/ResourceDictionaries/PathIcons.xaml
  src/Files.App/UserControls/InnerNavigationToolbar.xaml
  src/Files.App/UserControls/OpacityIcon.xaml
  src/Files.App/UserControls/OpacityIcon.xaml.cs
Labels: approved

#11411 Fix: Catch COMException wherever it occurs in shell extension loading
  src/Files.App/Shell/ContextMenu.cs
Labels: approved

#11414 Fix: Fixed network folder error with phones
  src/Files.App/ViewModels/ItemViewModel.cs
Labels: approved

#11415 RichCommand: Glyph + ContextMenu + EmptyRecycleBinAction
  src/Files.App/Actions/FileSystem/EmptyRecycleBinAction.cs
  src/Files.App/Actions/IAction.cs
  src/Files.App/Commands/CommandCodes.cs
  src/Files.App/Commands/HotKey.cs
  src/Files.App/Commands/IRichCommand.cs
  src/Files.App/Commands/Manager/CommandManager.cs
  src/Files.App/Commands/Manager/ICommandManager.cs
  src/Files.App/Commands/RichGlyph.cs
  src/Files.App/Helpers/ContextFlyoutItemHelper.cs
  src/Files.App/Interacts/BaseLayoutCommandImplementationModel.cs
  src/Files.App/Interacts/BaseLayoutCommandsViewModel.cs
  src/Files.App/Interacts/IBaseLayoutCommandImplementationModel.cs
  src/Files.App/Strings/en-US/Resources.resw
  src/Files.App/UserControls/InnerNavigationToolbar.xaml
  src/Files.App/UserControls/InnerNavigationToolbar.xaml.cs
  src/Files.App/UserControls/SidebarControl.xaml.cs
  src/Files.App/ViewModels/ContextMenuFlyoutItemViewModel.cs
  src/Files.App/ViewModels/SidebarViewModel.cs
  src/Files.App/ViewModels/ToolbarViewModel.cs
  src/Files.App/Views/BaseShellPage.cs
  src/Files.App/Views/MainPage.xaml
Labels: approved

#11421 Merge CustomFolderIcons with Customization properties page
  src/Files.App/ViewModels/Properties/CustomizationViewModel.cs
  src/Files.App/Views/CustomFolderIcons.xaml
  src/Files.App/Views/CustomFolderIcons.xaml.cs
  src/Files.App/Views/Pages/PropertiesCustomization.xaml
  src/Files.App/Views/Pages/PropertiesCustomization.xaml.cs
Labels: approved

#11433 Fix: Fixed issue where the properties window opened from widgets was hidden behind
  src/Files.App/UserControls/Widgets/DrivesWidget.xaml.cs
  src/Files.App/UserControls/Widgets/HomePageWidget.cs
  src/Files.App/UserControls/Widgets/QuickAccessWidget.xaml.cs
Labels: approved

#11441 Fix: Delete duplicate language
  src/Files.App/Strings/lt-LT/Resources.resw
Labels: approved

#11444 Fix: Fixed issue with open terminal as admin not working
  src/Files.App/Views/BaseShellPage.cs
Labels: approved

#11427 Feature: Vertical NavigationView in the properties window
  src/Files.App/App.xaml
  src/Files.App/Helpers/FilePropertiesHelpers.cs
  src/Files.App/ResourceDictionaries/NavigationViewStoreStyle.xaml
  src/Files.App/ResourceDictionaries/PathIcons.xaml
  src/Files.App/Strings/en-US/Resources.resw
  src/Files.App/UserControls/AddressToolbar.xaml
  src/Files.App/UserControls/InnerNavigationToolbar.xaml
  src/Files.App/Views/Pages/Properties.xaml
  src/Files.App/Views/Pages/Properties.xaml.cs
  src/Files.App/Views/Pages/PropertiesCompatibility.xaml
  src/Files.App/Views/Pages/PropertiesCustomization.xaml
  src/Files.App/Views/Pages/PropertiesCustomization.xaml.cs
  src/Files.App/Views/Pages/PropertiesDetails.xaml
  src/Files.App/Views/Pages/PropertiesGeneral.xaml
  src/Files.App/Views/Pages/PropertiesLibrary.xaml
  src/Files.App/Views/Pages/PropertiesSecurity.xaml
  src/Files.App/Views/Pages/PropertiesSecurityAdvanced.xaml
  src/Files.App/Views/Pages/PropertiesShortcut.xaml
Labels: approved

#11469 Code Quality: Deleted duplicate string resources
  src/Files.App/DataModels/NavigationControlItems/DriveItem.cs
  src/Files.App/Dialogs/CredentialDialog.xaml
  src/Files.App/Dialogs/DecompressArchiveDialog.xaml
  src/Files.App/Dialogs/FilesystemOperationDialog.xaml
  src/Files.App/Filesystem/FilesystemOperations/Helpers/FilesystemHelpers.cs
  src/Files.App/Filesystem/LibraryManager.cs
  src/Files.App/Filesystem/ListedItem.cs
  src/Files.App/Filesystem/StorageEnumerators/Win32StorageEnumerator.cs
  src/Files.App/Filesystem/StorageItems/FtpStorageFile.cs
  src/Files.App/Filesystem/StorageItems/NativeStorageFile.cs
  src/Files.App/Filesystem/StorageItems/ZipStorageFile.cs
  src/Files.App/Helpers/ContextFlyoutItemHelper.cs
  src/Files.App/Helpers/DynamicDialogFactory.cs
  src/Files.App/Helpers/FilePropertiesHelpers.cs
  src/Files.App/ServicesImplementation/Settings/FileTagsSettingsService.cs
  src/Files.App/Strings/en-US/Resources.resw
  src/Files.App/UserControls/AddressToolbar.xaml
  src/Files.App/UserControls/InnerNavigationToolbar.xaml
  src/Files.App/UserControls/SearchBox.xaml
  src/Files.App/UserControls/SidebarControl.xaml.cs
  src/Files.App/UserControls/Widgets/BundlesWidget.xaml
  src/Files.App/UserControls/Widgets/DrivesWidget.xaml
  src/Files.App/UserControls/Widgets/DrivesWidget.xaml.cs
  src/Files.App/UserControls/Widgets/QuickAccessWidget.xaml.cs
  src/Files.App/UserControls/Widgets/RecentFilesWidget.xaml.cs
  src/Files.App/ViewModels/Properties/FileProperties.cs
  src/Files.App/ViewModels/Widgets/Bundles/BundleContainerViewModel.cs
  src/Files.App/ViewModels/Widgets/Bundles/BundlesViewModel.cs
  src/Files.App/Views/LayoutModes/ColumnViewBase.xaml
  src/Files.App/Views/LayoutModes/DetailsLayoutBrowser.xaml
  src/Files.App/Views/LayoutModes/GridViewBrowser.xaml
  src/Files.App/Views/MainPage.xaml
  src/Files.App/Views/Pages/Properties.xaml
  src/Files.App/Views/Pages/PropertiesDetails.xaml
  src/Files.App/Views/Pages/PropertiesGeneral.xaml
  src/Files.App/Views/Pages/PropertiesLibrary.xaml
  src/Files.App/Views/Pages/PropertiesSecurityAdvanced.xaml
  src/Files.App/Views/SettingsPages/Folders.xaml
  src/Files.App/Views/SettingsPages/Preferences.xaml
Labels: approved

#11460 Rename properties page namespaces and classes
  src/Files.App/Helpers/FilePropertiesHelpers.cs
  src/Files.App/ViewModels/Properties/BasePropertiesPage.cs
  src/Files.App/ViewModels/Properties/CompatibilityViewModel.cs
  src/Files.App/ViewModels/Properties/SecurityViewModel.cs
  src/Files.App/Views/Properties/CompatibilityPage.xaml
  src/Files.App/Views/Properties/CompatibilityPage.xaml.cs
  src/Files.App/Views/Properties/CustomizationPage.xaml
  src/Files.App/Views/Properties/CustomizationPage.xaml.cs
  src/Files.App/Views/Properties/DetailsPage.xaml
  src/Files.App/Views/Properties/DetailsPage.xaml.cs
  src/Files.App/Views/Properties/GeneralPage.xaml
  src/Files.App/Views/Properties/GeneralPage.xaml.cs
  src/Files.App/Views/Properties/LibraryPage.xaml
  src/Files.App/Views/Properties/LibraryPage.xaml.cs
  src/Files.App/Views/Properties/MainPropertiesPage.xaml
  src/Files.App/Views/Properties/MainPropertiesPage.xaml.cs
  src/Files.App/Views/Properties/SecurityAdvancedPage.xaml
  src/Files.App/Views/Properties/SecurityAdvancedPage.xaml.cs
  src/Files.App/Views/Properties/SecurityPage.xaml
  src/Files.App/Views/Properties/SecurityPage.xaml.cs
  src/Files.App/Views/Properties/ShortcutPage.xaml
  src/Files.App/Views/Properties/ShortcutPage.xaml.cs
Labels: approved

#11477 Codebase: Refactor QuickAccessWidget.xaml.cs
  src/Files.App/UserControls/Widgets/QuickAccessWidget.xaml.cs
Labels: approved

#11480 Feature: Context menu icons
  src/Files.App/Helpers/ContextFlyoutItemHelper.cs
  src/Files.App/Helpers/ItemModelListToContextFlyoutHelper.cs
  src/Files.App/ResourceDictionaries/PathIcons.xaml
  src/Files.App/UserControls/InnerNavigationToolbar.xaml
  src/Files.App/ViewModels/ContextMenuFlyoutItemViewModel.cs
Labels: approved

#11468 Feature: Improve tags context menu
  src/Files.App/Helpers/ContextFlyoutItemHelper.cs
  src/Files.App/Helpers/ShellContextMenuHelper.cs
  src/Files.App/UserControls/SidebarControl.xaml.cs
  src/Files.App/UserControls/Widgets/DrivesWidget.xaml.cs
  src/Files.App/UserControls/Widgets/FileTagsWidget.xaml
  src/Files.App/UserControls/Widgets/FileTagsWidget.xaml.cs
  src/Files.App/UserControls/Widgets/HomePageWidget.cs
  src/Files.App/UserControls/Widgets/QuickAccessWidget.xaml.cs
  src/Files.App/UserControls/Widgets/RecentFilesWidget.xaml.cs
  src/Files.App/UserControls/Widgets/WidgetCardItem.cs
  src/Files.App/ViewModels/Widgets/FileTagsContainerViewModel.cs
  src/Files.App/ViewModels/Widgets/FileTagsItemViewModel.cs
  src/Files.App/ViewModels/Widgets/FileTagsWidgetViewModel.cs
  src/Files.App/Views/WidgetsPage.xaml.cs
Labels: approved

#11484 Feature: Update color icons
  src/Files.App/BaseLayout.cs
  src/Files.App/Helpers/ContextFlyoutItemHelper.cs
  src/Files.App/ResourceDictionaries/PathIcons.xaml
  src/Files.App/UserControls/InnerNavigationToolbar.xaml
  src/Files.App/UserControls/SidebarControl.xaml.cs
  src/Files.App/UserControls/Widgets/DrivesWidget.xaml.cs
  src/Files.App/UserControls/Widgets/FileTagsWidget.xaml.cs
  src/Files.App/UserControls/Widgets/QuickAccessWidget.xaml.cs
Labels: approved

#11492 Feature: Add RichCommand for pinning and unpinning items
  src/Files.App/Actions/Favorites/PinItemAction.cs
  src/Files.App/Actions/Favorites/UnpinItemAction.cs
  src/Files.App/Commands/CommandCodes.cs
  src/Files.App/Commands/Manager/CommandManager.cs
  src/Files.App/Commands/Manager/ICommandManager.cs
  src/Files.App/Helpers/ContextFlyoutItemHelper.cs
  src/Files.App/Interacts/BaseLayoutCommandImplementationModel.cs
  src/Files.App/Interacts/BaseLayoutCommandsViewModel.cs
  src/Files.App/Interacts/IBaseLayoutCommandImplementationModel.cs
Labels: approved

#11493 Feature: Implement more RichCommands
  src/Files.App/Actions/FileSystem/CreateFolderAction.cs
  src/Files.App/Actions/FileSystem/CreateShortcutAction.cs
  src/Files.App/Actions/FileSystem/CreateShortcutFromDialogAction.cs
  src/Files.App/Actions/Start/PinToStartAction.cs
  src/Files.App/Actions/Start/UnpinFromStartAction.cs
  src/Files.App/Commands/CommandCodes.cs
  src/Files.App/Commands/Manager/CommandManager.cs
  src/Files.App/Commands/Manager/ICommandManager.cs
  src/Files.App/Helpers/ContextFlyoutItemHelper.cs
  src/Files.App/Interacts/BaseLayoutCommandImplementationModel.cs
  src/Files.App/Interacts/BaseLayoutCommandsViewModel.cs
  src/Files.App/Interacts/IBaseLayoutCommandImplementationModel.cs
Labels: approved

#11495 Fix: Fixed pin/unpin command when no items are selected
  src/Files.App/Actions/Favorites/PinItemAction.cs
  src/Files.App/Actions/Favorites/UnpinItemAction.cs
Labels: approved

#11496 Feature: Replaced old icons
  src/Files.App/Dialogs/SettingsDialog.xaml
  src/Files.App/Helpers/ContextFlyoutItemHelper.cs
  src/Files.App/UserControls/InnerNavigationToolbar.xaml
  src/Files.App/UserControls/MultitaskingControl/HorizontalMultitaskingControl.xaml
  src/Files.App/UserControls/SidebarControl.xaml.cs
  src/Files.App/UserControls/Widgets/BundlesWidget.xaml
  src/Files.App/UserControls/Widgets/DrivesWidget.xaml.cs
  src/Files.App/Views/LayoutModes/ColumnViewBase.xaml
  src/Files.App/Views/LayoutModes/DetailsLayoutBrowser.xaml
  src/Files.App/Views/LayoutModes/GridViewBrowser.xaml
  src/Files.App/Views/Properties/MainPropertiesPage.xaml.cs
  src/Files.App/Views/SettingsPages/Preferences.xaml
Labels: approved

#11498 Fix: Fixed highlights flickering after closing the properties window
  src/Files.App/Helpers/FilePropertiesHelpers.cs
  src/Files.App/Views/Properties/MainPropertiesPage.xaml.cs
  src/Files.App/Views/Properties/SecurityAdvancedPage.xaml.cs
  src/Files.App/Views/Properties/SecurityPage.xaml.cs
Labels: approved

#11437 Fix: Fixed "Size All Columns to Fit" not working properly
  src/Files.App/Views/LayoutModes/DetailsLayoutBrowser.xaml
  src/Files.App/Views/LayoutModes/DetailsLayoutBrowser.xaml.cs
Labels: changes requested

#11504 Feature: Add Copy, Cut and Delete RichCommands
  src/Files.App/Actions/FileSystem/CopyItemAction.cs
  src/Files.App/Actions/FileSystem/CutItemAction.cs
  src/Files.App/Actions/FileSystem/DeleteItemAction.cs
  src/Files.App/Commands/CommandCodes.cs
  src/Files.App/Commands/Manager/CommandManager.cs
  src/Files.App/Commands/Manager/ICommandManager.cs
  src/Files.App/Helpers/ContextFlyoutItemHelper.cs
  src/Files.App/Interacts/BaseLayoutCommandImplementationModel.cs
  src/Files.App/Interacts/BaseLayoutCommandsViewModel.cs
  src/Files.App/Interacts/IBaseLayoutCommandImplementationModel.cs
  src/Files.App/Views/BaseShellPage.cs
Labels: approved
