Repository files-community/Files, pull requests merged in 2024-10, with the labels that each got.

#16277 Fix: Fixed an issue when navigating the sidebar with the tab key
  src/Files.App/UserControls/Sidebar/SidebarItem.cs
Labels: ready to merge

#16302 Fix: Fixed an issue where sorting preferences didn't save when changed in the columns layout
  src/Files.App/Views/Shells/BaseShellPage.cs
  src/Files.App/Views/Shells/ColumnShellPage.xaml.cs
  src/Files.App/Views/Shells/ModernShellPage.xaml.cs
Labels: ready to merge

#16305 Fix: Fixed NullReferenceException in BaseTransferItemAction.ExecuteTransferAsync
  src/Files.App/Actions/FileSystem/Transfer/BaseTransferItemAction.cs
Labels: ready to merge

#16310 GitHub: Retry integration tests when failed
  .github/workflows/ci.yml
Labels: ready to merge

#16311 Code Quality: Use lock statements in FileLogger
  src/Files.Shared/Utils/Logger/FileLogger.cs
Labels: ready to merge

#16316 GitHub: Added default titles to all issue templates
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/code_quality_issue.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
Labels: ready to merge

#16318 Feature: Enabled support for inputting custom icon path
  src/Files.App/ViewModels/Properties/CustomizationViewModel.cs
  src/Files.App/Views/Properties/CustomizationPage.xaml
Labels: ready to merge

#16322 Fix: Fixed window placement
  src/Files.App/MainWindow.xaml.cs
Labels: ready to merge

#16317 Feature: Improved UX for the "Create new item" dialog
  src/Files.App/Helpers/Dialog/DynamicDialogFactory.cs
  src/Files.App/Helpers/UI/UIFilesystemHelpers.cs
  src/Files.App/Strings/en-US/Resources.resw
  src/Files.App/ViewModels/Dialogs/CreateItemDialogViewModel.cs
Labels: ready to merge

#16325 Code Quality: Lowercase item type
  src/Files.App/Helpers/UI/UIFilesystemHelpers.cs
Labels: ready to merge

#16321 Feature: Added Files icon to the process in Windows
  src/Files.App/Files.App.csproj
Labels: needs - code review

#16331 Code Quality: Fixed a GC hole in OpenClassicPropertiesAction
  src/Files.App/Actions/Open/OpenClassicPropertiesAction.cs
Labels: needs - code review

#16361 GitHub: Make C++ headers actually detect as C++
  .gitattributes
Labels: needs - code review

#16355 GitHub: Fixed XAML formatting checker
  .github/workflows/ci.yml
  .github/workflows/format-xaml.yml
Labels: changes requested

#15948 Code Quality: ThemedIcon, Changed IsToggle to ToggleBehavior
  src/Files.App.Controls/ThemedIcon/Data/ThemedIconColorType.cs
  src/Files.App.Controls/ThemedIcon/Data/ThemedIconLayerType.cs
  src/Files.App.Controls/ThemedIcon/Data/ThemedIconLayers.cs
  src/Files.App.Controls/ThemedIcon/Data/ThemedIconToggleBehaviors.cs
  src/Files.App.Controls/ThemedIcon/Data/ThemedIconTypes.cs
  src/Files.App.Controls/ThemedIcon/ThemedIcon.Consts.cs
  src/Files.App.Controls/ThemedIcon/ThemedIcon.Owner.cs
  src/Files.App.Controls/ThemedIcon/ThemedIcon.Properties.cs
  src/Files.App.Controls/ThemedIcon/ThemedIcon.ThemeResources.xaml
  src/Files.App.Controls/ThemedIcon/ThemedIcon.cs
  src/Files.App.Controls/ThemedIcon/ThemedIcon.xaml
  src/Files.App.Controls/ThemedIcon/ThemedIconColorType.cs
  src/Files.App.Controls/ThemedIcon/ThemedIconLayer/ThemedIconLayer.Consts.cs
  src/Files.App.Controls/ThemedIcon/ThemedIconLayer/ThemedIconLayer.Properties.cs
  src/Files.App.Controls/ThemedIcon/ThemedIconLayer/ThemedIconLayer.cs
  src/Files.App.Controls/ThemedIcon/ThemedIconLayer/ThemedIconLayerType.cs
  src/Files.App.Controls/ThemedIcon/ThemedIconLayer/ThemedIconLayers.cs
  src/Files.App.Controls/ThemedIcon/ThemedIconTypes.cs
  src/Files.App.Controls/Themes/Generic.xaml
  tests/Files.App.UITests/Views/ThemedIconPage.xaml
  tests/Files.App.UITests/Views/ThemedIconPage.xaml.cs
Labels: needs - code review

#16405 Fix: Fixed context menu placement on the home page
  src/Files.App/ViewModels/UserControls/Widgets/BaseWidgetViewModel.cs
Labels: ready to merge

#16400 GitHub: Introduce GHA CD to Microsoft Store
  .github/workflows/cd-store.yml
Labels: ready to merge

#16409 Feature: Save archive creation settings
  src/Files.App/Data/Contracts/IGeneralSettingsService.cs
  src/Files.App/Dialogs/CreateArchiveDialog.xaml.cs
  src/Files.App/Services/Settings/GeneralSettingsService.cs
Labels: needs - code review
