Repository files-community/Files, pull requests merged in 2024-04, with the labels that each got.

#15096 Fix: Fixed issue of overlapping brushes leaving gap in the Columns View
  src/Files.App/Helpers/Layout/LayoutSizeKindHelper.cs
  src/Files.App/Views/Layouts/ColumnLayoutPage.xaml
  src/Files.App/Views/Layouts/ColumnLayoutPage.xaml.cs
Labels: approved

#15030 GitHub: Added ps1 scripts to simplify CI/CD
  .github/workflows/cd-preview.yml
  .github/workflows/cd-stable.yml
  scripts/Configure-AppxManifest.ps1
Labels: approved

#15106 Feature: Improved the display of keyboard shortcuts in the Command Palette
  src/Files.App/Data/Commands/HotKey/HotKey.cs
  src/Files.App/Data/Items/NavigationBarSuggestionItem.cs
  src/Files.App/UserControls/AddressToolbar.xaml
  src/Files.App/UserControls/KeyboardShortcut/KeyboardShortcut.Properties.cs
  src/Files.App/UserControls/KeyboardShortcut/KeyboardShortcut.cs
  src/Files.App/UserControls/KeyboardShortcut/KeyboardShortcut.xaml
  src/Files.App/UserControls/KeyboardShortcut/KeyboardShortcutItem.Properties.cs
  src/Files.App/UserControls/KeyboardShortcut/KeyboardShortcutItem.cs
  src/Files.App/UserControls/KeyboardShortcut/KeyboardShortcutItemKind.cs
  src/Files.App/UserControls/KeyboardShortcut/KeyboardShortcutItemSize.cs
  src/Files.App/UserControls/KeyboardShortcut/KeyboardShortcutItemStyleSelector.cs
  src/Files.App/ViewModels/UserControls/AddressToolbarViewModel.cs
Labels: approved

#15070 Feature: List all the SharePoint directories
  src/Files.App/Utils/Cloud/CloudDrivesDetector.cs
Labels: approved

#15113 Fix: File extensions not showing up at Recent Files
  src/Files.App/Utils/RecentItem/RecentItem.cs
  src/Files.App/Utils/RecentItem/RecentItems.cs
Labels: needs-review

#15114 GitHub: Fixed formatting workflow
  .github/workflows/format-xaml.yml
Labels: approved

#15126 Fix: Crash caused by useless predicate.
  src/Files.App (Package)/Package.appxmanifest
  src/Files.App.Server/Database/LayoutPreferencesDatabase.cs
  src/Files.App/Helpers/Layout/LayoutPreferencesDatabaseManager.cs
Labels: approved

#15128 Fix: Fixed issue where items could not be sorted by clicking on the header of the details layout
  src/Files.App/Views/Layouts/DetailsLayoutPage.xaml.cs
Labels: approved

#15119 Feature: Added support for filtering current directory when typing into search box
  src/Files.App/Data/Models/ItemViewModel.cs
  src/Files.App/ViewModels/UserControls/AddressToolbarViewModel.cs
  src/Files.App/Views/Shells/BaseShellPage.cs
  src/Files.App/Views/Shells/ModernShellPage.xaml.cs
Labels: needs-review

#15131 Code Quality: Migrated CopyFileFromApp and MoveFileFromApp to CsWin32
  src/Files.App/Helpers/Interop/NativeFileOperationsHelper.cs
  src/Files.App/NativeMethods.txt
  src/Files.App/Utils/Storage/Helpers/FilesystemResult.cs
  src/Files.App/Utils/Storage/Operations/FilesystemOperations.cs
  src/Files.App/Utils/Storage/StorageItems/NativeStorageFile.cs
  src/Files.App/Utils/Storage/StorageItems/ZipStorageFile.cs
  src/Files.App/Utils/Storage/StorageItems/ZipStorageFolder.cs
Labels: approved

#15090 Code Quality: Files.App/Helpers - convert into constant.
  src/Files.App/Helpers/Environment/SoftwareHelpers.cs
  src/Files.App/Helpers/NaturalStringComparer.cs
  src/Files.App/Helpers/WMI/ManagementEventWatcher.cs
  src/Files.App/Helpers/Win32/Win32Helper.Storage.cs
Labels: approved

#15093 Code Quality: Use concrete types when possible for improved performance
  src/Files.App/Data/Factories/ShellContextFlyoutHelper.cs
  src/Files.App/Data/Models/ItemViewModel.cs
  src/Files.App/Services/UpdateService.cs
  src/Files.App/Utils/RecycleBin/RecycleBinManager.cs
  src/Files.App/Utils/Storage/Collection/BulkConcurrentObservableCollection.cs
  src/Files.App/Utils/Storage/Collection/ConcurrentCollection.cs
  src/Files.App/Utils/Storage/Enumerators/Win32StorageEnumerator.cs
  src/Files.App/Utils/Storage/Operations/FilesystemHelpers.cs
  src/Files.App/Utils/Storage/StorageItems/ZipStorageFolder.cs
  src/Files.App/ViewModels/Properties/CompatibilityViewModel.cs
  src/Files.App/ViewModels/Settings/AboutViewModel.cs
  src/Files.App/ViewModels/UserControls/SidebarViewModel.cs
Labels: needs-review

#15140 Code Quality: Avoid unnecessary shell folder fetching
  src/Files.App/Helpers/Win32/Win32Helper.Shell.cs
  src/Files.App/Services/QuickAccessService.cs
  src/Files.App/Utils/RecentItem/RecentItems.cs
  src/Files.App/Utils/RecycleBin/RecycleBinHelpers.cs
  src/Files.App/Utils/Storage/StorageItems/ShellStorageFolder.cs
Labels: approved

#15139 Fix: Fixed issue where some file operations would fail
  src/Files.App/Data/Items/ListedItem.cs
  src/Files.App/Data/Models/ItemViewModel.cs
  src/Files.App/MainWindow.xaml.cs
  src/Files.App/Utils/FileTags/FileTagsHelper.cs
  src/Files.App/Utils/Storage/Operations/FileOperationsHelpers.cs
Labels: approved

#15109 Feature: Added support for custom key bindings
  src/Files.App/Actions/Content/Archives/Decompress/DecompressArchiveToChildFolderAction.cs
  src/Files.App/Actions/FileSystem/CopyPathWithQuotesAction.cs
  src/Files.App/Actions/Global/EditPathAction.cs
  src/Files.App/Actions/Global/EnterCompactOverlayAction.cs
  src/Files.App/Actions/Global/ExitCompactOverlayAction.cs
  src/Files.App/Actions/Navigation/NavigateBackAction.cs
  src/Files.App/Actions/Navigation/NavigateForwardAction.cs
  src/Files.App/Actions/Navigation/NavigateUpAction.cs
  src/Files.App/Actions/Navigation/OpenInNewWindowItemAction.cs
  src/Files.App/Actions/Navigation/OpenNewPaneAction.cs
  src/Files.App/Actions/Open/OpenPropertiesAction.cs
  src/Files.App/Actions/Show/ToggleDetailsPaneAction.cs
  src/Files.App/Actions/Show/ToggleInfoPaneAction.cs
  src/Files.App/Actions/Show/TogglePreviewPaneAction.cs
  src/Files.App/Data/Commands/HotKey/HotKey.cs
  src/Files.App/Data/Commands/HotKey/HotKeyCollection.cs
  src/Files.App/Data/Commands/HotKey/HotKeyHelpers.cs
  src/Files.App/Data/Commands/HotKey/KeyModifiers.cs
  src/Files.App/Data/Commands/IRichCommand.cs
  src/Files.App/Data/Commands/Manager/CommandCodes.cs
  src/Files.App/Data/Commands/Manager/CommandManager.cs
  src/Files.App/Data/Commands/Manager/ICommandManager.cs
  src/Files.App/Data/Commands/ModifiableCommand.cs
  src/Files.App/Data/Commands/NoneCommand.cs
  src/Files.App/Data/Enums/SettingsPageKind.cs
  src/Files.App/Data/Items/ModifiableCommandHotKeyItem.cs
  src/Files.App/Data/Models/ContextMenuFlyoutItemViewModelBuilder.cs
  src/Files.App/Dialogs/SettingsDialog.xaml
  src/Files.App/Dialogs/SettingsDialog.xaml.cs
  src/Files.App/Helpers/Win32/Win32PInvoke.Methods.cs
  src/Files.App/Services/Settings/GeneralSettingsService.cs
  src/Files.App/Services/Settings/IGeneralSettingsService.cs
  src/Files.App/Strings/en-US/Resources.resw
  src/Files.App/UserControls/KeyboardShortcut/KeyboardShortcut.cs
  src/Files.App/ViewModels/Settings/ActionsViewModel.cs
  src/Files.App/Views/Settings/ActionsPage.xaml
  src/Files.App/Views/Settings/ActionsPage.xaml.cs
  tests/Files.InteractionTests/Tests/SettingsTests.cs
Labels: needs-review

#15149 Fix: Fixed issue where properties window could not navigate to other pages after returning from advanced settings
  src/Files.App/ViewModels/Properties/MainPropertiesViewModel.cs
Labels: approved

#15160 Fix: Fixed possible crash when entering characters into path bar
  src/Files.App/ViewModels/UserControls/AddressToolbarViewModel.cs
Labels: approved

#15150 Code Quality: Replace ThemeHelper with AppThemeModeService
  src/Files.App/Data/Contracts/IAppThemeModeService.cs
  src/Files.App/Dialogs/AddBranchDialog.xaml
  src/Files.App/Dialogs/AddBranchDialog.xaml.cs
  src/Files.App/Dialogs/AddItemDialog.xaml
  src/Files.App/Dialogs/AddItemDialog.xaml.cs
  src/Files.App/Dialogs/CreateArchiveDialog.xaml
  src/Files.App/Dialogs/CreateArchiveDialog.xaml.cs
  src/Files.App/Dialogs/CreateShortcutDialog.xaml
  src/Files.App/Dialogs/CreateShortcutDialog.xaml.cs
  src/Files.App/Dialogs/CredentialDialog.xaml
  src/Files.App/Dialogs/CredentialDialog.xaml.cs
  src/Files.App/Dialogs/DecompressArchiveDialog.xaml
  src/Files.App/Dialogs/DecompressArchiveDialog.xaml.cs
  src/Files.App/Dialogs/DynamicDialog.xaml
  src/Files.App/Dialogs/DynamicDialog.xaml.cs
  src/Files.App/Dialogs/ElevateConfirmDialog.xaml
  src/Files.App/Dialogs/ElevateConfirmDialog.xaml.cs
  src/Files.App/Dialogs/FileTooLargeDialog.xaml
  src/Files.App/Dialogs/FileTooLargeDialog.xaml.cs
  src/Files.App/Dialogs/FilesystemOperationDialog.xaml
  src/Files.App/Dialogs/FilesystemOperationDialog.xaml.cs
  src/Files.App/Dialogs/GitHubLoginDialog.xaml
  src/Files.App/Dialogs/GitHubLoginDialog.xaml.cs
  src/Files.App/Dialogs/ReleaseNotesDialog.xaml
  src/Files.App/Dialogs/ReleaseNotesDialog.xaml.cs
  src/Files.App/Dialogs/ReorderSidebarItemsDialog.xaml
  src/Files.App/Dialogs/ReorderSidebarItemsDialog.xaml.cs
  src/Files.App/Helpers/Application/AppLifecycleHelper.cs
  src/Files.App/Helpers/UI/ThemeHelper.cs
  src/Files.App/Services/AppThemeModeService.cs
  src/Files.App/Services/ResourcesService.cs
  src/Files.App/Services/Settings/AppearanceSettingsService.cs
  src/Files.App/Services/Settings/IAppearanceSettingsService.cs
  src/Files.App/Utils/Storage/Helpers/FilePropertiesHelpers.cs
  src/Files.App/ViewModels/MainPageViewModel.cs
  src/Files.App/ViewModels/Settings/AppearanceViewModel.cs
  src/Files.App/ViewModels/SettingsViewModel.cs
  src/Files.App/Views/Properties/MainPropertiesPage.xaml.cs
Labels: approved

#15171 Feature: Disable access keys when content dialogs are open
  src/Files.App/UserControls/AddressToolbar.xaml
  src/Files.App/UserControls/AddressToolbar.xaml.cs
  src/Files.App/UserControls/InnerNavigationToolbar.xaml
  src/Files.App/UserControls/InnerNavigationToolbar.xaml.cs
Labels: approved

#15005 Code Quality: Reduced usage of Await inside foreach loops
  src/Files.App/Actions/Content/Tags/OpenAllTaggedActions.cs
  src/Files.App/Data/Factories/ShellContextFlyoutHelper.cs
  src/Files.App/Utils/Storage/Operations/FilesystemHelpers.cs
  src/Files.App/Views/Layouts/BaseLayoutPage.cs
Labels: approved

#15173 Code Quality: Migrated `GetKeyState` to CsWin32
  src/Files.App/Helpers/Interop/NativeWinApiHelper.cs
  src/Files.App/Helpers/Win32/Win32PInvoke.Methods.cs
  src/Files.App/NativeMethods.txt
  src/Files.App/Views/Layouts/BaseGroupableLayoutPage.cs
Labels: approved

#15148 Code Quality: Moved service interfaces to Contracts & Removed JumpListHelper
  src/Files.App/Data/Contracts/IAddItemService.cs
  src/Files.App/Data/Contracts/IDialogService.cs
  src/Files.App/Data/Contracts/IFileExplorerService.cs
  src/Files.App/Data/Contracts/IFileTagsService.cs
  src/Files.App/Data/Contracts/IImageService.cs
  src/Files.App/Data/Contracts/ILocalizationService.cs
  src/Files.App/Data/Contracts/INetworkDrivesService.cs
  src/Files.App/Data/Contracts/IPreviewPopupProvider.cs
  src/Files.App/Data/Contracts/IPreviewPopupService.cs
  src/Files.App/Data/Contracts/IQuickAccessService.cs
  src/Files.App/Data/Contracts/IRemovableDrivesService.cs
  src/Files.App/Data/Contracts/IResourcesService.cs
  src/Files.App/Data/Contracts/IStartMenuService.cs
  src/Files.App/Data/Contracts/IThreadingService.cs
  src/Files.App/Data/Contracts/IUpdateService.cs
  src/Files.App/Data/Contracts/IVolumeInfoFactory.cs
  src/Files.App/Data/Contracts/IWindowsJumpListService.cs
  src/Files.App/Data/Contracts/ImagingService.cs
  src/Files.App/Data/Models/ItemViewModel.cs
  src/Files.App/Helpers/Application/AppLifecycleHelper.cs
  src/Files.App/Helpers/UI/JumpListHelper.cs
  src/Files.App/Services/WindowsJumpListService.cs
  src/Files.App/Utils/Storage/Operations/FilesystemHelpers.cs
Labels: approved, requires quality assurance

#15174 Code Quality: Migrated `GetCursorPos` to CsWin32
  src/Files.App/Helpers/Win32/Win32PInvoke.Methods.cs
  src/Files.App/Helpers/Win32/Win32PInvoke.Structs.cs
  src/Files.App/UserControls/TabBar/TabBar.xaml.cs
  src/Files.App/Utils/Storage/Helpers/FilePropertiesHelpers.cs
Labels: approved

#15176 Feature: Show Lucid Link in the cloud drives section
  src/Files.App/Utils/Cloud/CloudProviders.cs
  src/Files.App/Utils/Cloud/Detector/CloudDetector.cs
  src/Files.App/Utils/Cloud/Detector/LucidLinkCloudDetector.cs
Labels: approved

#15175 Code Quality: Migrated `CreateDirectoryFromApp` to CsWin32
  src/Files.App/Helpers/Interop/NativeFileOperationsHelper.cs
  src/Files.App/NativeMethods.txt
  src/Files.App/Utils/Serialization/Implementation/DefaultSettingsSerializer.cs
Labels: approved

#15178 Code Quality: Add exception log for server
  src/Files.App.Server/Program.cs
Labels: approved

#15166 Code Quality: Replace StorageCacheController with IStorageCacheService
  src/Files.App/Data/Contracts/IStorageCacheService.cs
  src/Files.App/Data/Models/ItemViewModel.cs
  src/Files.App/Helpers/Application/AppLifecycleHelper.cs
  src/Files.App/Services/StorageCacheService.cs
  src/Files.App/Utils/Storage/Cache/IStorageCacheController.cs
  src/Files.App/Utils/Storage/Cache/StorageCacheController.cs
  src/Files.App/Utils/Storage/Enumerators/Win32StorageEnumerator.cs
Labels: needs-review

#15194 Fix: Fixed alignment of the add tab button
  src/Files.App/Views/MainPage.xaml
Labels: approved

#15180 Fix: Fixed issue where adaptive layout is not disabled when the sync layout setting is on
  src/Files.App/Data/Contexts/DisplayPage/DisplayPageContext.cs
  src/Files.App/Strings/en-US/Resources.resw
  src/Files.App/UserControls/InnerNavigationToolbar.xaml
  src/Files.App/ViewModels/Settings/LayoutViewModel.cs
  src/Files.App/Views/Settings/ActionsPage.xaml
  src/Files.App/Views/Settings/LayoutPage.xaml
Labels: needs-review

#15197 Fix: Fixed issue where Git submenu was shown for non-GitHub repos
  src/Files.App/Data/Models/CurrentInstanceViewModel.cs
  src/Files.App/Views/HomePage.xaml.cs
  src/Files.App/Views/Shells/BaseShellPage.cs
Labels: approved

#15195 Code Quality: Use compile time Regex
  src/Files.App/Data/Items/WindowsCompatibilityOptions.cs
  src/Files.App/Helpers/RegexHelpers.cs
  src/Files.App/Utils/Git/GitHelpers.cs
  src/Files.App/Utils/RecycleBin/RecycleBinHelpers.cs
  src/Files.App/Utils/Shell/LaunchHelper.cs
  src/Files.App/Utils/Storage/StorageItems/BaseQueryResults.cs
  src/Files.App/Utils/Storage/StorageItems/NativeStorageFile.cs
  src/Files.App/Views/Properties/GeneralPage.xaml.cs
Labels: approved

#15155 Code Quality: Removed NetworkDrivesViewModel and NetworkDrivesAPI
  src/Files.App/Data/Contracts/INetworkDrivesService.cs
  src/Files.App/Data/Models/ItemViewModel.cs
  src/Files.App/Data/Models/NetworkConnectionDialog.cs
  src/Files.App/Data/Models/NetworkDrivesViewModel.cs
  src/Files.App/Helpers/Application/AppLifecycleHelper.cs
  src/Files.App/Helpers/Navigation/NavigationHelpers.cs
  src/Files.App/Services/NetworkDrivesService.cs
  src/Files.App/UserControls/Widgets/DrivesWidget.xaml.cs
  src/Files.App/Utils/Global/NetworkDrivesAPI.cs
  src/Files.App/ViewModels/MainPageViewModel.cs
  src/Files.App/ViewModels/UserControls/SidebarViewModel.cs
Labels: approved, requires quality assurance

#15204 Fix: Fixed crash when closing the GitHub login modal
  src/Files.App/Dialogs/GitHubLoginDialog.xaml.cs
Labels: needs-review

#15210 Fix: Fixed issue where Recycle Bin wasn't pinned by default
  src/Files.App/Utils/Global/QuickAccessManager.cs
Labels: approved

#15216 Code Quality: Fixed the way tags were initialized
  src/Files.App/Data/Items/ListedItem.cs
Labels: approved

#15208 Code Quality: Added Save dialog project
  Files.sln
  src/Files.App.OpenDialog/Files.App.OpenDialog.Win32.vcxproj
  src/Files.App.OpenDialog/FilesOpenDialog.cpp
  src/Files.App.OpenDialog/FilesOpenDialog.h
  src/Files.App.SaveDialog/CustomSaveDialog.cpp
  src/Files.App.SaveDialog/CustomSaveDialog.def
  src/Files.App.SaveDialog/CustomSaveDialog.idl
  src/Files.App.SaveDialog/CustomSaveDialog.rc
  src/Files.App.SaveDialog/CustomSaveDialog.rgs
  src/Files.App.SaveDialog/CustomSaveDialogps.def
  src/Files.App.SaveDialog/Files.App.SaveDialog.Win32.vcxproj
  src/Files.App.SaveDialog/Files.App.SaveDialog.vcxproj
  src/Files.App.SaveDialog/Files.App.SaveDialog.vcxproj.filters
  src/Files.App.SaveDialog/FilesDialogEvents.cpp
  src/Files.App.SaveDialog/FilesDialogEvents.h
  src/Files.App.SaveDialog/FilesSaveDialog.cpp
  src/Files.App.SaveDialog/FilesSaveDialog.h
  src/Files.App.SaveDialog/FilesSaveDialog.rgs
  src/Files.App.SaveDialog/UndefInterfaces.h
  src/Files.App.SaveDialog/dllmain.cpp
  src/Files.App.SaveDialog/dllmain.h
  src/Files.App.SaveDialog/framework.h
  src/Files.App.SaveDialog/pch.cpp
  src/Files.App.SaveDialog/pch.h
  src/Files.App.SaveDialog/resource.h
  src/Files.App.SaveDialog/targetver.h
  src/Files.App/App.xaml.cs
  src/Files.App/Assets/FilesOpenDialog/CustomOpenDialog64.dll
  src/Files.App/Program.cs
  src/Files.App/ViewModels/Settings/AdvancedViewModel.cs
  src/Files.App/Views/Settings/AdvancedPage.xaml
Labels: approved

#15220 Code Quality: Use registry for preferences and tags storage
  src/Files.App (Package)/Package.appxmanifest
  src/Files.App.Server/Data/LayoutPreferences.cs
  src/Files.App.Server/Data/TaggedFile.cs
  src/Files.App.Server/Database/FileTagsDatabase.cs
  src/Files.App.Server/Database/LayoutPreferencesDatabase.cs
  src/Files.App.Server/Files.App.Server.csproj
  src/Files.App.Server/Utils/RegistryUtils.cs
  src/Files.App/Constants.cs
  src/Files.App/Helpers/Layout/LayoutPreferencesDatabaseItem.cs
  src/Files.App/Helpers/Layout/LayoutPreferencesDatabaseManager.cs
  src/Files.App/Helpers/Layout/LayoutPreferencesManager.cs
  src/Files.App/ViewModels/Settings/AdvancedViewModel.cs
  src/Files.Core.SourceGenerator/AnalyzerReleases.Shipped.md
  src/Files.Core.SourceGenerator/AnalyzerReleases.Unshipped.md
  src/Files.Core.SourceGenerator/DiagnosticDescriptors.cs
  src/Files.Core.SourceGenerator/RegistrySerializationGenerator.cs
  src/Files.Shared/Attributes/RegistrySerializableAttribute.cs
Labels: needs-review

#15236 Fix: Fixed issue where View more and Open all in Tags widget were disabled
  src/Files.App/Data/Items/WidgetFileTagsContainerItem.cs
Labels: needs-review

#15229 Code Quality: Various fixes to the WinRT server call
  src/Files.App.Server/NativeMethods.json
  src/Files.App.Server/NativeMethods.txt
  src/Files.App.Server/Program.cs
  src/Files.App/Helpers/Layout/LayoutPreferencesManager.cs
  src/Files.App/Program.cs
  src/Files.App/Utils/Storage/StorageItems/SystemStorageFile.cs
Labels: approved
