Repository files-community/Files, pull requests merged in 2024-06, with the labels that each got.

#15532 Fix: Fixed an issue where text on the Actions Settings page didn't wrap
  src/Files.App/Views/Settings/ActionsPage.xaml
Labels: ready to merge

#15531 Code Quality: Replace Community Toolkit notifications with WinAppSdk
  src/Files.App/App.xaml.cs
  src/Files.App/Files.App.csproj
  src/Files.App/Helpers/Application/AppLifecycleHelper.cs
  src/Files.App/Helpers/Application/AppToastNotificationHelper.cs
  src/Files.App/Helpers/UI/UIHelpers.cs
Labels: ready to merge

#15449 Fix: Fixed an issue where the focus was lost when quickly switching tabs
  src/Files.App/Actions/Navigation/NextTabAction.cs
  src/Files.App/Actions/Navigation/PreviousTabAction.cs
  src/Files.App/Data/Models/AppModel.cs
  src/Files.App/ViewModels/MainPageViewModel.cs
Labels: ready to merge

#15553 Code Quality: Fixed an issue where folder selection dialog wouldn't work
  src/Files.App/ViewModels/Dialogs/DecompressArchiveDialogViewModel.cs
  src/Files.App/Views/Properties/LibraryPage.xaml.cs
Labels: ready to merge

#15545 Code Quality: Added support for clinking links in the release notes
  src/Files.App/Dialogs/ReleaseNotesDialog.xaml
  src/Files.App/Dialogs/ReleaseNotesDialog.xaml.cs
Labels: needs - code review

#15535 Code Quality: Replace AppCenter with Sentry
  .github/PRIVACY.md
  .github/workflows/cd-preview.yml
  .github/workflows/cd-stable.yml
  .github/workflows/deploy-preview-legacy.yml
  .github/workflows/deploy-stable-legacy.yml
  builds/azure-pipelines-release.yml
  scripts/Configure-AppxManifest.ps1
  src/Files.App (Package)/Package.appxmanifest
  src/Files.App/App.xaml.cs
  src/Files.App/Constants.cs
  src/Files.App/Data/Commands/ActionCommand.cs
  src/Files.App/Data/Contracts/IGeneralSettingsService.cs
  src/Files.App/Files.App.csproj
  src/Files.App/Helpers/Application/AppLifecycleHelper.cs
  src/Files.App/Services/Settings/ActionsSettingsService.cs
  src/Files.App/Services/Settings/AppSettingsService.cs
  src/Files.App/Services/Settings/AppearanceSettingsService.cs
  src/Files.App/Services/Settings/DevToolsSettingsService.cs
  src/Files.App/Services/Settings/FoldersSettingsService.cs
  src/Files.App/Services/Settings/GeneralSettingsService.cs
  src/Files.App/Services/Settings/InfoPaneSettingsService.cs
  src/Files.App/Services/Settings/LayoutSettingsService.cs
  src/Files.App/Utils/Git/GitHelpers.cs
Labels: ready to merge

#15544 Code Quality: Introduced pane generation 2
  src/Files.App/Actions/Navigation/ClosePaneAction.cs
  src/Files.App/Actions/Navigation/DuplicateCurrentTabAction.cs
  src/Files.App/Actions/Navigation/DuplicateSelectedTabAction.cs
  src/Files.App/Actions/Navigation/OpenDirectoryInNewTabAction.cs
  src/Files.App/Actions/Navigation/OpenNewPaneAction.cs
  src/Files.App/App.xaml.cs
  src/Files.App/Data/Contexts/ContentPage/ContentPageContext.cs
  src/Files.App/Data/Contexts/MultiPanes/IMultiPanesContext.cs
  src/Files.App/Data/Contexts/MultiPanes/MultiPanesContext.cs
  src/Files.App/Data/Contracts/IMultiPaneInfo.cs
  src/Files.App/Data/Contracts/IShellPanesPage.cs
  src/Files.App/Helpers/Application/AppLifecycleHelper.cs
  src/Files.App/Helpers/Navigation/NavigationHelpers.cs
  src/Files.App/MainWindow.xaml.cs
  src/Files.App/UserControls/TabBar/ITabBarItemContent.cs
  src/Files.App/ViewModels/MainPageViewModel.cs
  src/Files.App/ViewModels/UserControls/AddressToolbarViewModel.cs
  src/Files.App/ViewModels/UserControls/SidebarViewModel.cs
  src/Files.App/ViewModels/UserControls/Widgets/DrivesWidgetViewModel.cs
  src/Files.App/ViewModels/UserControls/Widgets/FileTagsWidgetViewModel.cs
  src/Files.App/ViewModels/UserControls/Widgets/NetworkLocationsWidgetViewModel.cs
  src/Files.App/ViewModels/UserControls/Widgets/QuickAccessWidgetViewModel.cs
  src/Files.App/Views/MainPage.xaml
  src/Files.App/Views/MainPage.xaml.cs
  src/Files.App/Views/PaneHolderPage.xaml
  src/Files.App/Views/PaneHolderPage.xaml.cs
  src/Files.App/Views/ShellPanesPage.xaml
  src/Files.App/Views/ShellPanesPage.xaml.cs
  src/Files.App/Views/Shells/BaseShellPage.cs
Labels: ready to merge

#15329 Code Quality: Use RichCommands in home and sidebar
  src/Files.App/Actions/IAction.cs
  src/Files.App/Actions/Navigation/OpenDirectoryInNewPaneAction.cs
  src/Files.App/Actions/Navigation/OpenDirectoryInNewTabAction.cs
  src/Files.App/Actions/Navigation/OpenInNewPane/BaseOpenInNewPaneAction.cs
  src/Files.App/Actions/Navigation/OpenInNewPane/OpenInNewPaneAction.cs
  src/Files.App/Actions/Navigation/OpenInNewPane/OpenInNewPaneFromHomeAction.cs
  src/Files.App/Actions/Navigation/OpenInNewPane/OpenInNewPaneFromSidebarAction.cs
  src/Files.App/Actions/Navigation/OpenInNewTab/BaseOpenInNewTabAction.cs
  src/Files.App/Actions/Navigation/OpenInNewTab/OpenInNewTabAction.cs
  src/Files.App/Actions/Navigation/OpenInNewTab/OpenInNewTabFromHomeAction.cs
  src/Files.App/Actions/Navigation/OpenInNewTab/OpenInNewTabFromSidebarAction.cs
  src/Files.App/Actions/Navigation/OpenInNewWindow/BaseOpenInNewWindowAction.cs
  src/Files.App/Actions/Navigation/OpenInNewWindow/OpenInNewWindowAction.cs
  src/Files.App/Actions/Navigation/OpenInNewWindow/OpenInNewWindowFromHomeAction.cs
  src/Files.App/Actions/Navigation/OpenInNewWindow/OpenInNewWindowFromSidebarAction.cs
  src/Files.App/Actions/Navigation/OpenInNewWindowItemAction.cs
  src/Files.App/Data/Commands/ActionCommand.cs
  src/Files.App/Data/Commands/IRichCommand.cs
  src/Files.App/Data/Commands/Manager/CommandCodes.cs
  src/Files.App/Data/Commands/Manager/CommandManager.cs
  src/Files.App/Data/Commands/Manager/ICommandManager.cs
  src/Files.App/Data/Commands/ModifiableCommand.cs
  src/Files.App/Data/Commands/NoneCommand.cs
  src/Files.App/Data/Factories/ContentPageContextFlyoutFactory.cs
  src/Files.App/Helpers/Application/AppLifecycleHelper.cs
  src/Files.App/ViewModels/Settings/ActionsViewModel.cs
  src/Files.App/ViewModels/UserControls/AddressToolbarViewModel.cs
  src/Files.App/ViewModels/UserControls/SidebarViewModel.cs
  src/Files.App/ViewModels/UserControls/Widgets/BaseWidgetViewModel.cs
  src/Files.App/ViewModels/UserControls/Widgets/DrivesWidgetViewModel.cs
  src/Files.App/ViewModels/UserControls/Widgets/FileTagsWidgetViewModel.cs
  src/Files.App/ViewModels/UserControls/Widgets/QuickAccessWidgetViewModel.cs
Labels: ready to merge

#15579 Code Quality: Reverting changes for DateTime formatting without ICU
  src/Files.App/Services/DateTimeFormatter/ApplicationDateTimeFormatter.cs
  src/Files.App/Strings/en-US/Resources.resw
Labels: ready to merge

#15536 Code Quality: Fixed Sidebar alignment
  src/Files.App/UserControls/SideBar/SideBarControls.xaml
  src/Files.App/UserControls/SideBar/SideBarItem.cs
  src/Files.App/UserControls/SideBar/SideBarView.xaml
  src/Files.App/UserControls/SideBar/SideBarView.xaml.cs
Labels: ready to merge

#15581 Fix: Fixed NullReferenceException in RegistryHelpers.CombineKeys
  src/Files.App/Utils/FileTags/FileTagsHelper.cs
Labels: ready to merge

#15543 Feature: Added dimensions to tooltip when hovering over image files
  src/Files.App/Actions/Content/Background/BaseSetAsAction.cs
  src/Files.App/Actions/Content/ImageManipulation/BaseRotateAction.cs
  src/Files.App/Data/Factories/ContentPageContextFlyoutFactory.cs
  src/Files.App/Data/Items/ListedItem.cs
  src/Files.App/Data/Models/SelectedItemsPropertiesViewModel.cs
  src/Files.Shared/Helpers/FileExtensionHelpers.cs
Labels: ready to merge

#15584 Code Quality: Assign background/border properties in respective controls
  src/Files.App/UserControls/InnerNavigationToolbar.xaml
  src/Files.App/UserControls/Pane/InfoPane.xaml
  src/Files.App/UserControls/TabBar/TabBar.xaml
  src/Files.App/UserControls/TabBar/TabBar.xaml.cs
  src/Files.App/Views/MainPage.xaml
  src/Files.App/Views/MainPage.xaml.cs
Labels: ready to merge

#15587 Fix: Fixed potential crash on startup
  src/Files.App/Helpers/UI/AppSystemBackdrop.cs
Labels: needs - code review

#15586 Fix: Fixed crash that could occur if the Libraries folder wasn't located
  src/Files.App/Data/Items/ShellLibraryItem.cs
  src/Files.App/Helpers/Win32/Win32PInvoke.Methods.cs
Labels: needs - code review

#15585 Code Quality: Move new tab button to TabBar itself
  src/Files.App/UserControls/TabBar/TabBar.xaml
  src/Files.App/UserControls/TabBar/TabBar.xaml.cs
  src/Files.App/Views/MainPage.xaml
  src/Files.App/Views/MainPage.xaml.cs
Labels: needs - code review

#15608 Fix: Fixed NullReferenceException in StatusBarViewModel.UpdateGitInfo
  src/Files.App/Data/Models/DirectoryPropertiesViewModel.cs
Labels: ready to merge

#15609 Fix: Fixed HttpRequestException in GitHelpers.RequireGitAuthenticationAsync
  src/Files.App/Utils/Git/GitHelpers.cs
Labels: ready to merge

#15600 Fix: Prevent issue "WinUI Desktop Window object has already been closed"
  src/Files.App/ViewModels/UserControls/InfoPaneViewModel.cs
  src/Files.App/Views/MainPage.xaml.cs
Labels: needs - code review

#15558 Code Quality: Add Composition based speed graph
  src/Files.App/Data/Contracts/IAppThemeModeService.cs
  src/Files.App/Files.App.csproj
  src/Files.App/Services/App/AppThemeModeService.cs
  src/Files.App/UserControls/AddressToolbar.xaml
  src/Files.App/UserControls/StatusCenter/SpeedGraph.cs
  src/Files.App/UserControls/StatusCenter/StatusCenter.xaml
  src/Files.App/UserControls/StatusCenter/StatusCenter.xaml.cs
  src/Files.App/Utils/StatusCenter/StatusCenterItem.cs
Labels: needs - code review

#15582 Fix: Fixed ArgumentException at CommandManager.OverwriteKeyBindings
  src/Files.App/Data/Commands/Manager/CommandManager.cs
Labels: ready to merge

#15618 Code Quality: Added a logger to send exception reports to Sentry
  src/Files.App/Helpers/Application/AppLifecycleHelper.cs
  src/Files.App/Utils/Logger/SentryLogger.cs
  src/Files.App/Utils/Logger/SentryLoggerProvider.cs
  src/Files.App/ViewModels/UserControls/InfoPaneViewModel.cs
  src/Files.App/Views/MainPage.xaml.cs
Labels: ready to merge

#15615 Code Quality: Wrap sync icon in border
  src/Files.App/Views/Layouts/ColumnLayoutPage.xaml
  src/Files.App/Views/Layouts/DetailsLayoutPage.xaml
  src/Files.App/Views/Layouts/GridLayoutPage.xaml
Labels: needs - code review

#15621 Code Quality: Formatting Issue with Dimensions and Synchronization Labels
  src/Files.App/Data/Items/ListedItem.cs
  src/Files.App/Strings/en-US/Resources.resw
  src/Files.App/Views/Layouts/DetailsLayoutPage.xaml
Labels: ready to merge

#15624 Fix: Fixed an issue where setting the desktop wallpaper didn't work on multiple monitors
  src/Files.App/Utils/Global/WallpaperHelpers.cs
Labels: needs - code review

#15635 Code Quality: Remove Microsoft.DotNet.UpgradeAssistant.Extensions.Default.Analyzers
  src/Files.App/Files.App.csproj
Labels: ready to merge

#15637 Code Quality: Bump CsWin32 to latest available
  src/Files.App.Server/Files.App.Server.csproj
  src/Files.App.Server/Helpers.cs
  src/Files.App.Server/NativeMethods.txt
  src/Files.App.Server/Program.cs
  src/Files.App/Files.App.csproj
  src/Files.App/Services/Storage/StorageNetworkService.cs
Labels: ready to merge

#15638 Code Quality: Fixed COMException with WinUI Desktop Window
  src/Files.App/Views/ShellPanesPage.xaml.cs
Labels: needs - code review

#15627 Feature: Added support for hiding the toolbar
  src/Files.App/Data/Contracts/IAppearanceSettingsService.cs
  src/Files.App/Services/Settings/AppearanceSettingsService.cs
  src/Files.App/Strings/en-US/Resources.resw
  src/Files.App/Styles/PathIcons.xaml
  src/Files.App/ViewModels/MainPageViewModel.cs
  src/Files.App/ViewModels/Settings/AppearanceViewModel.cs
  src/Files.App/Views/MainPage.xaml
  src/Files.App/Views/Settings/AppearancePage.xaml
Labels: ready to merge

#15645 Fix: Fixed an issue with deleting items from zip files
  src/Files.App/Utils/Storage/Operations/FileOperationsHelpers.cs
Labels: ready to merge

#15625 Fix: Fixed an issue where changing icons didn't work when admin access was required
  src/Files.App/Utils/Storage/Operations/FileOperationsHelpers.cs
Labels: needs - code review

#15614 Feature: Added support for closing the left pane
  src/Files.App/Actions/Navigation/CloseActivePaneAction.cs
  src/Files.App/Data/Commands/Manager/CommandCodes.cs
  src/Files.App/Data/Commands/Manager/CommandManager.cs
  src/Files.App/Data/Commands/Manager/ICommandManager.cs
  src/Files.App/Data/Contracts/IShellPanesPage.cs
  src/Files.App/Strings/en-US/Resources.resw
  src/Files.App/UserControls/InnerNavigationToolbar.xaml
  src/Files.App/Views/ShellPanesPage.xaml.cs
Labels: needs - code review

#15647 Fix: Fixed System.TypeInitializationException in FileTagsDatabase
  src/Files.App/Utils/FileTags/FileTagsDatabase.cs
Labels: ready to merge

#15655 Feature: Added `ctrl` + `shift` + `b` shortcut to toggle the toolbar
  src/Files.App/Actions/Show/ToggleToolbarAction.cs
  src/Files.App/Data/Commands/Manager/CommandCodes.cs
  src/Files.App/Data/Commands/Manager/CommandManager.cs
  src/Files.App/Data/Commands/Manager/ICommandManager.cs
  src/Files.App/Strings/en-US/Resources.resw
Labels: needs - code review

#15628 Fix: Fixed an issue where arguments weren’t passed when running shortcuts as admin
  src/Files.App/Helpers/Win32/Win32Helper.Process.cs
Labels: ready to merge

#15669 Fix: Fixed crash that could occur when checking for updates
  src/Files.App/Services/App/AppUpdateStoreService.cs
Labels: needs - code review

#15666 Fix: Fixed an issue where the cursor wasn't inline when resizing columns in Details View
  src/Files.App/Views/Layouts/DetailsLayoutPage.xaml.cs
Labels: ready to merge

#15653 Feature: Added Tab Actions menu to the title bar
  src/Files.App/Strings/en-US/Resources.resw
  src/Files.App/UserControls/InnerNavigationToolbar.xaml
  src/Files.App/UserControls/Menus/MenuFlyoutItemWithOpacityIcon.xaml
  src/Files.App/UserControls/Menus/MenuFlyoutItemWithOpacityIcon.xaml.cs
  src/Files.App/UserControls/TabBar/TabBar.xaml
Labels: ready to merge

#15670 Fix: Fixed crash that could occur when adding items to the jumplist
  src/Files.App/Services/Windows/WindowsJumpListService.cs
Labels: needs - code review

#15672 Fix: Fixed InvalidOperationException in FileProperty.RetrieveAndInitializePropertiesAsync
  src/Files.App/ViewModels/Properties/Items/FileProperty.cs
Labels: ready to merge

#15690 Fix: Fixed an issue with extracting archives on ARM64 devices
  src/Files.App/7zArm64.dll
  src/Files.App/Files.App.csproj
Labels: needs - code review

#15696 Fix: Fixed ArgumentNullException in AppLifecycleHelper.HandleAppUnhandledException
  src/Files.App/Helpers/Application/AppLifecycleHelper.cs
Labels: ready to merge

#15632 Feature: Added support for displaying background images in folders
  src/Files.App/ViewModels/ShellViewModel.cs
  src/Files.App/Views/Shells/ModernShellPage.xaml
Labels: ready to merge

#15686 Fix: Fixed COMException when renaming files
  src/Files.App/Data/Models/AppModel.cs
  src/Files.App/Views/Layouts/BaseGroupableLayoutPage.cs
  src/Files.App/Views/Shells/BaseShellPage.cs
Labels: needs - code review

#15649 Docs: Update README.md
  .github/README.md
  assets/ClassicInstallerBadge-dark.png
  assets/ClassicInstallerBadge-light.png
  assets/ReadmeHero.png
  assets/StoreBadge-dark.png
  assets/StoreBadge-light.png
Labels: needs - code review

#15719 Fix: Fixed crash that would occur when entering invalid parameters via command line
  src/Files.App/Utils/CommandLine/ParsedCommand.cs
Labels: ready to merge

#15720 Fix: Fixed an issue where quick search filtering wasn't cleared when navigating to another folder
  src/Files.App/ViewModels/ShellViewModel.cs
Labels: ready to merge, area - actions

#15722 Feature: Added support for clicking links when previewing markdown files
  src/Files.App/UserControls/FilePreviews/MarkdownPreview.xaml
  src/Files.App/UserControls/FilePreviews/MarkdownPreview.xaml.cs
Labels: ready to merge
