Repository files-community/Files, pull requests merged in 2024-11, with the labels that each got.

#16410 Feature: Added support for pasting items as shortcuts
  src/Files.App/Actions/FileSystem/PasteItemAsShortcutAction.cs
  src/Files.App/Data/Commands/Manager/CommandCodes.cs
  src/Files.App/Data/Commands/Manager/CommandManager.cs
  src/Files.App/Data/Commands/Manager/ICommandManager.cs
  src/Files.App/Data/Factories/ContentPageContextFlyoutFactory.cs
  src/Files.App/Helpers/UI/UIFilesystemHelpers.cs
  src/Files.App/Strings/en-US/Resources.resw
Labels: ready to merge

#16418 Feature: Added an action to close all tabs
  src/Files.App/Actions/Navigation/CloseActivePaneAction.cs
  src/Files.App/Actions/Navigation/CloseAllTabsAction.cs
  src/Files.App/Data/Commands/Manager/CommandCodes.cs
  src/Files.App/Data/Commands/Manager/CommandManager.cs
  src/Files.App/Data/Commands/Manager/ICommandManager.cs
  src/Files.App/Helpers/Navigation/MultitaskingTabsHelpers.cs
  src/Files.App/Strings/en-US/Resources.resw
Labels: ready to merge

#16433 Code Quality: Updated commit message in `crowdin.yml` to match contribution guidelines
  crowdin.yml
Labels: ready to merge

#16382 Code Quality: Introduced ComPtr.As() to QI easily
  src/Files.App.CsWin32/Windows.Win32.ComHeapPtr.cs
  src/Files.App.CsWin32/Windows.Win32.ComPtr.cs
Labels: ready to merge

#16354 GitHub: Improved issue templates
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/code_quality_issue.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
Labels: changes requested

#16438 Feature: Added support for creating alternate data streams
  src/Files.App/Actions/FileSystem/CreateAlternateDataStreamAction.cs
  src/Files.App/Data/Commands/Manager/CommandCodes.cs
  src/Files.App/Data/Commands/Manager/CommandManager.cs
  src/Files.App/Data/Commands/Manager/ICommandManager.cs
  src/Files.App/Data/Contracts/IApplicationSettingsService.cs
  src/Files.App/Data/Contracts/IGeneralSettingsService.cs
  src/Files.App/Data/Factories/ContentPageContextFlyoutFactory.cs
  src/Files.App/Helpers/Dialog/DialogDisplayHelper.cs
  src/Files.App/Helpers/Dialog/DynamicDialogFactory.cs
  src/Files.App/Services/Settings/ApplicationSettingsService.cs
  src/Files.App/Services/Settings/GeneralSettingsService.cs
  src/Files.App/Strings/en-US/Resources.resw
  src/Files.App/ViewModels/Settings/GeneralViewModel.cs
  src/Files.App/Views/Settings/GeneralPage.xaml
Labels: ready to merge

#16444 GitHub: Changed bug report log upload tip
  .github/ISSUE_TEMPLATE/bug_report.yml
Labels: needs - code review

#16445 Fix: Fixed an issue where canceling drag & dropped cleared the selected items
  src/Files.App/ViewModels/Layouts/BaseLayoutViewModel.cs
Labels: needs - code review

#16452 Code Quality: Added AltDataStream Icon
  src/Files.App.Controls/ThemedIcon/Styles/Icons.Misc16.xaml
  src/Files.App/Actions/FileSystem/CreateAlternateDataStreamAction.cs
  tests/Files.App.UITests/Views/ThemedIconPage.xaml
Labels: ready to merge

#16150 Code Quality: Introduced IWindowsRecentItemsService
  src/Files.App.CsWin32/NativeMethods.txt
  src/Files.App.CsWin32/Windows.Win32.Extras.cs
  src/Files.App/App.xaml.cs
  src/Files.App/Data/Contracts/IWindowsRecentItemsService.cs
  src/Files.App/Data/Items/WidgetRecentItem.cs
  src/Files.App/GlobalUsings.cs
  src/Files.App/Helpers/Application/AppLifecycleHelper.cs
  src/Files.App/Helpers/Navigation/NavigationHelpers.cs
  src/Files.App/Helpers/UI/UIFilesystemHelpers.cs
  src/Files.App/Services/Storage/StorageTrashBinService.cs
  src/Files.App/Services/Windows/WindowsRecentItemsService.cs
  src/Files.App/UserControls/Widgets/RecentFilesWidget.xaml
  src/Files.App/UserControls/Widgets/RecentFilesWidget.xaml.cs
  src/Files.App/Utils/RecentItem/RecentItem.cs
  src/Files.App/Utils/RecentItem/RecentItems.cs
  src/Files.App/Utils/RecentItem/RecentItemsManager.cs
  src/Files.App/ViewModels/UserControls/Widgets/BaseWidgetViewModel.cs
  src/Files.App/ViewModels/UserControls/Widgets/RecentFilesWidgetViewModel.cs
Labels: ready to merge

#16466 Code Quality: Updated WindowsAppSDK to 1.5.241107002
  src/Files.App (Package)/Files.Package.wapproj
  src/Files.App.Controls/Files.App.Controls.csproj
  src/Files.App/Files.App.csproj
  tests/Files.App.UITests/Files.App.UITests.csproj
Labels: ready to merge

#16235 Code Quality: Removed Vanara from some classes
  src/Files.App.CsWin32/NativeMethods.txt
  src/Files.App/Data/Items/ShellLibraryItem.cs
  src/Files.App/Helpers/Win32/Win32Helper.Shell.cs
  src/Files.App/Helpers/Win32/Win32Helper.WindowManagement.cs
  src/Files.App/Helpers/Win32/Win32PInvoke.Methods.cs
  src/Files.App/Utils/Shell/ItemStreamHelper.cs
  src/Files.App/Utils/Shell/PreviewHandler.cs
  src/Files.App/Utils/Storage/Operations/FileSizeCalculator.cs
  src/Files.App/ViewModels/UserControls/Previews/ShellPreviewViewModel.cs
Labels: ready to merge

#16475 Feature: Added an option to manage tags when right clicking on the sidebar
  src/Files.App/Actions/Open/OpenSettingsAction.cs
  src/Files.App/Data/Contracts/INavigationControlItem.cs
  src/Files.App/Data/Parameters/SettingsNavigationParams.cs
  src/Files.App/Dialogs/SettingsDialog.xaml.cs
  src/Files.App/Strings/en-US/Resources.resw
  src/Files.App/ViewModels/UserControls/SidebarViewModel.cs
Labels: ready to merge

#16482 Code Quality: Fixed a GC hole in the network connection dialog
  src/Files.App/Data/Contracts/ICommonDialogService.cs
  src/Files.App/Services/Windows/WindowsDialogService.cs
Labels: ready to merge

#16505 Feature: Added support for making Files default app for opening gz archives
  src/Files.App (Package)/Package.appxmanifest
Labels: ready to merge

#16518 Fix: Fixed an issue where the address bar flyouts displayed duplicate items
  src/Files.App/UserControls/PathBreadcrumb.xaml
  src/Files.App/UserControls/PathBreadcrumb.xaml.cs
  src/Files.App/ViewModels/UserControls/AddressToolbarViewModel.cs
Labels: ready to merge

#16519 Fix: Fixed an issue where tabs weren't placed in the correct order when dragged from other windows
  src/Files.App/UserControls/TabBar/TabBar.xaml.cs
Labels: needs - code review

#16521 Feature: Reduced frequency of the review Files prompt
  src/Files.App/Views/MainPage.xaml.cs
Labels: needs - code review

#16522 Feature: Removed number of open tabs from the app title
  src/Files.App/Helpers/Navigation/NavigationHelpers.cs
Labels: needs - code review

#16001 Code Quality: Added StorageBar and StorageRing Controls
  src/Files.App.Controls/Storage/Data/BarShapes.cs
  src/Files.App.Controls/Storage/Data/ThicknessCheck.cs
  src/Files.App.Controls/Storage/RingShape/RingShape.Properties.cs
  src/Files.App.Controls/Storage/RingShape/RingShape.cs
  src/Files.App.Controls/Storage/StorageBar/StorageBar.Constants.cs
  src/Files.App.Controls/Storage/StorageBar/StorageBar.Properties.cs
  src/Files.App.Controls/Storage/StorageBar/StorageBar.ThemeResources.xaml
  src/Files.App.Controls/Storage/StorageBar/StorageBar.cs
  src/Files.App.Controls/Storage/StorageBar/StorageBar.xaml
  src/Files.App.Controls/Storage/StorageRing/StorageRing.Constants.cs
  src/Files.App.Controls/Storage/StorageRing/StorageRing.Properties.cs
  src/Files.App.Controls/Storage/StorageRing/StorageRing.ThemeResources.xaml
  src/Files.App.Controls/Storage/StorageRing/StorageRing.cs
  src/Files.App.Controls/Storage/StorageRing/StorageRing.xaml
  src/Files.App.Controls/Themes/Generic.xaml
  src/Files.App/Assets/FilesOpenDialog/Files.App.Launcher.exe
  src/Files.App/Assets/FilesOpenDialog/Files.App.Launcher.exe.sha256
  tests/Files.App.UITests/MainWindow.xaml
  tests/Files.App.UITests/MainWindow.xaml.cs
  tests/Files.App.UITests/Views/MainPage.xaml
  tests/Files.App.UITests/Views/StorageControlsPage.xaml
  tests/Files.App.UITests/Views/StorageControlsPage.xaml.cs
Labels: ready to merge

#16494 Code Quality: Updated dependencies
  src/Files.App/Files.App.csproj
Labels: needs - code review

#16536 Code Quality: Replace Vanara with CsWin32
  src/Files.App.CsWin32/NativeMethods.txt
  src/Files.App/Data/Factories/ShellContextFlyoutHelper.cs
  src/Files.App/Data/Items/ContextMenu.cs
  src/Files.App/UserControls/FilePreviews/ShellPreview.xaml.cs
  src/Files.App/Utils/Shell/ContextMenu.cs
  src/Files.App/Utils/Shell/LaunchHelper.cs
  src/Files.App/Utils/Storage/Enumerators/Win32StorageEnumerator.cs
  src/Files.App/ViewModels/Dialogs/DecompressArchiveDialogViewModel.cs
  src/Files.App/ViewModels/Settings/AdvancedViewModel.cs
  src/Files.App/ViewModels/Settings/GeneralViewModel.cs
  src/Files.App/ViewModels/UserControls/Previews/ShellPreviewViewModel.cs
Labels: ready to merge

#16547 Code Quality: Auto delete artifacts within CI
  .github/workflows/ci.yml
Labels: needs - code review
