Repository files-community/Files, pull requests merged in 2024-05, with the labels that each got.

#15259 Code Quality: Improved loading of pinned folders and recent files
  src/Files.App/Services/QuickAccessService.cs
  src/Files.App/Utils/RecentItem/RecentItems.cs
  src/Files.App/Utils/RecentItem/RecentItemsManager.cs
Labels: needs-review

#15251 Fix: Fixed an issue where HWiNFO64.exe wouldn't open
  src/Files.App/Utils/Shell/LaunchHelper.cs
Labels: approved

#15249 Fix: Fixed issue where changing focus in column view caused extra animation
  src/Files.App/Views/Layouts/ColumnLayoutPage.xaml.cs
Labels: approved

#15247 Fix: Fixed an issue where the window wasn't refocused if minimized on launch
  src/Files.App/MainWindow.xaml.cs
  src/Files.App/NativeMethods.txt
Labels: approved

#15281 Fix: Fixed issue where scroll position wasn't always in the correct position
  src/Files.App/Data/Models/ItemManipulationModel.cs
  src/Files.App/Views/Layouts/BaseGroupableLayoutPage.cs
  src/Files.App/Views/Layouts/ColumnLayoutPage.xaml.cs
  src/Files.App/Views/Layouts/DetailsLayoutPage.xaml.cs
  src/Files.App/Views/Layouts/GridLayoutPage.xaml.cs
  src/Files.App/Views/Shells/BaseShellPage.cs
Labels: approved

#14926 Code Quality: Use view models in Widgets
  src/Files.App/Data/Contexts/HomePage/HomePageContext.cs
  src/Files.App/Data/Contexts/HomePage/IHomePageContext.cs
  src/Files.App/Data/Contracts/IFileTagsService.cs
  src/Files.App/Data/Contracts/IWidgetViewModel.cs
  src/Files.App/Data/EventArguments/QuickAccessCardEventArgs.cs
  src/Files.App/Data/Factories/ShellContextFlyoutHelper.cs
  src/Files.App/Data/Items/WidgetContainerItem.cs
  src/Files.App/Data/Items/WidgetFileTagCardItem.cs
  src/Files.App/Data/Items/WidgetFileTagsContainerItem.cs
  src/Files.App/Data/Models/ListedTagViewModel.cs
  src/Files.App/Data/Models/TagViewModel.cs
  src/Files.App/GlobalUsings.cs
  src/Files.App/Helpers/Application/AppLifecycleHelper.cs
  src/Files.App/Services/Settings/FileTagsSettingsService.cs
  src/Files.App/Services/Settings/IFileTagsSettingsService.cs
  src/Files.App/Strings/en-US/Resources.resw
  src/Files.App/UserControls/Widgets/DrivesWidget.xaml
  src/Files.App/UserControls/Widgets/DrivesWidget.xaml.cs
  src/Files.App/UserControls/Widgets/FileTagsWidget.xaml
  src/Files.App/UserControls/Widgets/FileTagsWidget.xaml.cs
  src/Files.App/UserControls/Widgets/QuickAccessWidget.xaml
  src/Files.App/UserControls/Widgets/QuickAccessWidget.xaml.cs
  src/Files.App/UserControls/Widgets/RecentFilesWidget.xaml
  src/Files.App/UserControls/Widgets/RecentFilesWidget.xaml.cs
  src/Files.App/Utils/RecentItem/RecentItem.cs
  src/Files.App/Utils/Widgets/WidgetsHelpers.cs
  src/Files.App/ViewModels/HomeViewModel.cs
  src/Files.App/ViewModels/UserControls/Widgets/BaseWidgetViewModel.cs
  src/Files.App/ViewModels/UserControls/Widgets/DrivesWidgetViewModel.cs
  src/Files.App/ViewModels/UserControls/Widgets/FileTagsWidgetViewModel.cs
  src/Files.App/ViewModels/UserControls/Widgets/QuickAccessWidgetViewModel.cs
  src/Files.App/ViewModels/UserControls/Widgets/RecentFilesWidgetViewModel.cs
  src/Files.App/ViewModels/Widgets/FileTagsWidget/FileTagsContainerViewModel.cs
  src/Files.App/ViewModels/Widgets/FileTagsWidget/FileTagsItemViewModel.cs
  src/Files.App/ViewModels/Widgets/FileTagsWidget/FileTagsWidgetViewModel.cs
  src/Files.App/Views/HomePage.xaml.cs
  src/Files.App/Views/Layouts/DetailsLayoutPage.xaml
  src/Files.App/Views/Settings/TagsPage.xaml
  src/Files.App/Views/Settings/TagsPage.xaml.cs
  src/Files.App/Views/Shells/ModernShellPage.xaml.cs
Labels: approved, requires quality assurance

#15271 Fix: Fixed issue that caused shortcut keys to be displayed incorrectly in the command palette
  src/Files.App/UserControls/KeyboardShortcut/KeyboardShortcut.cs
  src/Files.App/ViewModels/UserControls/AddressToolbarViewModel.cs
Labels: needs-review

#15280 Code Quality: Use protocol launch for open and save file dialogs
  src/Files.App.OpenDialog/FilesOpenDialog.cpp
  src/Files.App.SaveDialog/FilesSaveDialog.cpp
  src/Files.App/Program.cs
Labels: approved

#15209 Code Quality: Merged all interop into Win32PInvoke
  src/Files.App/Data/Models/ItemViewModel.cs
  src/Files.App/Extensions/Win32FindDataExtensions.cs
  src/Files.App/Helpers/Environment/ElevationHelpers.cs
  src/Files.App/Helpers/Interop/NativeFileOperationsHelper.cs
  src/Files.App/Helpers/Interop/NativeWinApiHelper.cs
  src/Files.App/Helpers/Layout/AdaptiveLayoutHelpers.cs
  src/Files.App/Helpers/Layout/LayoutPreferencesManager.cs
  src/Files.App/Helpers/NativeFindStorageItemHelper.cs
  src/Files.App/Helpers/NaturalStringComparer.cs
  src/Files.App/Helpers/Navigation/NavigationHelpers.cs
  src/Files.App/Helpers/Win32/Win32Helper.Process.cs
  src/Files.App/Helpers/Win32/Win32Helper.Shell.cs
  src/Files.App/Helpers/Win32/Win32Helper.Storage.cs
  src/Files.App/Helpers/Win32/Win32PInvoke.Consts.cs
  src/Files.App/Helpers/Win32/Win32PInvoke.Enums.cs
  src/Files.App/Helpers/Win32/Win32PInvoke.Methods.cs
  src/Files.App/Helpers/Win32/Win32PInvoke.Structs.cs
  src/Files.App/Services/SideloadUpdateService.cs
  src/Files.App/Services/SizeProvider/CachedSizeProvider.cs
  src/Files.App/Utils/FileTags/FileTagsHelper.cs
  src/Files.App/Utils/Serialization/Implementation/DefaultSettingsSerializer.cs
  src/Files.App/Utils/Shell/ItemStreamHelper.cs
  src/Files.App/Utils/Shell/PreviewHandler.cs
  src/Files.App/Utils/Storage/Enumerators/Win32StorageEnumerator.cs
  src/Files.App/Utils/Storage/Helpers/FolderHelpers.cs
  src/Files.App/Utils/Storage/Helpers/StorageHelpers.cs
  src/Files.App/Utils/Storage/Operations/FileSizeCalculator.cs
  src/Files.App/Utils/Storage/Operations/FilesystemHelpers.cs
  src/Files.App/Utils/Storage/Operations/FilesystemOperations.cs
  src/Files.App/Utils/Storage/Search/FolderSearch.cs
  src/Files.App/Utils/Storage/StorageItems/NativeStorageFile.cs
  src/Files.App/Utils/Storage/StorageItems/SystemStorageFile.cs
  src/Files.App/Utils/Storage/StorageItems/VirtualStorageItem.cs
  src/Files.App/Utils/Storage/StorageItems/ZipStorageFile.cs
  src/Files.App/Utils/Storage/StorageItems/ZipStorageFolder.cs
  src/Files.App/ViewModels/Properties/Items/BaseProperties.cs
  src/Files.App/ViewModels/Properties/Items/CombinedProperties.cs
  src/Files.App/ViewModels/Properties/Items/FileProperties.cs
  src/Files.App/ViewModels/Properties/Items/FolderProperties.cs
  src/Files.App/ViewModels/Properties/Items/LibraryProperties.cs
Labels: approved

#15246 Fix: Fixed a bug where dropdown flyouts opened in the wrong location
  src/Files.App/App.xaml
  src/Files.App/UserControls/ComboBoxEx/ComboBoxEx.cs
  src/Files.App/Views/Settings/AppearancePage.xaml
  src/Files.App/Views/Settings/FoldersPage.xaml
  src/Files.App/Views/Settings/GeneralPage.xaml
  src/Files.App/Views/Settings/LayoutPage.xaml
Labels: approved

#15290 Feature: Added a theming option to display a background image
  src/Files.App/Services/Settings/AppearanceSettingsService.cs
  src/Files.App/Services/Settings/IAppearanceSettingsService.cs
  src/Files.App/Strings/en-US/Resources.resw
  src/Files.App/ViewModels/MainPageViewModel.cs
  src/Files.App/ViewModels/Settings/AppearanceViewModel.cs
  src/Files.App/Views/MainPage.xaml
  src/Files.App/Views/Settings/AppearancePage.xaml
Labels: needs-review

#15296 Code Quality: Update CsWin32 to latest version
  src/Files.App/Files.App.csproj
  src/Files.App/UserControls/TabBar/TabBar.xaml.cs
  src/Files.App/Utils/Storage/Helpers/FilePropertiesHelpers.cs
  src/Files.App/Utils/Taskbar/SystemTrayIcon.cs
Labels: approved

#15306 Code Quality: Fix horizontal alignment labels
  src/Files.App/ViewModels/Settings/AppearanceViewModel.cs
Labels: approved

#15267 Fix: Fixed an issue where the conflicts dialog didn't append numbers when pasting files
  src/Files.App/Utils/Storage/Operations/FileOperationsHelpers.cs
  src/Files.App/Utils/Storage/Operations/FilesystemHelpers.cs
Labels: approved

#15305 Fix: Fixed issue where renaming in the conflict dialog would leave the copy status in process
  src/Files.App/Utils/Storage/Operations/FilesystemHelpers.cs
Labels: approved

#15285 Code Quality: Move Resources dir to Assets
  src/Files.App/Assets/Resources/PreviewPanePropertiesInformation.json
  src/Files.App/Assets/Resources/PropertiesInformation.json
  src/Files.App/Constants.cs
  src/Files.App/Files.App.csproj
Labels: approved

#15304 Feature: Added audio bitrate to the Details Pane
  src/Files.App/Assets/Resources/PreviewPanePropertiesInformation.json
  src/Files.App/Assets/Resources/PropertiesInformation.json
  src/Files.App/Strings/en-US/Resources.resw
  src/Files.App/ViewModels/Properties/Items/CombinedFileProperties.cs
  src/Files.App/ViewModels/Properties/Items/FileProperties.cs
  src/Files.App/ViewModels/Properties/Items/FileProperty.cs
Labels: approved

#15314 Code Quality: Ignore exceptions to return default layout preferences in GetLayoutPreferencesForPath
  src/Files.App/Helpers/Layout/LayoutPreferencesManager.cs
Labels: approved

#15316 Feature: Added set as app background action
  src/Files.App/Actions/Content/Background/SetAsAppBackgroundAction.cs
  src/Files.App/Data/Commands/Manager/CommandCodes.cs
  src/Files.App/Data/Commands/Manager/CommandManager.cs
  src/Files.App/Data/Commands/Manager/ICommandManager.cs
  src/Files.App/Data/Factories/ContentPageContextFlyoutFactory.cs
  src/Files.App/Strings/en-US/Resources.resw
  src/Files.App/UserControls/InnerNavigationToolbar.xaml
Labels: needs-review

#15298 Code Quality: Use `LibraryImportAttribute` at undocumented EntryPoint
  src/Files.App/Helpers/Environment/ElevationHelpers.cs
  src/Files.App/Helpers/Win32/Win32PInvoke.Methods.cs
Labels: approved

#15321 Fix: Fixed COMException in LayoutPreferencesManager.SetLayoutPreferencesForPath
  src/Files.App/Helpers/Layout/LayoutPreferencesManager.cs
Labels: approved

#15312 Fix: Fixed an issue where "Custom" wasn't localized in the settings appearance page
  src/Files.App/ViewModels/Settings/AppearanceViewModel.cs
Labels: approved

#15324 Code Quality: Pin WinRT server object to prevent object reference being invalid
  src/Files.App.Server/AppInstanceMonitor.cs
  src/Files.App.Server/Database/FileTagsDatabase.cs
  src/Files.App.Server/Database/LayoutPreferencesDatabase.cs
  src/Files.App/Helpers/Layout/LayoutPreferencesDatabaseManager.cs
  src/Files.App/Utils/FileTags/FileTagsHelper.cs
Labels: approved

#15337 Code Quality: Use constructor instead of collection expression for the properties window cache
  src/Files.App/Utils/Storage/Helpers/FilePropertiesHelpers.cs
Labels: approved

#15347 Fix: Fixed an issue where the string for "Actions" wasn't localize in the Settings menu
  src/Files.App/Dialogs/SettingsDialog.xaml
Labels: approved

#15350 Feature: Added support for setting tif files as the Background Image
  src/Files.App/ViewModels/Settings/AppearanceViewModel.cs
Labels: needs-review

#15357 Code Quality: Moving registry database to Files.App
  src/Files.App (Package)/Package.appxmanifest
  src/Files.App.Server/Data/ColumnPreferences.cs
  src/Files.App.Server/Data/ColumnPreferencesItem.cs
  src/Files.App.Server/Data/LayoutPreferencesItem.cs
  src/Files.App.Server/Data/TaggedFile.cs
  src/Files.App.Server/Files.App.Server.csproj
  src/Files.App/Actions/Display/GroupAction.cs
  src/Files.App/Actions/Display/SortAction.cs
  src/Files.App/Data/Contexts/DisplayPage/DisplayPageContext.cs
  src/Files.App/Data/Contexts/DisplayPage/IDisplayPageContext.cs
  src/Files.App/Data/Enums/FolderLayoutModes.cs
  src/Files.App/Data/Enums/GroupByDateUnit.cs
  src/Files.App/Data/Enums/GroupOption.cs
  src/Files.App/Data/Enums/SortDirection.cs
  src/Files.App/Data/Enums/SortOption.cs
  src/Files.App/Data/EventArguments/LayoutModeEventArgs.cs
  src/Files.App/Data/Items/DetailsLayoutColumnItem.cs
  src/Files.App/Data/Models/ColumnsViewModel.cs
  src/Files.App/Data/Models/CurrentInstanceViewModel.cs
  src/Files.App/Data/Models/ItemViewModel.cs
  src/Files.App/Extensions/GroupOptionExtensions.cs
  src/Files.App/Files.App.csproj
  src/Files.App/Helpers/Layout/LayoutPreferencesDatabase.cs
  src/Files.App/Helpers/Layout/LayoutPreferencesDatabaseItem.cs
  src/Files.App/Helpers/Layout/LayoutPreferencesDatabaseManager.cs
  src/Files.App/Helpers/Layout/LayoutPreferencesItem.cs
  src/Files.App/Helpers/Layout/LayoutPreferencesManager.cs
  src/Files.App/Helpers/Navigation/NavigationHelpers.cs
  src/Files.App/Helpers/RegistryHelpers.cs
  src/Files.App/Services/DateTimeFormatter/AbstractDateTimeFormatter.cs
  src/Files.App/Services/DateTimeFormatter/IDateTimeFormatter.cs
  src/Files.App/Services/DateTimeFormatter/UserDateTimeFormatter.cs
  src/Files.App/Services/Settings/FoldersSettingsService.cs
  src/Files.App/Services/Settings/IFoldersSettingsService.cs
  src/Files.App/Services/Settings/ILayoutSettingsService.cs
  src/Files.App/Services/Settings/LayoutSettingsService.cs
  src/Files.App/UserControls/DataGridHeader.xaml.cs
  src/Files.App/Utils/FileTags/FileTagsDatabase.cs
  src/Files.App/Utils/FileTags/FileTagsHelper.cs
  src/Files.App/Utils/FileTags/TaggedFile.cs
  src/Files.App/Utils/Storage/Collection/GroupingHelper.cs
  src/Files.App/Utils/Storage/Collection/SortingHelper.cs
  src/Files.App/ViewModels/Settings/FoldersViewModel.cs
  src/Files.App/ViewModels/Settings/LayoutViewModel.cs
  src/Files.App/ViewModels/UserControls/AddressToolbarViewModel.cs
  src/Files.App/Views/Layouts/BaseGroupableLayoutPage.cs
  src/Files.App/Views/Layouts/BaseLayoutPage.cs
  src/Files.App/Views/Layouts/ColumnLayoutPage.xaml.cs
  src/Files.App/Views/Layouts/DetailsLayoutPage.xaml.cs
  src/Files.App/Views/Layouts/GridLayoutPage.xaml.cs
  src/Files.App/Views/Shells/BaseShellPage.cs
  src/Files.App/Views/Shells/ColumnShellPage.xaml.cs
  src/Files.Core.SourceGenerator/RegistrySerializationGenerator.cs
  src/Files.Shared/Attributes/RegistrySerializableAttribute.cs
Labels: approved

#15377 Feature: Added toolbar button to play mkv files
  src/Files.Shared/Helpers/FileExtensionHelpers.cs
Labels: approved

#15376 Feature: Updated the wording of the "Files is running as admin" prompt
  src/Files.App/Strings/en-US/Resources.resw
Labels: needs-review

#15383 Fix: Fixed crash when connecting some removable drives
  src/Files.App/Utils/Global/WindowsStorageDeviceWatcher.cs
Labels: approved

#15385 Code Quality: Switch DirectN to CsWin32
  src/Files.App/Files.App.csproj
  src/Files.App/NativeMethods.txt
  src/Files.App/ViewModels/UserControls/Previews/ShellPreviewViewModel.cs
Labels: needs-review

#15339 Feature: Added support for SeerPro's "Track selected file" setting
  src/Files.App/Services/PreviewPopupProviders/SeerProProvider.cs
Labels: needs-review

#15387 Code Quality: Gave priority to registry when loading Seer Pro settings
  src/Files.App/Services/PreviewPopupProviders/SeerProProvider.cs
Labels: approved

#15388 Feature: Added support for displaying all network folders on the sidebar
  src/Files.App/Data/Contracts/INetworkDrivesService.cs
  src/Files.App/Data/Items/DriveItem.cs
  src/Files.App/Services/NetworkDrivesService.cs
Labels: approved

#15391 Fix: Fixed an issue where the theme mode change would cause a crash
  src/Files.App/Services/AppThemeModeService.cs
Labels: approved

#15401 Fix: Fixed NullReferenceException in FilePropertiesHelpers.DestroyCachedWindows
  src/Files.App/Utils/Storage/Helpers/FilePropertiesHelpers.cs
Labels: approved

#15405 Code Quality: Add Dummy update service for dev builds
  src/Files.App/Helpers/Application/AppLifecycleHelper.cs
  src/Files.App/Services/DummyUpdateService.cs
  src/Files.App/Services/StoreUpdateService.cs
Labels: approved

#15394 Feature: Added a setting to configure the "Open in ide" button on the status bar
  src/Files.App/Data/Enums/OpenInIDEOption.cs
  src/Files.App/Data/Enums/SettingsPageKind.cs
  src/Files.App/Data/Models/DirectoryPropertiesViewModel.cs
  src/Files.App/Dialogs/SettingsDialog.xaml
  src/Files.App/Dialogs/SettingsDialog.xaml.cs
  src/Files.App/Helpers/Application/AppLifecycleHelper.cs
  src/Files.App/Services/Settings/DevToolsSettingsService.cs
  src/Files.App/Services/Settings/IDevToolsSettingsService.cs
  src/Files.App/Strings/en-US/Resources.resw
  src/Files.App/UserControls/StatusBar.xaml
  src/Files.App/UserControls/StatusBar.xaml.cs
  src/Files.App/ViewModels/Settings/DevToolsViewModel.cs
  src/Files.App/Views/HomePage.xaml.cs
  src/Files.App/Views/Layouts/BaseLayoutPage.cs
  src/Files.App/Views/Layouts/IBaseLayoutPage.cs
  src/Files.App/Views/MainPage.xaml.cs
  src/Files.App/Views/Settings/DevToolsPage.xaml
  src/Files.App/Views/Settings/DevToolsPage.xaml.cs
  src/Files.App/Views/Shells/BaseShellPage.cs
  tests/Files.InteractionTests/Tests/SettingsTests.cs
Labels: approved

#15368 Code Quality: Introduce flexible pane generation 1
  src/Files.App/Constants.cs
  src/Files.App/Data/Contexts/ContentPage/ContentPageContext.cs
  src/Files.App/Data/Contexts/DisplayPage/DisplayPageContext.cs
  src/Files.App/Data/Contexts/MultiPanes/IMultiPanesContext.cs
  src/Files.App/Data/Contexts/MultiPanes/MultiPanesContext.cs
  src/Files.App/Data/Contexts/Page/IPageContext.cs
  src/Files.App/Data/Contexts/Page/PageContext.cs
  src/Files.App/Data/Contracts/IMultiPaneInfo.cs
  src/Files.App/Data/Contracts/IPanesPage.cs
  src/Files.App/Data/Contracts/IShellPage.cs
  src/Files.App/Data/Parameters/TabBarItemParameter.cs
  src/Files.App/Helpers/Application/AppLifecycleHelper.cs
  src/Files.App/Helpers/Navigation/MultitaskingTabsHelpers.cs
  src/Files.App/Helpers/Navigation/NavigationHelpers.cs
  src/Files.App/MainWindow.xaml.cs
  src/Files.App/UserControls/TabBar/BaseTabBar.cs
  src/Files.App/UserControls/TabBar/ITabBarItem.cs
  src/Files.App/UserControls/TabBar/ITabBarItemContent.cs
  src/Files.App/UserControls/TabBar/TabBar.xaml.cs
  src/Files.App/UserControls/TabBar/TabBarItem.cs
  src/Files.App/ViewModels/MainPageViewModel.cs
  src/Files.App/ViewModels/UserControls/SidebarViewModel.cs
  src/Files.App/Views/Layouts/ColumnsLayoutPage.xaml.cs
  src/Files.App/Views/MainPage.xaml.cs
  src/Files.App/Views/PaneHolderPage.xaml.cs
  src/Files.App/Views/Shells/BaseShellPage.cs
  src/Files.App/Views/Shells/ColumnShellPage.xaml.cs
  src/Files.App/Views/Shells/ModernShellPage.xaml.cs
Labels: approved

#15406 Feature: Added support for "Thin acrylic" system backdrop
  src/Files.App/Data/Enums/BackdropMaterialType.cs
  src/Files.App/Helpers/UI/AppSystemBackdrop.cs
  src/Files.App/Strings/en-US/Resources.resw
  src/Files.App/ViewModels/Settings/AppearanceViewModel.cs
Labels: approved

#15416 Feature: Close settings dialog when opening the log location
  src/Files.App/ViewModels/Settings/AboutViewModel.cs
Labels: approved

#15386 Code Quality: Introduced ICommonDialogService
  src/Files.App/Data/Contracts/ICommonDialogService.cs
  src/Files.App/Data/Contracts/IFileExplorerService.cs
  src/Files.App/Data/Models/NetworkConnectionDialog.cs
  src/Files.App/Helpers/Application/AppLifecycleHelper.cs
  src/Files.App/NativeMethods.txt
  src/Files.App/Services/CommonDialogService.cs
  src/Files.App/Services/FileExplorerService.cs
  src/Files.App/Services/NetworkDrivesService.cs
  src/Files.App/Strings/en-US/Resources.resw
  src/Files.App/ViewModels/Dialogs/CreateShortcutDialogViewModel.cs
  src/Files.App/ViewModels/Dialogs/DecompressArchiveDialogViewModel.cs
  src/Files.App/ViewModels/Properties/BasePropertiesPage.cs
  src/Files.App/ViewModels/Properties/CustomizationViewModel.cs
  src/Files.App/ViewModels/Settings/AdvancedViewModel.cs
  src/Files.App/ViewModels/Settings/AppearanceViewModel.cs
  src/Files.App/ViewModels/Settings/GeneralViewModel.cs
  src/Files.App/Views/Properties/LibraryPage.xaml.cs
Labels: approved

#15417 Feature: Added "Run as admin" support for AHK files
  src/Files.Shared/Helpers/FileExtensionHelpers.cs
Labels: needs-code review

#15419 Feature: Updated the Status Bar design
  src/Files.App/UserControls/Pane/InfoPane.xaml
  src/Files.App/UserControls/SideBar/SideBarView.properties.cs
  src/Files.App/UserControls/SideBar/SideBarView.xaml
  src/Files.App/UserControls/SideBar/SideBarView.xaml.cs
  src/Files.App/Views/MainPage.xaml
  src/Files.App/Views/PaneHolderPage.xaml
Labels: needs-code review

#15421 Feature: Added a tooltip when hovering over OneDrive status icons
  src/Files.App/Views/Layouts/ColumnLayoutPage.xaml
  src/Files.App/Views/Layouts/DetailsLayoutPage.xaml
  src/Files.App/Views/Layouts/GridLayoutPage.xaml
Labels: ready to merge

#15429 Feature: Added an action to edit "Batch" files in Notepad
  src/Files.App/Actions/Open/EditInNotepadAction.cs
  src/Files.App/Data/Commands/Manager/CommandCodes.cs
  src/Files.App/Data/Commands/Manager/CommandManager.cs
  src/Files.App/Data/Commands/Manager/ICommandManager.cs
  src/Files.App/Strings/en-US/Resources.resw
  src/Files.App/UserControls/InnerNavigationToolbar.xaml
  src/Files.Shared/Helpers/FileExtensionHelpers.cs
Labels: ready to merge

#15428 Code Quality: Disable run as user for AHK files
  src/Files.App/Actions/Content/Run/BaseRunAsAction.cs
  src/Files.App/Actions/Content/Run/RunAsAdminAction.cs
  src/Files.App/Actions/Content/Run/RunAsAnotherUserAction.cs
  src/Files.Shared/Helpers/FileExtensionHelpers.cs
Labels: ready to merge

#15435 Feature: Added "Edit in notepad" action to the right click context menu
  src/Files.App/Actions/Content/Run/RunAsAdminAction.cs
  src/Files.App/Actions/Content/Run/RunAsAnotherUserAction.cs
  src/Files.App/Actions/FileSystem/CreateFolderWithSelectionAction.cs
  src/Files.App/Actions/Open/EditInNotepadAction.cs
  src/Files.App/Data/Factories/ContentPageContextFlyoutFactory.cs
  src/Files.Shared/Helpers/FileExtensionHelpers.cs
Labels: ready to merge

#15433 Code Quality: Adding the possibility of plural translation using ICU format
  src/Files.App/Extensions/MessageFormatExtensions.cs
  src/Files.App/Files.App.csproj
  src/Files.App/Strings/en-US/Resources.resw
  src/Files.App/Views/Layouts/BaseLayoutPage.cs
  src/Files.App/Views/Shells/BaseShellPage.cs
Labels: ready to merge

#15341 Code Quality: Introduced IStorageArchiveService
  src/Files.App/Actions/Content/Archives/Compress/BaseCompressArchiveAction.cs
  src/Files.App/Actions/Content/Archives/Compress/CompressIntoArchiveAction.cs
  src/Files.App/Actions/Content/Archives/Compress/CompressIntoSevenZipAction.cs
  src/Files.App/Actions/Content/Archives/Compress/CompressIntoZipAction.cs
  src/Files.App/Actions/Content/Archives/Decompress/BaseDecompressArchiveAction.cs
  src/Files.App/Actions/Content/Archives/Decompress/DecompressArchive.cs
  src/Files.App/Actions/Content/Archives/Decompress/DecompressArchiveHere.cs
  src/Files.App/Actions/Content/Archives/Decompress/DecompressArchiveHereSmart.cs
  src/Files.App/Actions/Content/Archives/Decompress/DecompressArchiveToChildFolderAction.cs
  src/Files.App/Data/Contracts/ICompressArchiveModel.cs
  src/Files.App/Data/Contracts/IStorageArchiveService.cs
  src/Files.App/Data/Factories/ContentPageContextFlyoutFactory.cs
  src/Files.App/Data/Models/CompressArchiveModel.cs
  src/Files.App/GlobalUsings.cs
  src/Files.App/Helpers/Application/AppLifecycleHelper.cs
  src/Files.App/Services/Storage/StorageArchiveService.cs
  src/Files.App/Services/Storage/StorageCacheService.cs
  src/Files.App/Utils/Archives/CompressHelper.cs
  src/Files.App/Utils/Archives/DecompressHelper.cs
Labels: ready to merge

#15446 Code Quality: Changed default settings for Network locations widget
  src/Files.App/Services/Settings/GeneralSettingsService.cs
  src/Files.App/ViewModels/HomeViewModel.cs
Labels: ready to merge

#15442 Feature: Updated the Toolbar design
  src/Files.App/App.xaml
  src/Files.App/Data/Contracts/IResourcesService.cs
  src/Files.App/Helpers/UI/AppThemeResourcesHelper.cs
  src/Files.App/Services/ResourcesService.cs
  src/Files.App/Services/Settings/AppearanceSettingsService.cs
  src/Files.App/Services/Settings/IAppearanceSettingsService.cs
  src/Files.App/UserControls/InnerNavigationToolbar.xaml
  src/Files.App/UserControls/SideBar/SideBarView.properties.cs
  src/Files.App/UserControls/SideBar/SideBarView.xaml
  src/Files.App/UserControls/StatusBar.xaml
  src/Files.App/Views/MainPage.xaml
  src/Files.App/Views/MainPage.xaml.cs
Labels: ready to merge

#15451 Code Quality: Moved toolbar background to MainPage
  src/Files.App/UserControls/SideBar/SideBarView.xaml
  src/Files.App/Views/MainPage.xaml
Labels: ready to merge

#15448 Fix: Fixed formatting bug when entering commands into the Address Bar
  src/Files.App/ViewModels/UserControls/AddressToolbarViewModel.cs
Labels: needs-code review

#15445 Fix: Fixed an issue with Nutstore cloud drive detection
  src/Files.App/Utils/Cloud/CloudDrivesDetector.cs
Labels: ready to merge

#15456 Feature: Updated the design of the Preview Pane
  src/Files.App/App.xaml
  src/Files.App/Data/Contracts/IResourcesService.cs
  src/Files.App/Helpers/UI/AppThemeResourcesHelper.cs
  src/Files.App/Services/ResourcesService.cs
  src/Files.App/Services/Settings/AppearanceSettingsService.cs
  src/Files.App/Services/Settings/IAppearanceSettingsService.cs
  src/Files.App/UserControls/SideBar/SideBarView.properties.cs
  src/Files.App/UserControls/SideBar/SideBarView.xaml
  src/Files.App/UserControls/SideBar/SideBarView.xaml.cs
  src/Files.App/Views/MainPage.xaml
  src/Files.App/Views/MainPage.xaml.cs
Labels: needs-code review

#15443 Code Quality: Created a language helper to work with the global language of the application
  src/Files.App/Data/Items/AppLanguageItem.cs
  src/Files.App/Extensions/MessageFormatExtensions.cs
  src/Files.App/Helpers/Application/AppLanguageHelper.cs
  src/Files.App/Services/DateTimeFormatter/AbstractDateTimeFormatter.cs
  src/Files.App/ViewModels/Settings/GeneralViewModel.cs
  src/Files.App/Views/Properties/CustomizationPage.xaml
  src/Files.App/Views/Settings/GeneralPage.xaml
Labels: needs-code review

#15420 Fix: Fixed an issue where it didn't work to map certain keys to Actions
  src/Files.App/Data/Commands/HotKey/HotKey.cs
  src/Files.App/Data/Commands/HotKey/Keys.cs
  src/Files.App/Data/Items/ModifiableActionItem.cs
  src/Files.App/Helpers/Win32/Win32PInvoke.Methods.cs
  src/Files.App/Helpers/Win32/Win32PInvoke.Structs.cs
  src/Files.App/Strings/en-US/Resources.resw
  src/Files.App/UserControls/KeyboardShortcut/KeyboardShortcut.xaml
  src/Files.App/ViewModels/Settings/ActionsViewModel.cs
  src/Files.App/Views/Settings/ActionsPage.xaml
  src/Files.App/Views/Settings/ActionsPage.xaml.cs
Labels: ready to merge

#15459 Fix: Fixed an issue with launching programs from the Address Bar
  src/Files.App/ViewModels/UserControls/AddressToolbarViewModel.cs
Labels: ready to merge

#15466 Fix: Fixed NullReferenceException in QuickAccessWidgetViewModel.NavigateToPath
  src/Files.App/ViewModels/UserControls/Widgets/QuickAccessWidgetViewModel.cs
Labels: ready to merge

#15467 Fix: Fixed NullReferenceException in BaseDeleteAction.DeleteItemsAsync
  src/Files.App/Actions/FileSystem/BaseDeleteAction.cs
Labels: ready to merge

#15474 Fix: Fixed issue where search result stopped showing when switching tabs
  src/Files.App/Views/Shells/BaseShellPage.cs
Labels: ready to merge

#15471 Fix: Fixed an issue where import/export settings didn't work
  src/Files.App/ViewModels/Settings/AdvancedViewModel.cs
Labels: ready to merge

#15476 Feature: Added support for displaying total duration when selecting multiple video files
  src/Files.App/ViewModels/Properties/Items/CombinedFileProperties.cs
Labels: ready to merge

#15469 Feature: Updated the design for Dual Pane mode
  src/Files.App/App.xaml
  src/Files.App/Data/Contracts/IResourcesService.cs
  src/Files.App/Helpers/UI/AppThemeResourcesHelper.cs
  src/Files.App/Services/ResourcesService.cs
  src/Files.App/Services/Settings/AppearanceSettingsService.cs
  src/Files.App/Services/Settings/IAppearanceSettingsService.cs
  src/Files.App/Views/MainPage.xaml
  src/Files.App/Views/MainPage.xaml.cs
  src/Files.App/Views/PaneHolderPage.xaml
  src/Files.App/Views/PaneHolderPage.xaml.cs
  src/Files.App/Views/Shells/BaseShellPage.cs
  src/Files.App/Views/Shells/ColumnShellPage.xaml
  src/Files.App/Views/Shells/ModernShellPage.xaml
  src/Files.App/Views/Shells/ModernShellPage.xaml.cs
Labels: ready to merge

#15481 Fix: Fixed Column View chevron color in high contrast
  src/Files.App/UserControls/Pane/InfoPane.xaml
  src/Files.App/Views/Layouts/ColumnLayoutPage.xaml
Labels: ready to merge

#15482 Code Quality: Change active pane border thickness in high contrast
  src/Files.App/Views/PaneHolderPage.xaml.cs
  src/Files.App/Views/Shells/ModernShellPage.xaml
Labels: ready to merge

#15487 Fix: Fixed app icon in High Contrast
  src/Files.App (Package)/Assets/AppTiles/Dev/contrast-black/Square44x44Logo.targetsize-16_altform-unplated_contrast-black.png
  src/Files.App (Package)/Assets/AppTiles/Dev/contrast-black/Square44x44Logo.targetsize-20_altform-unplated_contrast-black.png
  src/Files.App (Package)/Assets/AppTiles/Dev/contrast-black/Square44x44Logo.targetsize-24_altform-unplated_contrast-black.png
  src/Files.App (Package)/Assets/AppTiles/Dev/contrast-black/Square44x44Logo.targetsize-256_altform-unplated_contrast-black.png
  src/Files.App (Package)/Assets/AppTiles/Dev/contrast-black/Square44x44Logo.targetsize-30_altform-unplated_contrast-black.png
  src/Files.App (Package)/Assets/AppTiles/Dev/contrast-black/Square44x44Logo.targetsize-32_altform-unplated_contrast-black.png
  src/Files.App (Package)/Assets/AppTiles/Dev/contrast-black/Square44x44Logo.targetsize-36_altform-unplated_contrast-black.png
  src/Files.App (Package)/Assets/AppTiles/Dev/contrast-black/Square44x44Logo.targetsize-40_altform-unplated_contrast-black.png
  src/Files.App (Package)/Assets/AppTiles/Dev/contrast-black/Square44x44Logo.targetsize-48_altform-unplated_contrast-black.png
  src/Files.App (Package)/Assets/AppTiles/Dev/contrast-black/Square44x44Logo.targetsize-60_altform-unplated_contrast-black.png
  src/Files.App (Package)/Assets/AppTiles/Dev/contrast-black/Square44x44Logo.targetsize-64_altform-unplated_contrast-black.png
  src/Files.App (Package)/Assets/AppTiles/Dev/contrast-black/Square44x44Logo.targetsize-72_altform-unplated_contrast-black.png
  src/Files.App (Package)/Assets/AppTiles/Dev/contrast-black/Square44x44Logo.targetsize-80_altform-unplated_contrast-black.png
  src/Files.App (Package)/Assets/AppTiles/Dev/contrast-black/Square44x44Logo.targetsize-96_altform-unplated_contrast-black.png
  src/Files.App (Package)/Assets/AppTiles/Preview/contrast-black/Square44x44Logo.targetsize-16_altform-unplated_contrast-black.png
  src/Files.App (Package)/Assets/AppTiles/Preview/contrast-black/Square44x44Logo.targetsize-20_altform-unplated_contrast-black.png
  src/Files.App (Package)/Assets/AppTiles/Preview/contrast-black/Square44x44Logo.targetsize-24_altform-unplated_contrast-black.png
  src/Files.App (Package)/Assets/AppTiles/Preview/contrast-black/Square44x44Logo.targetsize-256_altform-unplated_contrast-black.png
  src/Files.App (Package)/Assets/AppTiles/Preview/contrast-black/Square44x44Logo.targetsize-30_altform-unplated_contrast-black.png
  src/Files.App (Package)/Assets/AppTiles/Preview/contrast-black/Square44x44Logo.targetsize-32_altform-unplated_contrast-black.png
  src/Files.App (Package)/Assets/AppTiles/Preview/contrast-black/Square44x44Logo.targetsize-36_altform-unplated_contrast-black.png
  src/Files.App (Package)/Assets/AppTiles/Preview/contrast-black/Square44x44Logo.targetsize-40_altform-unplated_contrast-black.png
  src/Files.App (Package)/Assets/AppTiles/Preview/contrast-black/Square44x44Logo.targetsize-48_altform-unplated_contrast-black.png
  src/Files.App (Package)/Assets/AppTiles/Preview/contrast-black/Square44x44Logo.targetsize-60_altform-unplated_contrast-black.png
  src/Files.App (Package)/Assets/AppTiles/Preview/contrast-black/Square44x44Logo.targetsize-64_altform-unplated_contrast-black.png
  src/Files.App (Package)/Assets/AppTiles/Preview/contrast-black/Square44x44Logo.targetsize-72_altform-unplated_contrast-black.png
  src/Files.App (Package)/Assets/AppTiles/Preview/contrast-black/Square44x44Logo.targetsize-80_altform-unplated_contrast-black.png
  src/Files.App (Package)/Assets/AppTiles/Preview/contrast-black/Square44x44Logo.targetsize-96_altform-unplated_contrast-black.png
  src/Files.App (Package)/Assets/AppTiles/Release/contrast-black/Square44x44Logo.targetsize-16_altform-unplated_contrast-black.png
  src/Files.App (Package)/Assets/AppTiles/Release/contrast-black/Square44x44Logo.targetsize-20_altform-unplated_contrast-black.png
  src/Files.App (Package)/Assets/AppTiles/Release/contrast-black/Square44x44Logo.targetsize-24_altform-unplated_contrast-black.png
  src/Files.App (Package)/Assets/AppTiles/Release/contrast-black/Square44x44Logo.targetsize-256_altform-unplated_contrast-black.png
  src/Files.App (Package)/Assets/AppTiles/Release/contrast-black/Square44x44Logo.targetsize-30_altform-unplated_contrast-black.png
  src/Files.App (Package)/Assets/AppTiles/Release/contrast-black/Square44x44Logo.targetsize-32_altform-unplated_contrast-black.png
  src/Files.App (Package)/Assets/AppTiles/Release/contrast-black/Square44x44Logo.targetsize-36_altform-unplated_contrast-black.png
  src/Files.App (Package)/Assets/AppTiles/Release/contrast-black/Square44x44Logo.targetsize-40_altform-unplated_contrast-black.png
  src/Files.App (Package)/Assets/AppTiles/Release/contrast-black/Square44x44Logo.targetsize-48_altform-unplated_contrast-black.png
  src/Files.App (Package)/Assets/AppTiles/Release/contrast-black/Square44x44Logo.targetsize-60_altform-unplated_contrast-black.png
  src/Files.App (Package)/Assets/AppTiles/Release/contrast-black/Square44x44Logo.targetsize-64_altform-unplated_contrast-black.png
  src/Files.App (Package)/Assets/AppTiles/Release/contrast-black/Square44x44Logo.targetsize-72_altform-unplated_contrast-black.png
  src/Files.App (Package)/Assets/AppTiles/Release/contrast-black/Square44x44Logo.targetsize-80_altform-unplated_contrast-black.png
  src/Files.App (Package)/Assets/AppTiles/Release/contrast-black/Square44x44Logo.targetsize-96_altform-unplated_contrast-black.png
Labels: ready to merge

#15490 Code Quality: Fixed an issue where the forward icon was wrongly clipped
  src/Files.App/Views/Shells/ModernShellPage.xaml
Labels: ready to merge

#15514 Code Quality: Convert Multiple Localized Strings to ICU Message Format | Stage Three
  src/Files.App/Strings/en-US/Resources.resw
  src/Files.App/ViewModels/Properties/Items/BaseProperties.cs
  src/Files.App/ViewModels/UserControls/Previews/ArchivePreviewViewModel.cs
Labels: ready to merge

#15517 Code Quality: Convert Multiple Localized Strings to ICU Message Format | Add custom number format
  src/Files.App/Extensions/MessageFormatExtensions.cs
Labels: ready to merge

#15493 Fix: Fixed an issue where panes couldn't be switched via touch
  src/Files.App/Views/PaneHolderPage.xaml.cs
Labels: ready to merge
