Repository files-community/Files, pull requests merged in 2025-04, with the labels that each got.

#17004 Feature: Added option to open settings file when right clicking settings button
  src/Files.App/Actions/Open/OpenSettingsFileAction.cs
  src/Files.App/Data/Commands/Manager/CommandCodes.cs
  src/Files.App/Data/Commands/Manager/CommandManager.cs
  src/Files.App/Data/Commands/Manager/ICommandManager.cs
  src/Files.App/Strings/en-US/Resources.resw
  src/Files.App/ViewModels/Settings/AdvancedViewModel.cs
  src/Files.App/Views/MainPage.xaml
  src/Files.App/Views/MainPage.xaml.cs
  src/Files.App/Views/Settings/AdvancedPage.xaml
Labels: needs - code review

#16996 Feature: Added support for changing the size format
  src/Files.App/Data/Contracts/IFoldersSettingsService.cs
  src/Files.App/Data/Enums/SizeUnitTypes.cs
  src/Files.App/Data/Models/ByteSize.cs
  src/Files.App/Extensions/StringExtensions.cs
  src/Files.App/Services/Settings/FoldersSettingsService.cs
  src/Files.App/Strings/en-US/Resources.resw
  src/Files.App/ViewModels/Settings/FoldersViewModel.cs
  src/Files.App/ViewModels/ShellViewModel.cs
  src/Files.App/ViewModels/UserControls/Widgets/DrivesWidgetViewModel.cs
  src/Files.App/Views/Settings/FoldersPage.xaml
Labels: needs - code review

#16973 Code Quality: Brushed up Omnibar and BreadcrumbBar
  Settings.XamlStyler
  src/Files.App.Controls/BreadcrumbBar/BreadcrumbBar.cs
  src/Files.App.Controls/BreadcrumbBar/BreadcrumbBar.xaml
  src/Files.App.Controls/BreadcrumbBar/BreadcrumbBarItem.cs
  src/Files.App.Controls/BreadcrumbBar/BreadcrumbBarLayout.cs
  src/Files.App.Controls/BreadcrumbBar/EventArgs.cs
  src/Files.App.Controls/Omnibar/EventArgs.cs
  src/Files.App.Controls/Omnibar/IOmnibarTextMemberPathProvider.cs
  src/Files.App.Controls/Omnibar/Omnibar.Events.cs
  src/Files.App.Controls/Omnibar/Omnibar.Properties.cs
  src/Files.App.Controls/Omnibar/Omnibar.cs
  src/Files.App.Controls/Omnibar/Omnibar.xaml
  src/Files.App.Controls/Omnibar/OmnibarMode.Events.cs
  src/Files.App.Controls/Omnibar/OmnibarMode.Properties.cs
  src/Files.App.Controls/Omnibar/OmnibarMode.cs
  src/Files.App.Controls/Omnibar/OmnibarMode.xaml
  src/Files.App.Controls/Omnibar/OmnibarModeSeparator.cs
  src/Files.App.Controls/Omnibar/OmnibarTextChangeReason.cs
  src/Files.App.Controls/ThemedIcon/ThemedIconMarkup.cs
  src/Files.App.Controls/Themes/Generic.xaml
  tests/Files.App.UITests/Data/BreadcrumbBarItemModel.cs
  tests/Files.App.UITests/Data/DummyItem1.cs
  tests/Files.App.UITests/Data/OmnibarPaletteSuggestionItem.cs
  tests/Files.App.UITests/Views/BreadcrumbBarPage.xaml
  tests/Files.App.UITests/Views/BreadcrumbBarPage.xaml.cs
  tests/Files.App.UITests/Views/OmnibarPage.xaml
  tests/Files.App.UITests/Views/OmnibarPage.xaml.cs
Labels: ready to merge

#17016 Feature: Replaced Release Notes dialog with dedicated tab
  src/Files.App/Actions/Content/Archives/Compress/BaseCompressArchiveAction.cs
  src/Files.App/Actions/Content/Archives/Decompress/BaseDecompressArchiveAction.cs
  src/Files.App/Actions/Content/Background/BaseSetAsAction.cs
  src/Files.App/Actions/Content/ImageManipulation/BaseRotateAction.cs
  src/Files.App/Actions/FileSystem/CopyPathAction.cs
  src/Files.App/Actions/FileSystem/CopyPathWithQuotesAction.cs
  src/Files.App/Actions/FileSystem/PasteItemAction.cs
  src/Files.App/Actions/FileSystem/PasteItemAsShortcutAction.cs
  src/Files.App/Actions/FileSystem/PasteItemToSelectionAction.cs
  src/Files.App/Actions/FileSystem/RenameAction.cs
  src/Files.App/Actions/Open/OpenReleaseNotesAction.cs
  src/Files.App/Actions/Open/OpenTerminalAction.cs
  src/Files.App/Data/Contexts/ContentPage/ContentPageContext.cs
  src/Files.App/Data/Contexts/ContentPage/ContentPageTypes.cs
  src/Files.App/Data/Contracts/IShellPage.cs
  src/Files.App/Data/Items/LocationItem.cs
  src/Files.App/Data/Models/CurrentInstanceViewModel.cs
  src/Files.App/Dialogs/ReleaseNotesDialog.xaml
  src/Files.App/Dialogs/ReleaseNotesDialog.xaml.cs
  src/Files.App/Helpers/Application/AppLifecycleHelper.cs
  src/Files.App/Helpers/Navigation/NavigationHelpers.cs
  src/Files.App/Services/App/AppDialogService.cs
  src/Files.App/Strings/en-US/Resources.resw
  src/Files.App/UserControls/NavigationToolbar.xaml
  src/Files.App/Utils/Shell/ShellHelpers.cs
  src/Files.App/Utils/Storage/Helpers/StorageFileExtensions.cs
  src/Files.App/ViewModels/Dialogs/ReleaseNotesDialogViewModel.cs
  src/Files.App/ViewModels/MainPageViewModel.cs
  src/Files.App/ViewModels/ReleaseNotesViewModel.cs
  src/Files.App/ViewModels/ShellViewModel.cs
  src/Files.App/ViewModels/UserControls/NavigationToolbarViewModel.cs
  src/Files.App/ViewModels/UserControls/SidebarViewModel.cs
  src/Files.App/Views/HomePage.xaml.cs
  src/Files.App/Views/Layouts/BaseLayoutPage.cs
  src/Files.App/Views/MainPage.xaml
  src/Files.App/Views/ReleaseNotesPage.xaml
  src/Files.App/Views/ReleaseNotesPage.xaml.cs
  src/Files.App/Views/Shells/BaseShellPage.cs
  src/Files.App/Views/Shells/ColumnShellPage.xaml.cs
  src/Files.App/Views/Shells/ModernShellPage.xaml.cs
Labels: needs - code review

#17018 Code Quality: Added setting to enable Omnibar
  src/Files.App/Data/Contracts/IGeneralSettingsService.cs
  src/Files.App/Services/Settings/GeneralSettingsService.cs
  src/Files.App/Strings/en-US/Resources.resw
  src/Files.App/UserControls/NavigationToolbar.xaml
  src/Files.App/ViewModels/Settings/AdvancedViewModel.cs
  src/Files.App/ViewModels/UserControls/NavigationToolbarViewModel.cs
  src/Files.App/Views/Settings/AdvancedPage.xaml
Labels: ready to merge

#16812 Fix: Fixed performance issue with SMB shares
  src/Files.App/Services/Storage/StorageNetworkService.cs
  src/Files.App/Utils/Storage/Helpers/DriveHelpers.cs
  src/Files.App/ViewModels/ShellViewModel.cs
  src/Files.Shared/Helpers/PathHelpers.cs
Labels: needs - code review

#17020 Code Quality: Converted the 'Hidden items' icon to a PathIcon
  src/Files.App/Styles/PathIcons.xaml
  src/Files.App/Views/Settings/FoldersPage.xaml
Labels: changes requested

#17026 Feature: Use UTF-8 encoding for ZIP creation to ensure cross-language compatibility
  src/Files.App/Data/Models/CompressArchiveModel.cs
  src/Files.App/Utils/Storage/StorageItems/ZipStorageFile.cs
  src/Files.App/Utils/Storage/StorageItems/ZipStorageFolder.cs
Labels: ready to merge

#17012 Fix: Fixed sorting issues with #-# numbered files
  .github/NOTICE.md
  src/Files.App/Helpers/NaturalStringComparer.cs
  src/Files.App/ViewModels/Settings/AboutViewModel.cs
Labels: ready to merge

#17022 Feature: Added support for selecting encoding when extracting ZIP files
  Directory.Packages.props
  src/Files.App/Actions/Content/Archives/Decompress/DecompressArchive.cs
  src/Files.App/Data/Contracts/IStorageArchiveService.cs
  src/Files.App/Data/Items/EncodingItem.cs
  src/Files.App/Dialogs/DecompressArchiveDialog.xaml
  src/Files.App/Files.App.csproj
  src/Files.App/Program.cs
  src/Files.App/Services/Storage/StorageArchiveService.cs
  src/Files.App/Strings/en-US/Resources.resw
  src/Files.App/ViewModels/Dialogs/DecompressArchiveDialogViewModel.cs
Labels: ready to merge

#17032 Fix: Fixed issue where toolbar button sometimes had the wrong icon state
  src/Files.App/Actions/Content/ImageManipulation/BaseRotateAction.cs
  src/Files.App/UserControls/Toolbar.xaml
  src/Files.App/ViewModels/UserControls/NavigationToolbarViewModel.cs
Labels: needs - code review

#16976 Fix: Fixed crash that would sometimes occur when updating
  src/Files.App/Services/App/AppUpdateSideloadService.cs
Labels: ready to merge

#17034 Code Quality: Switch Storage Provider Status UI APIs to use MemberFunction
  src/Files.App.CsWin32/IStorageProviderQuotaUI.cs
  src/Files.App.CsWin32/IStorageProviderStatusUI.cs
  src/Files.App.CsWin32/IStorageProviderStatusUISource.cs
  src/Files.App.CsWin32/IStorageProviderStatusUISourceFactory.cs
Labels: needs - code review

#17049 Code Quality: Fixed an issue where shell locations wouldn't load
  src/Files.App/ViewModels/ShellViewModel.cs
Labels: ready to merge

#16993 Code Quality: Replaced stack-allocated GUIDs with RVA-inlined GUIDs
  Directory.Packages.props
  src/Files.App.CsWin32/ComPtr`1.cs
  src/Files.App.CsWin32/Files.App.CsWin32.csproj
  src/Files.App.CsWin32/IStorageProviderQuotaUI.cs
  src/Files.App.CsWin32/IStorageProviderStatusUI.cs
  src/Files.App.CsWin32/IStorageProviderStatusUISource.cs
  src/Files.App.CsWin32/IStorageProviderStatusUISourceFactory.cs
  src/Files.App.CsWin32/ManualGuid.cs
  src/Files.App/Services/Storage/StorageTrashBinService.cs
  src/Files.App/Services/Windows/WindowsDialogService.cs
  src/Files.App/Services/Windows/WindowsRecentItemsService.cs
  src/Files.App/Services/Windows/WindowsWallpaperService.cs
  src/Files.App/Utils/Shell/LaunchHelper.cs
  src/Files.App/Utils/Storage/Helpers/SyncRootHelpers.cs
Labels: ready to merge

#17055 Code Quality: Added a credit for Dongle.GuidRVAGen
  .github/NOTICE.md
  src/Files.App/ViewModels/Settings/AboutViewModel.cs
Labels: ready to merge

#17039 Feature: Display banner when all sections are hidden on the sidebar
  src/Files.App.Controls/Sidebar/SidebarView.Properties.cs
  src/Files.App.Controls/Sidebar/SidebarView.xaml
  src/Files.App/Assets/Sidebar/EmptySidebar_100_ThemeDark.svg
  src/Files.App/Assets/Sidebar/EmptySidebar_100_ThemeLight.svg
  src/Files.App/Assets/Sidebar/EmptySidebar_200_ThemeDark.svg
  src/Files.App/Assets/Sidebar/EmptySidebar_200_ThemeLight.svg
  src/Files.App/Assets/Sidebar/EmptySidebar_48_ThemeDark.svg
  src/Files.App/Assets/Sidebar/EmptySidebar_48_ThemeLight.svg
  src/Files.App/Strings/en-US/Resources.resw
  src/Files.App/ViewModels/UserControls/SidebarViewModel.cs
  src/Files.App/Views/MainPage.xaml
  src/Files.App/Views/MainPage.xaml.cs
Labels: ready to merge

#17002 Code Quality: Introduced the new WindowsStorable
  src/Files.App.CsWin32/Extras.cs
  src/Files.App.CsWin32/HRESULT.cs
  src/Files.App.CsWin32/NativeMethods.txt
  src/Files.App.Storage/Files.App.Storage.csproj
  src/Files.App.Storage/Storables/HomeFolder/HomeFolder.cs
  src/Files.App.Storage/Storables/HomeFolder/IHomeFolder.cs
  src/Files.App.Storage/Storables/WindowsStorage/IWindowsStorable.cs
  src/Files.App.Storage/Storables/WindowsStorage/JumpListItem.cs
  src/Files.App.Storage/Storables/WindowsStorage/JumpListItemType.cs
  src/Files.App.Storage/Storables/WindowsStorage/JumpListManager.cs
  src/Files.App.Storage/Storables/WindowsStorage/STATask.cs
  src/Files.App.Storage/Storables/WindowsStorage/TaskbarManager.cs
  src/Files.App.Storage/Storables/WindowsStorage/WindowsBulkOperations.cs
  src/Files.App.Storage/Storables/WindowsStorage/WindowsBulkOperationsEventArgs.cs
  src/Files.App.Storage/Storables/WindowsStorage/WindowsBulkOperationsSink.Methods.cs
  src/Files.App.Storage/Storables/WindowsStorage/WindowsBulkOperationsSink.VTable.cs
  src/Files.App.Storage/Storables/WindowsStorage/WindowsFile.cs
  src/Files.App.Storage/Storables/WindowsStorage/WindowsFolder.cs
  src/Files.App.Storage/Storables/WindowsStorage/WindowsStorable.cs
  src/Files.App.Storage/Storables/WindowsStorage/WindowsStorableHelpers.Icon.cs
  src/Files.App.Storage/Storables/WindowsStorage/WindowsStorableHelpers.PowerShell.cs
  src/Files.App.Storage/Storables/WindowsStorage/WindowsStorableHelpers.Shell.cs
  src/Files.App.Storage/Storables/WindowsStorage/WindowsStorableHelpers.Storage.cs
  src/Files.App/GlobalUsings.cs
  src/Files.App/Helpers/Win32/Win32Helper.Storage.cs
  src/Files.App/Helpers/Win32/Win32PInvoke.Methods.cs
  src/Files.App/Services/Storage/StorageTrashBinService.cs
  src/Files.App/Services/Windows/WindowsJumpListService.cs
Labels: ready to merge

#17045 Feature: Automatically detect zip encoding
  Directory.Packages.props
  src/Files.App/Actions/Content/Archives/Decompress/DecompressArchive.cs
  src/Files.App/Data/Contracts/IStorageArchiveService.cs
  src/Files.App/Data/Items/EncodingItem.cs
  src/Files.App/Files.App.csproj
  src/Files.App/Services/Storage/StorageArchiveService.cs
  src/Files.App/Strings/en-US/Resources.resw
  src/Files.App/ViewModels/Dialogs/DecompressArchiveDialogViewModel.cs
Labels: ready to merge

#17061 Code Quality: Updated translations
  src/Files.App/Strings/af/Resources.resw
  src/Files.App/Strings/ar/Resources.resw
  src/Files.App/Strings/be-BY/Resources.resw
  src/Files.App/Strings/bg/Resources.resw
  src/Files.App/Strings/ca/Resources.resw
  src/Files.App/Strings/cs-CZ/Resources.resw
  src/Files.App/Strings/da/Resources.resw
  src/Files.App/Strings/de-DE/Resources.resw
  src/Files.App/Strings/el/Resources.resw
  src/Files.App/Strings/en-GB/Resources.resw
  src/Files.App/Strings/es-419/Resources.resw
  src/Files.App/Strings/es-ES/Resources.resw
  src/Files.App/Strings/fa-IR/Resources.resw
  src/Files.App/Strings/fi-FI/Resources.resw
  src/Files.App/Strings/fil-PH/Resources.resw
  src/Files.App/Strings/fr-FR/Resources.resw
  src/Files.App/Strings/he-IL/Resources.resw
  src/Files.App/Strings/hi-IN/Resources.resw
  src/Files.App/Strings/hr-HR/Resources.resw
  src/Files.App/Strings/hu-HU/Resources.resw
  src/Files.App/Strings/hy-AM/Resources.resw
  src/Files.App/Strings/id-ID/Resources.resw
  src/Files.App/Strings/it-IT/Resources.resw
  src/Files.App/Strings/ja-JP/Resources.resw
  src/Files.App/Strings/ka/Resources.resw
  src/Files.App/Strings/km-KH/Resources.resw
  src/Files.App/Strings/ko-KR/Resources.resw
  src/Files.App/Strings/lt-LT/Resources.resw
  src/Files.App/Strings/lv-LV/Resources.resw
  src/Files.App/Strings/ms-MY/Resources.resw
  src/Files.App/Strings/nb-NO/Resources.resw
  src/Files.App/Strings/nl-NL/Resources.resw
  src/Files.App/Strings/pl-PL/Resources.resw
  src/Files.App/Strings/pt-BR/Resources.resw
  src/Files.App/Strings/pt-PT/Resources.resw
  src/Files.App/Strings/ro-RO/Resources.resw
  src/Files.App/Strings/ru-RU/Resources.resw
  src/Files.App/Strings/sk-SK/Resources.resw
  src/Files.App/Strings/sq-AL/Resources.resw
  src/Files.App/Strings/sr-Cyrl/Resources.resw
  src/Files.App/Strings/sv-SE/Resources.resw
  src/Files.App/Strings/ta/Resources.resw
  src/Files.App/Strings/th-TH/Resources.resw
  src/Files.App/Strings/tr-TR/Resources.resw
  src/Files.App/Strings/uk-UA/Resources.resw
  src/Files.App/Strings/vi/Resources.resw
  src/Files.App/Strings/zh-Hans/Resources.resw
  src/Files.App/Strings/zh-Hant/Resources.resw
Labels: ready to merge

#17057 Fix: Fixed issue where the LucidLink v3 Icon was not displayed
  src/Files.App/Utils/Cloud/CloudDrivesDetector.cs
  src/Files.App/Utils/Cloud/Detector/CloudDetector.cs
  src/Files.App/Utils/Cloud/Detector/LucidLinkCloudDetector.cs
Labels: ready to merge

#17071 Code Quality: Improved the new Windows thumbnail API
  src/Files.App.CsWin32/Extras.cs
  src/Files.App.CsWin32/NativeMethods.txt
  src/Files.App.Storage/Storables/HomeFolder/HomeFolder.cs
  src/Files.App.Storage/Storables/WindowsStorage/IWindowsStorable.cs
  src/Files.App.Storage/Storables/WindowsStorage/WindowsFile.cs
  src/Files.App.Storage/Storables/WindowsStorage/WindowsFolder.cs
  src/Files.App.Storage/Storables/WindowsStorage/WindowsStorable.cs
  src/Files.App.Storage/Storables/WindowsStorage/WindowsStorableHelpers.Icon.cs
  src/Files.App.Storage/Storables/WindowsStorage/WindowsStorableHelpers.Shell.cs
Labels: ready to merge

#17083 Fix: Fixed crash that would occur when using an invalid background image
  src/Files.App/ViewModels/MainPageViewModel.cs
Labels: ready to merge

#17023 Feature: Introduced Omnibar 1
  src/Files.App.Controls/Omnibar/Omnibar.Events.cs
  src/Files.App.Controls/Omnibar/Omnibar.Properties.cs
  src/Files.App.Controls/Omnibar/Omnibar.cs
  src/Files.App.Controls/Omnibar/Omnibar.xaml
  src/Files.App.Controls/Omnibar/OmnibarMode.Properties.cs
  src/Files.App/Data/Items/NavigationBarSuggestionItem.cs
  src/Files.App/Data/Models/BreadcrumbBarItemModel.cs
  src/Files.App/Data/Models/OmnibarPathModeSuggestionModel.cs
  src/Files.App/Strings/en-US/Resources.resw
  src/Files.App/UserControls/NavigationToolbar.xaml
  src/Files.App/UserControls/NavigationToolbar.xaml.cs
  src/Files.App/UserControls/PathBreadcrumb.xaml.cs
  src/Files.App/ViewModels/UserControls/NavigationToolbarViewModel.cs
  src/Files.App/Views/Shells/BaseShellPage.cs
Labels: ready to merge
